// framework/frontend/angular/src/profile/HilosProfileSignInPage.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  afterRenderEffect,
  computed,
  effect,
  input,
  signal,
  viewChild,
} from '@angular/core'
import {
  createHilosProfileAddSignInFlow,
  createHilosProfilePasswordChangeFlow,
  createHilosProfileSignInActions,
  createSignal,
  focusInitial,
  hilosProfileLinkableProviders,
  hilosProfilePasswordState,
  hilosProfileSignInSubtitle,
  hilosProfileSignInTitle,
  HILOS_PROFILE_SIGN_IN_COPY,
  hilosToasts,
  isPasskeySupported,
  PROFILE_PASSWORD_MODE_ADDED,
  sessionAuthMethods,
  subscribeSignal,
  watchHilosProfilePasswordUpdated,
  type AuthMethodEntry,
  type HilosAuthContext,
  type HilosProfileAddSignInStep,
  type HilosProfilePasswordChangeStep,
  type HilosProfileSignInMethod,
} from '@hilos/core'
import { HilosProfilePasswordChange } from './HilosProfilePasswordChange.js'
import { HilosActionError } from '../HilosActionError.js'
import { HilosFormError } from '../HilosFormError.js'
import { HilosModal } from '../HilosModal.js'
import { HilosPageHeading } from '../HilosPageHeading.js'
import { LoadingButton } from '../LoadingButton.js'
import { createHilosTrackedAction } from '../hilosTrackedAction.js'

const PASSWORD_MIN = 8
const emptyDraft = () => ({
  email: '',
  phone: '',
  code: '',
  newPassword: '',
  confirm: '',
})
let signInSequence = 0

/** The account's methods and the dialogs that add, change and remove them. */
@Component({
  selector: 'hilos-profile-sign-in-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    HilosProfilePasswordChange,
    HilosActionError,
    HilosFormError,
    HilosModal,
    HilosPageHeading,
    LoadingButton,
  ],
  template: `
    <section data-id="profile-sign-in-view">
      <hilos-page-heading />
      @if (methods().length === 0) {
        <p class="text-body-secondary">No ways to sign in.</p>
      }
      <div data-id="profile-identities-list">
        @for (method of methods(); track method.key) {
          <div
            class="d-flex flex-wrap align-items-center gap-3 py-3 border-bottom"
            data-id="profile-identity-item"
            [attr.data-identity-key]="method.key"
          >
            <div class="flex-grow-1 text-break">
              <div class="fw-semibold" data-id="identity-type">
                {{ title(method) }}
              </div>
              <div
                class="small text-body-secondary"
                [attr.data-id]="
                  method.type === 'passkey'
                    ? 'identity-passkey-added'
                    : 'identity-identifier'
                "
              >
                {{ subtitle(method) }}
              </div>
              @if (method.verified) {
                <span class="badge text-bg-success" data-id="identity-verified"
                  >Verified</span
                >
              } @else {
                <span
                  class="badge text-bg-secondary"
                  data-id="identity-unverified"
                  >Unverified</span
                >
              }
              @if (!method.canUnlink) {
                <div
                  class="small text-warning-emphasis"
                  data-id="identity-unlink-blocked"
                >
                  {{ copy.onlyMethod }}
                </div>
              }
            </div>
            <div class="d-flex gap-2">
              @if (method.type === 'password') {
                <button
                  class="btn btn-sm btn-outline-secondary"
                  type="button"
                  hilosLoadingButton
                  [loading]="passwordStep() === 'opening'"
                  data-id="profile-password-change"
                  (click)="passwordFlow().open()"
                >
                  Change
                </button>
              }
              <button
                class="btn btn-sm btn-outline-secondary"
                type="button"
                [disabled]="!method.canUnlink"
                data-id="identity-unlink"
                (click)="askUnlink(method)"
              >
                {{ method.type === 'oauth' ? 'Unlink' : 'Remove' }}
              </button>
            </div>
          </div>
        }
      </div>
      <button
        class="btn btn-sm btn-outline-primary mt-3"
        type="button"
        data-id="profile-sign-in-add"
        (click)="openAdd()"
      >
        Add a way to sign in
      </button>
      <hilos-modal
        [open]="unlinkKey() !== null"
        (openChange)="closeUnlink($event)"
        [title]="unlinkTitle()"
        initialFocus="dialog"
        [closeOnEsc]="!unlinkAction.busy()"
        [closeOnBackdrop]="!unlinkAction.busy()"
      >
        <div data-id="profile-unlink-modal">
          <p>
            You will no longer be able to sign in with {{ unlinkName() }}. You
            can still use: {{ remaining() }}.
          </p>
          <div data-id="profile-unlink-error">
            <hilos-action-error
              [action]="unlinkAction"
              detailsTitle="Couldn't remove the sign-in method"
            />
          </div>
        </div>
        <ng-template #modalActions let-requestClose="requestClose">
          <button
            type="button"
            class="btn btn-secondary"
            [disabled]="unlinkAction.busy()"
            data-id="identity-unlink-cancel"
            (click)="requestClose()"
          >
            Cancel
          </button>
          <button
            hilosLoadingButton
            class="btn btn-danger"
            [loading]="unlinkAction.loading()"
            [disabled]="unlinkAction.busy()"
            data-id="identity-unlink-yes"
            (click)="remove()"
          >
            Remove
          </button>
        </ng-template>
      </hilos-modal>
      <hilos-profile-password-change [flow]="passwordFlow()" />

      <hilos-modal
        [open]="step() !== 'closed'"
        (openChange)="closeAdd($event)"
        title="Add a way to sign in"
        initialFocus="dialog"
        [confirmOnClose]="addDirty()"
      >
        <div #addBody data-id="profile-sign-in-add-modal">
          <div
            class="visually-hidden"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-id="profile-sign-in-add-live"
          >
            {{ refusal() }}
          </div>
          <div class="hilos-stack">
            <div class="invisible" aria-hidden="true" inert>
              @for (
                label of ['Code', 'New password', 'Confirm new password'];
                track label
              ) {
                <div class="mb-3">
                  <div class="form-label">{{ label }}</div>
                  <div class="form-control">&nbsp;</div>
                </div>
              }
              <div class="form-text">{{ copy.passwordHint }}</div>
            </div>
            <div
              class="invisible d-flex flex-column gap-2"
              aria-hidden="true"
              inert
            >
              @if (!passwordState().hasPassword) {
                <span class="btn btn-outline-secondary"
                  ><span class="d-flex align-items-center gap-3 text-start"
                    ><i class="bi bi-lock fs-5" aria-hidden="true"></i
                    ><span
                      ><span class="d-block fw-semibold small">Password</span
                      ><span class="d-block small text-body-secondary">{{
                        copy.passwordDescription
                      }}</span></span
                    ></span
                  ></span
                >
              }
              <span class="btn btn-outline-secondary"
                ><span class="d-flex align-items-center gap-3 text-start"
                  ><i class="bi bi-phone fs-5" aria-hidden="true"></i
                  ><span
                    ><span class="d-block fw-semibold small">Phone</span
                    ><span class="d-block small text-body-secondary">{{
                      copy.phoneDescription
                    }}</span></span
                  ></span
                ></span
              >
              @for (entry of providers(); track entry.key) {
                <span class="btn btn-outline-secondary"
                  ><span class="d-flex align-items-center gap-3 text-start"
                    ><i
                      class="bi bi-box-arrow-in-right fs-5"
                      aria-hidden="true"
                    ></i
                    ><span
                      ><span class="d-block fw-semibold small">{{
                        entry.label
                      }}</span
                      ><span class="d-block small text-body-secondary">{{
                        copy.providerDescription
                      }}</span></span
                    ></span
                  ></span
                >
              }
              @if (passkeySupported) {
                <span class="btn btn-outline-secondary"
                  ><span class="d-flex align-items-center gap-3 text-start"
                    ><i class="bi bi-fingerprint fs-5" aria-hidden="true"></i
                    ><span
                      ><span class="d-block fw-semibold small">Passkey</span
                      ><span class="d-block small text-body-secondary">{{
                        copy.passkeyDescription
                      }}</span></span
                    ></span
                  ></span
                >
              }
            </div>
            @if (step() === 'choose') {
              <div class="d-flex flex-column gap-2 align-self-start">
                @if (!passwordState().hasPassword) {
                  <button
                    type="button"
                    class="btn btn-outline-secondary"
                    [disabled]="busy()"
                    data-id="profile-sign-in-choose-password"
                    (click)="flow().choosePassword()"
                  >
                    <span class="d-flex align-items-center gap-3 text-start"
                      ><i class="bi bi-lock fs-5" aria-hidden="true"></i
                      ><span
                        ><span class="d-block fw-semibold small">Password</span
                        ><span class="d-block small text-body-secondary">{{
                          copy.passwordDescription
                        }}</span></span
                      ></span
                    >
                  </button>
                }
                <button
                  type="button"
                  class="btn btn-outline-secondary"
                  [disabled]="busy()"
                  data-id="profile-sign-in-choose-phone"
                  (click)="flow().choosePhone()"
                >
                  <span class="d-flex align-items-center gap-3 text-start"
                    ><i class="bi bi-phone fs-5" aria-hidden="true"></i
                    ><span
                      ><span class="d-block fw-semibold small">Phone</span
                      ><span class="d-block small text-body-secondary">{{
                        copy.phoneDescription
                      }}</span></span
                    ></span
                  >
                </button>
                @for (entry of providers(); track entry.key) {
                  <button
                    hilosLoadingButton
                    class="btn btn-outline-secondary"
                    [loading]="busy() && pendingProvider() === entry.key"
                    [disabled]="busy()"
                    [attr.data-id]="'profile-oauth-link-' + entry.key"
                    (click)="flow().chooseProvider(entry.key)"
                  >
                    <span class="d-flex align-items-center gap-3 text-start"
                      ><i
                        class="bi bi-box-arrow-in-right fs-5"
                        aria-hidden="true"
                      ></i
                      ><span
                        ><span class="d-block fw-semibold small">{{
                          entry.label
                        }}</span
                        ><span class="d-block small text-body-secondary">{{
                          copy.providerDescription
                        }}</span></span
                      ></span
                    >
                  </button>
                }
                @if (passkeySupported) {
                  <button
                    hilosLoadingButton
                    class="btn btn-outline-secondary"
                    [loading]="busy() && pendingProvider() === null"
                    [disabled]="busy()"
                    data-id="profile-passkey-add"
                    (click)="flow().choosePasskey()"
                  >
                    <span class="d-flex align-items-center gap-3 text-start"
                      ><i class="bi bi-fingerprint fs-5" aria-hidden="true"></i
                      ><span
                        ><span class="d-block fw-semibold small">Passkey</span
                        ><span class="d-block small text-body-secondary">{{
                          copy.passkeyDescription
                        }}</span></span
                      ></span
                    >
                  </button>
                }
              </div>
            } @else {
              <form
                [id]="baseId + '-add'"
                class="align-self-start"
                (submit)="$event.preventDefault(); submitAdd()"
              >
                @for (field of fields(); track field.key; let first = $first) {
                  <div class="mb-3">
                    <label
                      [attr.for]="baseId + '-add-' + field.key"
                      class="form-label"
                      >{{ field.label }}</label
                    >
                    <input
                      [id]="baseId + '-add-' + field.key"
                      [value]="draft()[field.key]"
                      (input)="setDraftField(field.key, valueOf($event))"
                      [type]="field.type"
                      [attr.autocomplete]="field.autocomplete"
                      class="form-control"
                      [attr.data-id]="field.dataId"
                      [attr.aria-describedby]="
                        field.type === 'password'
                          ? baseId + '-add-password-hint'
                          : null
                      "
                      [attr.data-autofocus]="first ? '' : null"
                    />
                  </div>
                }
                @if (step() === 'password-new' || step() === 'password-code') {
                  <div
                    [id]="baseId + '-add-password-hint'"
                    class="form-text"
                    data-id="profile-add-password-hint"
                  >
                    {{ copy.passwordHint }}
                  </div>
                }
              </form>
            }
          </div>
          <hilos-form-error [message]="refusal()" [dataId]="errorId()" />
        </div>
        <ng-template #modalActions let-requestClose="requestClose">
          <button
            type="button"
            class="btn btn-secondary"
            data-id="profile-sign-in-add-cancel"
            (click)="requestClose()"
          >
            Cancel
          </button>
          @if (step() !== 'choose') {
            <button
              type="button"
              class="btn btn-outline-secondary"
              [disabled]="busy()"
              data-id="profile-sign-in-add-back"
              (click)="flow().back()"
            >
              Back
            </button>
            <button
              hilosLoadingButton
              type="submit"
              [attr.form]="baseId + '-add'"
              class="btn btn-primary"
              [loading]="busy()"
              [disabled]="!addValid() || busy()"
              [attr.data-id]="submitId()"
            >
              {{
                step() === 'password-email' || step() === 'phone-number'
                  ? 'Send code'
                  : 'Save'
              }}
            </button>
          }
        </ng-template>
      </hilos-modal>
    </section>
  `,
})
export class HilosProfileSignInPage {
  readonly context = input.required<HilosAuthContext>()
  readonly methods = input.required<readonly HilosProfileSignInMethod[]>()
  private readonly methodsSignal = createSignal<
    readonly HilosProfileSignInMethod[]
  >([])
  private readonly offered = signal<readonly AuthMethodEntry[]>([])
  protected readonly providers = computed(() =>
    hilosProfileLinkableProviders(this.methods(), this.offered()),
  )
  protected readonly passwordState = computed(() =>
    hilosProfilePasswordState(this.methods()),
  )
  protected readonly passkeySupported = isPasskeySupported()
  private readonly actions = computed(() =>
    createHilosProfileSignInActions(this.context()),
  )
  protected readonly baseId = `hilos-profile-sign-in-${signInSequence++}`
  protected readonly copy = HILOS_PROFILE_SIGN_IN_COPY
  protected readonly subtitle = hilosProfileSignInSubtitle
  protected readonly unlinkKey = signal<string | null>(null)
  protected readonly unlinkMethod = computed(() =>
    this.methods().find((method) => method.key === this.unlinkKey()),
  )
  protected readonly unlinkName = computed(() => {
    const method = this.unlinkMethod()
    return method ? this.title(method) : 'this method'
  })
  protected readonly unlinkTitle = computed(
    () => `Remove ${this.unlinkName()}?`,
  )
  protected readonly remaining = computed(() =>
    this.methods()
      .filter((method) => method.key !== this.unlinkKey())
      .map((method) => this.title(method))
      .join(', '),
  )
  protected readonly unlinkAction = createHilosTrackedAction()
  protected readonly passwordFlow = computed(() =>
    createHilosProfilePasswordChangeFlow(this.context()),
  )
  protected readonly passwordStep =
    signal<HilosProfilePasswordChangeStep>('closed')
  protected readonly flow = computed(() =>
    createHilosProfileAddSignInFlow(this.context(), this.methodsSignal),
  )
  protected readonly step = signal<HilosProfileAddSignInStep>('closed')
  protected readonly busy = signal(false)
  protected readonly refusal = signal<string | null>(null)
  protected readonly pendingProvider = signal<string | null>(null)
  protected readonly draft = signal(emptyDraft())
  private readonly addBody = viewChild<ElementRef<HTMLElement>>('addBody')
  protected readonly addDirty = computed(() =>
    Object.values(this.draft()).some((value) => value !== ''),
  )
  protected readonly fields = computed(() => {
    const step = this.step()
    const passwordFields = [
      {
        key: 'newPassword' as const,
        label: 'New password',
        type: 'password',
        autocomplete: 'new-password',
        dataId: 'profile-add-password-new',
      },
      {
        key: 'confirm' as const,
        label: 'Confirm new password',
        type: 'password',
        autocomplete: 'new-password',
        dataId: 'profile-add-password-confirm',
      },
    ]
    const codeField = {
      key: 'code' as const,
      label: 'Code',
      type: 'text',
      autocomplete: 'one-time-code',
      dataId:
        step === 'phone-code'
          ? 'profile-add-sms-code'
          : 'profile-add-password-code',
    }
    return step === 'password-email'
      ? [
          {
            key: 'email' as const,
            label: 'Email',
            type: 'email',
            autocomplete: 'email',
            dataId: 'profile-add-password-email',
          },
        ]
      : step === 'phone-number'
        ? [
            {
              key: 'phone' as const,
              label: 'Phone number',
              type: 'tel',
              autocomplete: 'tel',
              dataId: 'profile-add-sms-phone',
            },
          ]
        : step === 'phone-code'
          ? [codeField]
          : step === 'password-new'
            ? passwordFields
            : step === 'password-code'
              ? [codeField, ...passwordFields]
              : []
  })
  protected readonly addValid = computed(
    () =>
      this.fields().every(
        (field) =>
          (field.type === 'password'
            ? this.draft()[field.key]
            : this.draft()[field.key].trim()) !== '',
      ) &&
      (!this.step().startsWith('password-') ||
        this.step() === 'password-email' ||
        (this.draft().newPassword.length >= PASSWORD_MIN &&
          this.draft().newPassword === this.draft().confirm)),
  )
  protected readonly submitId = computed(() =>
    this.step() === 'phone-number'
      ? 'profile-add-sms-request'
      : this.step() === 'phone-code'
        ? 'profile-add-sms-confirm'
        : this.step() === 'password-email'
          ? 'profile-add-password-request'
          : 'profile-add-password-save',
  )
  protected readonly errorId = computed(() =>
    this.step().startsWith('phone-')
      ? 'profile-add-sms-error'
      : this.step().startsWith('password-')
        ? 'profile-add-password-error'
        : 'profile-sign-in-add-error',
  )

  constructor() {
    effect((onCleanup) => {
      const flow = this.passwordFlow()
      this.passwordStep.set(flow.step.get())
      const off = subscribeSignal(flow.step, (value) =>
        this.passwordStep.set(value),
      )
      onCleanup(() => {
        off()
        flow.dispose()
      })
    })
    effect(() => this.methodsSignal.set(this.methods()))
    effect(() => {
      if (this.unlinkKey() !== null && !this.unlinkMethod())
        this.unlinkKey.set(null)
    })
    effect((onCleanup) => {
      const offered = sessionAuthMethods(this.context().scopes)
      this.offered.set(offered.get())
      onCleanup(subscribeSignal(offered, (value) => this.offered.set(value)))
    })
    effect((onCleanup) => {
      const flow = this.flow()
      this.step.set(flow.step.get())
      this.busy.set(flow.busy.get())
      this.refusal.set(flow.refusal.get())
      this.pendingProvider.set(flow.provider.get())
      const stops = [
        subscribeSignal(flow.step, (value) => this.step.set(value)),
        subscribeSignal(flow.busy, (value) => this.busy.set(value)),
        subscribeSignal(flow.refusal, (value) => this.refusal.set(value)),
        subscribeSignal(flow.provider, (value) =>
          this.pendingProvider.set(value),
        ),
      ]
      onCleanup(() => {
        for (const stop of stops) stop()
        flow.dispose()
      })
    })
    effect((onCleanup) => {
      onCleanup(
        watchHilosProfilePasswordUpdated(this.context().connection, (data) => {
          if (this.passwordFlow().step.get() !== 'closed') return
          hilosToasts.push(
            data.mode === PROFILE_PASSWORD_MODE_ADDED
              ? this.copy.passwordAdded
              : this.copy.passwordChanged,
            { severity: 'success' },
          )
        }),
      )
    })
    afterRenderEffect(() => {
      this.step()
      const dialog =
        this.addBody()?.nativeElement.closest<HTMLElement>('[role="dialog"]')
      if (dialog) focusInitial(dialog)
    })
  }
  protected title(method: HilosProfileSignInMethod): string {
    return hilosProfileSignInTitle(method, this.offered())
  }
  protected valueOf(event: Event): string {
    return (event.target as HTMLInputElement).value
  }
  protected setDraftField(
    key: keyof ReturnType<typeof emptyDraft>,
    value: string,
  ): void {
    this.draft.update((draft) => ({ ...draft, [key]: value }))
  }
  protected askUnlink(method: HilosProfileSignInMethod): void {
    if (!method.canUnlink || this.unlinkAction.busy()) return
    this.unlinkAction.clearError()
    this.unlinkKey.set(method.key)
  }
  protected closeUnlink(open: boolean): void {
    if (!open && !this.unlinkAction.busy()) this.unlinkKey.set(null)
  }
  protected async remove(): Promise<void> {
    const key = this.unlinkKey()
    if (key === null || this.unlinkAction.busy()) return
    if (await this.unlinkAction.run(this.actions().unlinkIdentity(Number(key))))
      this.unlinkKey.set(null)
  }
  protected openAdd(): void {
    this.draft.set(emptyDraft())
    this.flow().open()
  }
  protected closeAdd(open: boolean): void {
    if (!open) this.flow().close()
  }
  protected async submitAdd(): Promise<void> {
    if (!this.addValid() || this.busy()) return
    const draft = this.draft()
    switch (this.step()) {
      case 'password-new':
        await this.flow().submitPasswordNew(draft.newPassword)
        break
      case 'password-email':
        await this.flow().submitPasswordEmail(draft.email.trim())
        break
      case 'password-code':
        await this.flow().submitPasswordCode(
          draft.code.trim(),
          draft.newPassword,
        )
        break
      case 'phone-number':
        await this.flow().submitPhone(draft.phone.trim())
        break
      case 'phone-code':
        await this.flow().submitPhoneCode(draft.code.trim())
        break
    }
  }
}

// framework/frontend/react/src/profile/HilosProfileSignInPage.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react'
import {
  createHilosProfileAddSignInFlow,
  createHilosProfilePasswordChangeFlow,
  createHilosProfileSignInActions,
  createSignal,
  focusInitial,
  hilosProfileLinkableProviders,
  hilosProfilePasswordState,
  hilosProfileSignInSubtitle,
  hilosProfileSignInTitle,
  HILOS_PROFILE_SIGN_IN_COPY,
  hilosToasts,
  isPasskeySupported,
  PROFILE_PASSWORD_MODE_ADDED,
  sessionAuthMethods,
  watchHilosProfilePasswordUpdated,
  type HilosAuthContext,
  type HilosProfileSignInMethod,
} from '@hilos/core'
import { HilosProfilePasswordChange } from './HilosProfilePasswordChange.js'
import { HilosActionError } from '../HilosActionError.js'
import { HilosFormError } from '../HilosFormError.js'
import { HilosModal } from '../HilosModal.js'
import { HilosPageHeading } from '../HilosPageHeading.js'
import { LoadingButton } from '../LoadingButton.js'
import { useSignal } from '../useSignal.js'
import { useTrackedAction } from '../useTrackedAction.js'

const PASSWORD_MIN = 8
const emptyDraft = () => ({
  email: '',
  phone: '',
  code: '',
  newPassword: '',
  confirm: '',
})

/** The account's methods and the dialogs that add, change and remove them. */
export function HilosProfileSignInPage({
  context,
  methods,
}: {
  context: HilosAuthContext
  methods: readonly HilosProfileSignInMethod[]
}) {
  const methodsSignal = useMemo(() => createSignal(methods), [])
  useEffect(() => methodsSignal.set(methods), [methodsSignal, methods])
  const offeredSignal = useMemo(
    () => sessionAuthMethods(context.scopes),
    [context.scopes],
  )
  const offered = useSignal(offeredSignal)
  const providers = hilosProfileLinkableProviders(methods, offered)
  const passwordState = hilosProfilePasswordState(methods)
  const passkeySupported = isPasskeySupported()
  const actions = useMemo(
    () => createHilosProfileSignInActions(context),
    [context],
  )
  const baseId = useId()
  const title = (method: HilosProfileSignInMethod) =>
    hilosProfileSignInTitle(method, offered)

  const [unlinkKey, setUnlinkKey] = useState<string | null>(null)
  const unlinkMethod = methods.find((method) => method.key === unlinkKey)
  const remaining = methods
    .filter((method) => method.key !== unlinkKey)
    .map(title)
    .join(', ')
  const unlinkAction = useTrackedAction()
  const removing = useRef(false)
  useEffect(() => {
    if (
      unlinkKey !== null &&
      !methods.some((method) => method.key === unlinkKey)
    )
      setUnlinkKey(null)
  }, [methods, unlinkKey])
  function askUnlink(method: HilosProfileSignInMethod): void {
    if (!method.canUnlink || removing.current) return
    unlinkAction.clearError()
    setUnlinkKey(method.key)
  }
  async function remove(): Promise<void> {
    if (unlinkKey === null || removing.current) return
    removing.current = true
    if (await unlinkAction.run(actions.unlinkIdentity(Number(unlinkKey))))
      setUnlinkKey(null)
    removing.current = false
  }

  const passwordFlow = useMemo(
    () => createHilosProfilePasswordChangeFlow(context),
    [context],
  )
  const passwordStep = useSignal(passwordFlow.step)
  useEffect(() => () => passwordFlow.dispose(), [passwordFlow])
  useEffect(
    () =>
      watchHilosProfilePasswordUpdated(context.connection, (data) => {
        if (passwordFlow.step.get() !== 'closed') return
        hilosToasts.push(
          data.mode === PROFILE_PASSWORD_MODE_ADDED
            ? HILOS_PROFILE_SIGN_IN_COPY.passwordAdded
            : HILOS_PROFILE_SIGN_IN_COPY.passwordChanged,
          { severity: 'success' },
        )
      }),
    [context.connection, passwordFlow],
  )

  const flow = useMemo(
    () => createHilosProfileAddSignInFlow(context, methodsSignal),
    [context, methodsSignal],
  )
  useEffect(() => () => flow.dispose(), [flow])
  const step = useSignal(flow.step)
  const busy = useSignal(flow.busy)
  const refusal = useSignal(flow.refusal)
  const pendingProvider = useSignal(flow.provider)
  const [draft, setDraft] = useState(emptyDraft)
  const addBody = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const dialog = addBody.current?.closest<HTMLElement>('[role="dialog"]')
    if (dialog) focusInitial(dialog)
  }, [step])
  function openAdd(): void {
    setDraft(emptyDraft())
    flow.open()
  }
  const passwordFields = [
    {
      key: 'newPassword' as const,
      label: 'New password',
      type: 'password',
      autocomplete: 'new-password',
      dataId: 'profile-add-password-new',
    },
    {
      key: 'confirm' as const,
      label: 'Confirm new password',
      type: 'password',
      autocomplete: 'new-password',
      dataId: 'profile-add-password-confirm',
    },
  ]
  const codeField = {
    key: 'code' as const,
    label: 'Code',
    type: 'text',
    autocomplete: 'one-time-code',
    dataId:
      step === 'phone-code'
        ? 'profile-add-sms-code'
        : 'profile-add-password-code',
  }
  const fields =
    step === 'password-email'
      ? [
          {
            key: 'email' as const,
            label: 'Email',
            type: 'email',
            autocomplete: 'email',
            dataId: 'profile-add-password-email',
          },
        ]
      : step === 'phone-number'
        ? [
            {
              key: 'phone' as const,
              label: 'Phone number',
              type: 'tel',
              autocomplete: 'tel',
              dataId: 'profile-add-sms-phone',
            },
          ]
        : step === 'phone-code'
          ? [codeField]
          : step === 'password-new'
            ? passwordFields
            : step === 'password-code'
              ? [codeField, ...passwordFields]
              : []
  const addValid =
    fields.every(
      (field) =>
        (field.type === 'password'
          ? draft[field.key]
          : draft[field.key].trim()) !== '',
    ) &&
    (!step.startsWith('password-') ||
      step === 'password-email' ||
      (draft.newPassword.length >= PASSWORD_MIN &&
        draft.newPassword === draft.confirm))
  const submitId =
    step === 'phone-number'
      ? 'profile-add-sms-request'
      : step === 'phone-code'
        ? 'profile-add-sms-confirm'
        : step === 'password-email'
          ? 'profile-add-password-request'
          : 'profile-add-password-save'
  const errorId = step.startsWith('phone-')
    ? 'profile-add-sms-error'
    : step.startsWith('password-')
      ? 'profile-add-password-error'
      : 'profile-sign-in-add-error'
  async function submitAdd(): Promise<void> {
    if (!addValid || busy) return
    switch (step) {
      case 'password-new':
        await flow.submitPasswordNew(draft.newPassword)
        break
      case 'password-email':
        await flow.submitPasswordEmail(draft.email.trim())
        break
      case 'password-code':
        await flow.submitPasswordCode(draft.code.trim(), draft.newPassword)
        break
      case 'phone-number':
        await flow.submitPhone(draft.phone.trim())
        break
      case 'phone-code':
        await flow.submitPhoneCode(draft.code.trim())
        break
    }
  }

  return (
    <section data-id="profile-sign-in-view">
      <HilosPageHeading />
      {methods.length === 0 ? (
        <p className="text-body-secondary">No ways to sign in.</p>
      ) : null}
      <div data-id="profile-identities-list">
        {methods.map((method) => (
          <div
            key={method.key}
            className="d-flex flex-wrap align-items-center gap-3 py-3 border-bottom"
            data-id="profile-identity-item"
            data-identity-key={method.key}
          >
            <div className="flex-grow-1 text-break">
              <div className="fw-semibold" data-id="identity-type">
                {title(method)}
              </div>
              <div
                className="small text-body-secondary"
                data-id={
                  method.type === 'passkey'
                    ? 'identity-passkey-added'
                    : 'identity-identifier'
                }
              >
                {hilosProfileSignInSubtitle(method)}
              </div>
              {method.verified ? (
                <span
                  className="badge text-bg-success"
                  data-id="identity-verified"
                >
                  Verified
                </span>
              ) : (
                <span
                  className="badge text-bg-secondary"
                  data-id="identity-unverified"
                >
                  Unverified
                </span>
              )}
              {!method.canUnlink ? (
                <div
                  className="small text-warning-emphasis"
                  data-id="identity-unlink-blocked"
                >
                  {HILOS_PROFILE_SIGN_IN_COPY.onlyMethod}
                </div>
              ) : null}
            </div>
            <div className="d-flex gap-2">
              {method.type === 'password' ? (
                <LoadingButton
                  className="btn-sm btn-outline-secondary"
                  loading={passwordStep === 'opening'}
                  data-id="profile-password-change"
                  onClick={() => void passwordFlow.open()}
                >
                  Change
                </LoadingButton>
              ) : null}
              <button
                className="btn btn-sm btn-outline-secondary"
                type="button"
                disabled={!method.canUnlink}
                data-id="identity-unlink"
                onClick={() => askUnlink(method)}
              >
                {method.type === 'oauth' ? 'Unlink' : 'Remove'}
              </button>
            </div>
          </div>
        ))}
      </div>
      <button
        className="btn btn-sm btn-outline-primary mt-3"
        type="button"
        data-id="profile-sign-in-add"
        onClick={openAdd}
      >
        Add a way to sign in
      </button>
      <HilosModal
        open={unlinkKey !== null}
        onClose={() => {
          if (!removing.current) setUnlinkKey(null)
        }}
        title={`Remove ${unlinkMethod ? title(unlinkMethod) : 'sign-in method'}?`}
        initialFocus="dialog"
        closeOnEsc={!unlinkAction.busy}
        closeOnBackdrop={!unlinkAction.busy}
        actions={({ requestClose }) => (
          <>
            <button
              type="button"
              className="btn btn-secondary"
              disabled={unlinkAction.busy}
              data-id="identity-unlink-cancel"
              onClick={requestClose}
            >
              Cancel
            </button>
            <LoadingButton
              className="btn btn-danger"
              loading={unlinkAction.loading}
              disabled={unlinkAction.busy}
              data-id="identity-unlink-yes"
              onClick={() => void remove()}
            >
              Remove
            </LoadingButton>
          </>
        )}
      >
        <div data-id="profile-unlink-modal">
          <p>
            You will no longer be able to sign in with{' '}
            {unlinkMethod ? title(unlinkMethod) : 'this method'}. You can still
            use: {remaining}.
          </p>
          <div data-id="profile-unlink-error">
            <HilosActionError
              action={unlinkAction}
              detailsTitle="Couldn't remove the sign-in method"
            />
          </div>
        </div>
      </HilosModal>
      <HilosProfilePasswordChange flow={passwordFlow} />

      <HilosModal
        open={step !== 'closed'}
        onClose={flow.close}
        title="Add a way to sign in"
        initialFocus="dialog"
        confirmOnClose={Object.values(draft).some((value) => value !== '')}
        actions={({ requestClose }) => (
          <>
            <button
              type="button"
              className="btn btn-secondary"
              data-id="profile-sign-in-add-cancel"
              onClick={requestClose}
            >
              Cancel
            </button>
            {step !== 'choose' ? (
              <>
                <button
                  type="button"
                  className="btn btn-outline-secondary"
                  disabled={busy}
                  data-id="profile-sign-in-add-back"
                  onClick={flow.back}
                >
                  Back
                </button>
                <LoadingButton
                  type="submit"
                  form={`${baseId}-add`}
                  className="btn btn-primary"
                  loading={busy}
                  disabled={!addValid || busy}
                  data-id={submitId}
                >
                  {step === 'password-email' || step === 'phone-number'
                    ? 'Send code'
                    : 'Save'}
                </LoadingButton>
              </>
            ) : null}
          </>
        )}
      >
        <div ref={addBody} data-id="profile-sign-in-add-modal">
          <div
            className="visually-hidden"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-id="profile-sign-in-add-live"
          >
            {refusal}
          </div>
          <div className="hilos-stack">
            <div className="invisible" aria-hidden="true" inert>
              {['Code', 'New password', 'Confirm new password'].map((label) => (
                <div key={label} className="mb-3">
                  <div className="form-label">{label}</div>
                  <div className="form-control">&nbsp;</div>
                </div>
              ))}
              <div className="form-text">
                {HILOS_PROFILE_SIGN_IN_COPY.passwordHint}
              </div>
            </div>
            <div
              className="invisible d-flex flex-column gap-2"
              aria-hidden="true"
              inert
            >
              {!passwordState.hasPassword ? (
                <span className="btn btn-outline-secondary">
                  <span className="d-flex align-items-center gap-3 text-start">
                    <i className="bi bi-lock fs-5" aria-hidden="true"></i>
                    <span>
                      <span className="d-block fw-semibold small">
                        Password
                      </span>
                      <span className="d-block small text-body-secondary">
                        {HILOS_PROFILE_SIGN_IN_COPY.passwordDescription}
                      </span>
                    </span>
                  </span>
                </span>
              ) : null}
              <span className="btn btn-outline-secondary">
                <span className="d-flex align-items-center gap-3 text-start">
                  <i className="bi bi-phone fs-5" aria-hidden="true"></i>
                  <span>
                    <span className="d-block fw-semibold small">Phone</span>
                    <span className="d-block small text-body-secondary">
                      {HILOS_PROFILE_SIGN_IN_COPY.phoneDescription}
                    </span>
                  </span>
                </span>
              </span>
              {providers.map((entry) => (
                <span key={entry.key} className="btn btn-outline-secondary">
                  <span className="d-flex align-items-center gap-3 text-start">
                    <i
                      className="bi bi-box-arrow-in-right fs-5"
                      aria-hidden="true"
                    ></i>
                    <span>
                      <span className="d-block fw-semibold small">
                        {entry.label}
                      </span>
                      <span className="d-block small text-body-secondary">
                        {HILOS_PROFILE_SIGN_IN_COPY.providerDescription}
                      </span>
                    </span>
                  </span>
                </span>
              ))}
              {passkeySupported ? (
                <span className="btn btn-outline-secondary">
                  <span className="d-flex align-items-center gap-3 text-start">
                    <i
                      className="bi bi-fingerprint fs-5"
                      aria-hidden="true"
                    ></i>
                    <span>
                      <span className="d-block fw-semibold small">Passkey</span>
                      <span className="d-block small text-body-secondary">
                        {HILOS_PROFILE_SIGN_IN_COPY.passkeyDescription}
                      </span>
                    </span>
                  </span>
                </span>
              ) : null}
            </div>
            {step === 'choose' ? (
              <div className="d-flex flex-column gap-2 align-self-start">
                {!passwordState.hasPassword ? (
                  <button
                    type="button"
                    className="btn btn-outline-secondary"
                    disabled={busy}
                    data-id="profile-sign-in-choose-password"
                    onClick={flow.choosePassword}
                  >
                    <span className="d-flex align-items-center gap-3 text-start">
                      <i className="bi bi-lock fs-5" aria-hidden="true"></i>
                      <span>
                        <span className="d-block fw-semibold small">
                          Password
                        </span>
                        <span className="d-block small text-body-secondary">
                          {HILOS_PROFILE_SIGN_IN_COPY.passwordDescription}
                        </span>
                      </span>
                    </span>
                  </button>
                ) : null}
                <button
                  type="button"
                  className="btn btn-outline-secondary"
                  disabled={busy}
                  data-id="profile-sign-in-choose-phone"
                  onClick={flow.choosePhone}
                >
                  <span className="d-flex align-items-center gap-3 text-start">
                    <i className="bi bi-phone fs-5" aria-hidden="true"></i>
                    <span>
                      <span className="d-block fw-semibold small">Phone</span>
                      <span className="d-block small text-body-secondary">
                        {HILOS_PROFILE_SIGN_IN_COPY.phoneDescription}
                      </span>
                    </span>
                  </span>
                </button>
                {providers.map((entry) => (
                  <LoadingButton
                    key={entry.key}
                    className="btn btn-outline-secondary"
                    loading={busy && pendingProvider === entry.key}
                    disabled={busy}
                    data-id={`profile-oauth-link-${entry.key}`}
                    onClick={() => void flow.chooseProvider(entry.key)}
                  >
                    <span className="d-flex align-items-center gap-3 text-start">
                      <i
                        className="bi bi-box-arrow-in-right fs-5"
                        aria-hidden="true"
                      ></i>
                      <span>
                        <span className="d-block fw-semibold small">
                          {entry.label}
                        </span>
                        <span className="d-block small text-body-secondary">
                          {HILOS_PROFILE_SIGN_IN_COPY.providerDescription}
                        </span>
                      </span>
                    </span>
                  </LoadingButton>
                ))}
                {passkeySupported ? (
                  <LoadingButton
                    className="btn btn-outline-secondary"
                    loading={busy && pendingProvider === null}
                    disabled={busy}
                    data-id="profile-passkey-add"
                    onClick={() => void flow.choosePasskey()}
                  >
                    <span className="d-flex align-items-center gap-3 text-start">
                      <i
                        className="bi bi-fingerprint fs-5"
                        aria-hidden="true"
                      ></i>
                      <span>
                        <span className="d-block fw-semibold small">
                          Passkey
                        </span>
                        <span className="d-block small text-body-secondary">
                          {HILOS_PROFILE_SIGN_IN_COPY.passkeyDescription}
                        </span>
                      </span>
                    </span>
                  </LoadingButton>
                ) : null}
              </div>
            ) : (
              <form
                id={`${baseId}-add`}
                className="align-self-start"
                onSubmit={(event) => {
                  event.preventDefault()
                  void submitAdd()
                }}
              >
                {fields.map((field, index) => (
                  <div key={field.key} className="mb-3">
                    <label
                      htmlFor={`${baseId}-add-${field.key}`}
                      className="form-label"
                    >
                      {field.label}
                    </label>
                    <input
                      id={`${baseId}-add-${field.key}`}
                      value={draft[field.key]}
                      onChange={(event) =>
                        setDraft({ ...draft, [field.key]: event.target.value })
                      }
                      type={field.type}
                      autoComplete={field.autocomplete}
                      className="form-control"
                      data-id={field.dataId}
                      aria-describedby={
                        field.type === 'password'
                          ? `${baseId}-add-password-hint`
                          : undefined
                      }
                      data-autofocus={index === 0 ? '' : undefined}
                    />
                  </div>
                ))}
                {step === 'password-new' || step === 'password-code' ? (
                  <div
                    id={`${baseId}-add-password-hint`}
                    className="form-text"
                    data-id="profile-add-password-hint"
                  >
                    {HILOS_PROFILE_SIGN_IN_COPY.passwordHint}
                  </div>
                ) : null}
              </form>
            )}
          </div>
          <HilosFormError message={refusal} dataId={errorId} />
        </div>
      </HilosModal>
    </section>
  )
}
