// framework/frontend/vue/src/admin/security/HilosSecurityStepUpPage.vue
<!-- HilosSecurityStepUpPage — the framework page of operations that ask for
confirmation (HilosPages.SECURITY_STEP_UP, HIL-1204), a child of two-factor:
one row per operation the step-up directory declares, with whether the
framework or the project declared it and a switch. The table, the row
view-model and the switch round-trip are the core headless's
(createHilosSecurityStepUpTable / createHilosSecurityStepUpActions); this view
owns only the markup, so a project mounts it by passing its
HilosTwoFactorContext. The switch is a tracked action: a spinner on its own
row while it flies, the other switches dimmed, and the switch redraws from the
table's live row. The page heading names the table. The screen is built from
text: the mockup still draws the list on the two-factor page (D-143). Bootstrap
classes only (styling-rules.md). -->
<script setup lang="ts">
import {
  createHilosSecurityStepUpActions,
  createHilosSecurityStepUpTable,
  HILOS_STEP_UP_ADMIN_COPY,
  HilosPages,
  type HilosStepUpOperationRow,
  type HilosTwoFactorContext,
} from '@hilos/core'
import { onMounted, onUnmounted, ref } from 'vue'

import HilosAdminPage from '../../HilosAdminPage.vue'
import HilosHideable from '../../HilosHideable.vue'
import HilosSwitch from '../../HilosSwitch.vue'
import HilosViewportTable from '../../HilosViewportTable.vue'
import { useTrackedAction } from '../../useTrackedAction.js'

const props = defineProps<{
  /** The project context: connection, scope stores, and the action lifecycle. */
  context: HilosTwoFactorContext
}>()

const operations = createHilosSecurityStepUpTable(props.context)
const { sendOperationSet } = createHilosSecurityStepUpActions(props.context)

onMounted(() => operations.start())
onUnmounted(() => operations.dispose())

const { busy: operationBusy, run: runOperation } = useTrackedAction()
const pendingOperationKey = ref<string | null>(null)

async function toggleOperation(
  row: HilosStepUpOperationRow,
  enabled: boolean,
): Promise<void> {
  pendingOperationKey.value = row.operationKey
  try {
    await runOperation(sendOperationSet(row.operationKey, enabled))
  } finally {
    pendingOperationKey.value = null
  }
}
</script>

<template>
  <HilosAdminPage :page="HilosPages.SECURITY_STEP_UP">
    <HilosViewportTable
      :controller="operations.controller"
      data-id="hilos-step-up-table"
    >
      <template #cell-operationKey="{ row }">
        <span
          class="fw-semibold"
          :data-id="`hilos-step-up-row-${row.operationKey}`"
          >{{ row.label }}</span
        >
      </template>
      <template #cell-owner="{ row }">
        <span class="badge text-bg-light border">
          {{
            row.owner === 'framework'
              ? HILOS_STEP_UP_ADMIN_COPY.framework
              : HILOS_STEP_UP_ADMIN_COPY.project
          }}
        </span>
      </template>
      <template #cell-enabled="{ row }">
        <HilosHideable :value="row.enabled">
          <template #default="{ value: enabled }">
            <HilosSwitch
              class="mb-0"
              :checked="enabled"
              :busy="pendingOperationKey === row.operationKey"
              :disabled="operationBusy"
              :aria-label="`Require confirmation for ${row.label}`"
              :data-id="`hilos-step-up-switch-${row.operationKey}`"
              @toggle="toggleOperation(row, $event)"
            />
          </template>
        </HilosHideable>
      </template>
    </HilosViewportTable>
  </HilosAdminPage>
</template>

// framework/frontend/angular/src/admin/security/HilosSecurityStepUpPage.ts
// HilosSecurityStepUpPage — the framework page of operations that ask for
// confirmation (HilosPages.SECURITY_STEP_UP, HIL-1204), a child of two-factor:
// one row per operation the step-up directory declares, with whether the
// framework or the project declared it and a switch. The table, the row
// view-model and the switch round-trip are the core headless's
// (createHilosSecurityStepUpTable / createHilosSecurityStepUpActions); this view
// owns only the markup, so a project mounts it by passing its
// HilosTwoFactorContext. The switch is a tracked action: a spinner on its own
// row while it flies, the other switches dimmed, and the switch redraws from the
// table's live row. The page heading names the table. The screen is built from
// text: the mockup still draws the list on the two-factor page (D-143).
// Bootstrap classes only (styling-rules.md).
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  signal,
} from '@angular/core'
import {
  HILOS_STEP_UP_ADMIN_COPY,
  HilosPages,
  createHilosSecurityStepUpActions,
  createHilosSecurityStepUpTable,
} from '@hilos/core'
import type {
  HilosStepUpOperationRow,
  HilosTwoFactorContext,
} from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'
import { HilosHideable } from '../../HilosHideable.js'
import { HilosSwitch } from '../../HilosSwitch.js'
import { HilosTableCell } from '../../HilosTableCell.js'
import { HilosViewportTable } from '../../HilosViewportTable.js'
import { createHilosTrackedAction } from '../../hilosTrackedAction.js'

/** The framework page of operations that ask for confirmation: a switch per operation. */
@Component({
  selector: 'hilos-security-step-up-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    HilosAdminPage,
    HilosHideable,
    HilosSwitch,
    HilosTableCell,
    HilosViewportTable,
  ],
  template: `
    <hilos-admin-page [page]="page">
      <hilos-viewport-table
        [controller]="operations().controller"
        [dataId]="'hilos-step-up-table'"
      >
        <ng-template hilosTableCell="operationKey" let-row>
          <span
            class="fw-semibold"
            [attr.data-id]="'hilos-step-up-row-' + row.operationKey"
            >{{ row.label }}</span
          >
        </ng-template>
        <ng-template hilosTableCell="owner" let-row>
          <span class="badge text-bg-light border">
            {{
              row.owner === 'framework'
                ? stepUpCopy.framework
                : stepUpCopy.project
            }}
          </span>
        </ng-template>
        <ng-template hilosTableCell="enabled" let-row>
          <hilos-hideable [value]="row.enabled">
            <ng-template let-enabled>
              <hilos-switch
                class="mb-0"
                [checked]="enabled"
                [busy]="pendingOperationKey() === row.operationKey"
                [disabled]="operationToggle.busy()"
                [aria-label]="'Require confirmation for ' + row.label"
                [dataId]="'hilos-step-up-switch-' + row.operationKey"
                (toggle)="toggleOperation(row, $event)"
              />
            </ng-template>
          </hilos-hideable>
        </ng-template>
      </hilos-viewport-table>
    </hilos-admin-page>
  `,
})
export class HilosSecurityStepUpPage {
  /** The project context: connection, scope stores, and the action lifecycle. */
  readonly context = input.required<HilosTwoFactorContext>()

  protected readonly page = HilosPages.SECURITY_STEP_UP
  protected readonly stepUpCopy = HILOS_STEP_UP_ADMIN_COPY

  protected readonly operations = computed(() =>
    createHilosSecurityStepUpTable(this.context()),
  )
  private readonly operationActions = computed(() =>
    createHilosSecurityStepUpActions(this.context()),
  )
  protected readonly operationToggle = createHilosTrackedAction()
  protected readonly pendingOperationKey = signal<string | null>(null)

  constructor() {
    // Bind the table to the connection once the context input is bound; unbind
    // on destroy / swap.
    effect((onCleanup) => {
      const operations = this.operations()
      operations.start()
      onCleanup(() => operations.dispose())
    })
  }

  protected async toggleOperation(
    row: HilosStepUpOperationRow,
    enabled: boolean,
  ): Promise<void> {
    this.pendingOperationKey.set(row.operationKey)
    try {
      await this.operationToggle.run(
        this.operationActions().sendOperationSet(row.operationKey, enabled),
      )
    } finally {
      this.pendingOperationKey.set(null)
    }
  }
}
