// framework/frontend/angular/src/HilosDropdown.ts
// HilosDropdown — a tier-1 single-select dropdown on Bootstrap's `.dropdown`
// markup with its own open/close logic (the SDK ships Bootstrap CSS, not its JS,
// so toggling and outside-click are owned here, like HilosModal). It is
// projection-first: `#toggle` (context: label / selected / open) replaces the
// button face and `#option` (context: option / selected / select) replaces each
// item, so a project customizes the look by filling those templates, never by
// re-implementing the behavior. The selection is the two-way `value` binding.
// Outside-click and Escape close it, arrow keys rove the options on display, and
// the listbox/option ARIA roles ship by default (a11y is v1, styling-rules.md). A
// substituted option (projected #option) must itself carry role="option" and
// aria-selected — the <li> is presentational, and the SDK does not write the
// option role for a project.
// Exported as part of the public SDK surface (index.ts) and kept intentionally:
// no in-repo consumer mounts one today, but it stays a tier-1 building block for
// any catalog/option select — live API, not dead code.
// The primitive ships in all three view layers at parity; what differs is only
// the form the look is substituted through — projected templates here, slots in
// Vue, render props in React (multiframework-core.md).
// Bootstrap classes only — no CSS of its own.
import { NgTemplateOutlet } from '@angular/common'
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  TemplateRef,
  computed,
  contentChild,
  inject,
  input,
  model,
  signal,
  viewChild,
} from '@angular/core'
import { isDisplayed } from '@hilos/core'

import type { HilosDropdownOption } from './hilosDropdownOption.js'

// Distinct ids so two dropdowns on one page never share an `aria-controls`
// target.
let dropdownMenuSeq = 0

/** The context a HilosDropdown `#toggle` template receives. */
export interface DropdownToggleContext<V extends string | number> {
  /** The label the default face would show (the template's implicit `let-label`). */
  $implicit: string
  /** The selected option, or null when nothing is chosen. */
  selected: HilosDropdownOption<V> | null
  /** Whether the menu is open. */
  open: boolean
}

/** The context a HilosDropdown `#option` template receives. */
export interface DropdownOptionContext<V extends string | number> {
  /** The option this row draws (the template's implicit `let-option`). */
  $implicit: HilosDropdownOption<V>
  /** Whether this option is the selected one. */
  selected: boolean
  /** Choose this option; a disabled one stays unchosen. */
  select: () => void
}

/** The single-select dropdown: a toggle button over a listbox of options. */
@Component({
  selector: 'hilos-dropdown',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  template: `
    <div class="dropdown" data-id="hilos-dropdown">
      <button
        #toggleButton
        type="button"
        class="btn btn-outline-secondary dropdown-toggle d-flex align-items-center justify-content-between w-100"
        [disabled]="disabled()"
        [attr.aria-expanded]="open()"
        [attr.aria-controls]="menuId"
        aria-haspopup="listbox"
        data-id="hilos-dropdown-toggle"
        (click)="onToggleClick()"
        (keydown.arrowdown)="onToggleArrow($event, 'first')"
        (keydown.arrowup)="onToggleArrow($event, 'last')"
        (keydown.escape)="onEscape($event)"
      >
        @if (toggle(); as face) {
          <ng-container
            [ngTemplateOutlet]="face"
            [ngTemplateOutletContext]="{
              $implicit: label(),
              selected: selected(),
              open: open(),
            }"
          />
        } @else {
          <span class="text-truncate">{{ label() }}</span>
        }
      </button>
      <ul
        #menu
        [id]="menuId"
        class="dropdown-menu w-100"
        [class.show]="open()"
        role="listbox"
        [attr.aria-label]="menuAriaLabel()"
        data-id="hilos-dropdown-menu"
        (keydown.arrowdown)="onMenuArrow($event, 1)"
        (keydown.arrowup)="onMenuArrow($event, -1)"
        (keydown.home)="onMenuEdge($event, 'first')"
        (keydown.end)="onMenuEdge($event, 'last')"
        (keydown.escape)="onEscape($event)"
      >
        @for (item of options(); track item.value) {
          <li role="presentation">
            @if (option(); as row) {
              <ng-container
                [ngTemplateOutlet]="row"
                [ngTemplateOutletContext]="optionContext(item)"
              />
            } @else {
              <button
                type="button"
                class="dropdown-item d-flex align-items-center justify-content-between gap-2"
                [class.active]="item.value === value()"
                [disabled]="item.disabled"
                role="option"
                [attr.aria-selected]="item.value === value()"
                [attr.data-id]="'hilos-dropdown-option-' + item.value"
                (click)="select(item)"
              >
                <span class="text-truncate">{{ item.label }}</span>
                @if (item.value === value()) {
                  <i class="bi bi-check2 flex-shrink-0" aria-hidden="true"></i>
                }
              </button>
            }
          </li>
        }
        @if (options().length === 0) {
          <li role="presentation">
            <span
              class="dropdown-item disabled text-body-secondary"
              data-id="hilos-dropdown-empty"
              role="option"
              aria-disabled="true"
              >{{ emptyText() }}</span
            >
          </li>
        }
      </ul>
    </div>
  `,
})
export class HilosDropdown<V extends string | number> {
  /** The selectable options, in display order. */
  readonly options = input.required<HilosDropdownOption<V>[]>()
  /** The selected option's value; null when nothing is chosen. */
  readonly value = model<V | null>(null)
  /** Toggle label shown when no option is selected. */
  readonly placeholder = input('Select…')
  /** Disable the whole control. */
  readonly disabled = input(false)
  /** Accessible name for the options menu. */
  readonly menuAriaLabel = input('Options')
  /** Message shown inside the menu when there are no options. */
  readonly emptyText = input('No options')

  protected readonly toggle =
    contentChild<TemplateRef<DropdownToggleContext<V>>>('toggle')
  protected readonly option =
    contentChild<TemplateRef<DropdownOptionContext<V>>>('option')

  protected readonly open = signal(false)
  protected readonly menuId = `hilos-dropdown-menu-${dropdownMenuSeq++}`

  protected readonly selected = computed(
    () => this.options().find((each) => each.value === this.value()) ?? null,
  )
  protected readonly label = computed(
    () => this.selected()?.label ?? this.placeholder(),
  )

  private readonly toggleButton =
    viewChild<ElementRef<HTMLButtonElement>>('toggleButton')
  private readonly menu = viewChild<ElementRef<HTMLUListElement>>('menu')
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef)

  // Close on an outside click while open (the SDK ships Bootstrap CSS, not its
  // JS, so the dropdown owns its own dismissal like HilosModal).
  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (
      this.open() &&
      !this.host.nativeElement.contains(event.target as Node)
    ) {
      this.open.set(false)
    }
  }

  /**
   * The context one projected option row is drawn with.
   *
   * It is built here rather than inline in the template because `select` is a
   * closure over the option, and a template expression cannot write one.
   *
   * @param item The option the row draws.
   * @returns The context the `#option` template receives.
   */
  protected optionContext(
    item: HilosDropdownOption<V>,
  ): DropdownOptionContext<V> {
    return {
      $implicit: item,
      selected: item.value === this.value(),
      select: () => this.select(item),
    }
  }

  protected onToggleClick(): void {
    if (this.disabled()) {
      return
    }
    this.open.set(!this.open())
  }

  protected onToggleArrow(event: Event, which: 'first' | 'last'): void {
    event.preventDefault()
    if (this.disabled()) {
      return
    }
    this.open.set(true)
    // The menu is already in the DOM; focus after the open paints, the way the
    // bell does — Angular has no nextTick.
    requestAnimationFrame(() => this.focusOption(which))
  }

  protected onEscape(event: Event): void {
    event.preventDefault()
    this.close(true)
  }

  protected onMenuArrow(event: Event, delta: 1 | -1): void {
    event.preventDefault()
    const buttons = this.optionButtons()
    if (buttons.length === 0) {
      return
    }
    const index = buttons.indexOf(document.activeElement as HTMLButtonElement)
    const next =
      index === -1 ? 0 : (index + delta + buttons.length) % buttons.length
    buttons[next]?.focus()
  }

  protected onMenuEdge(event: Event, which: 'first' | 'last'): void {
    event.preventDefault()
    this.focusOption(which)
  }

  protected select(chosen: HilosDropdownOption<V>): void {
    if (chosen.disabled) {
      return
    }
    this.value.set(chosen.value)
    this.close(true)
  }

  private close(returnFocus = false): void {
    if (!this.open()) {
      return
    }
    this.open.set(false)
    if (returnFocus) {
      this.toggleButton()?.nativeElement.focus()
    }
  }

  // Only the options on display take focus: an option a width hides with a class
  // of its own would stop the walk on something nobody sees.
  private optionButtons(): HTMLButtonElement[] {
    const menu = this.menu()
    return menu
      ? Array.from(
          menu.nativeElement.querySelectorAll<HTMLButtonElement>(
            '.dropdown-item:not(:disabled)',
          ),
        ).filter(isDisplayed)
      : []
  }

  private focusOption(which: 'first' | 'last'): void {
    const buttons = this.optionButtons()
    const target = which === 'first' ? buttons[0] : buttons[buttons.length - 1]
    target?.focus()
  }
}

// framework/frontend/react/src/HilosDropdown.tsx
// HilosDropdown — a tier-1 single-select dropdown on Bootstrap's `.dropdown`
// markup with its own open/close logic (the SDK ships Bootstrap CSS, not its JS,
// so toggling and outside-click are owned here, like HilosModal). It is
// render-prop-first: `toggle` (context: label / selected / open) replaces the
// button face and `option` (context: option / selected / select) replaces each
// item, so a project customizes the look by filling those, never by
// re-implementing the behavior. The selection is a controlled pair — `value` in,
// `onChange` out. Outside-click and Escape close it, arrow keys rove the
// options on display, and the listbox/option ARIA roles ship by default (a11y is
// v1, styling-rules.md). A substituted option (render prop option) must itself
// carry role="option" and aria-selected — the <li> is presentational, and the
// SDK does not write the option role for a project. Exported as part of the
// public SDK surface (index.ts) and kept intentionally: no in-repo consumer
// mounts one today, but it stays a tier-1 building block for any catalog/option
// select — live API, not dead code.
// The primitive ships in all three view layers at parity; what differs is only
// the form the look is substituted through — render props here, slots in Vue,
// projected templates in Angular (multiframework-core.md).
// Bootstrap classes only — no CSS of its own.
import { useEffect, useId, useRef, useState, type ReactNode } from 'react'
import { isDisplayed } from '@hilos/core'

import type { HilosDropdownOption } from './hilosDropdown.js'

/** Props for {@link HilosDropdown}. */
export interface HilosDropdownProps<V extends string | number> {
  /** The selected option's value; null when nothing is chosen. */
  value: V | null
  /** The selectable options, in display order. */
  options: HilosDropdownOption<V>[]
  /** Called with the chosen option's value; only a selection fires it. */
  onChange: (value: V) => void
  /** Toggle label shown when no option is selected. */
  placeholder?: string
  /** Disable the whole control. */
  disabled?: boolean
  /** Accessible name for the options menu. */
  menuAriaLabel?: string
  /** Message shown inside the menu when there are no options. */
  emptyText?: string
  /** Replace the toggle's face; the context mirrors Vue's `#toggle` slot scope. */
  toggle?: (context: {
    label: string
    selected: HilosDropdownOption<V> | null
    open: boolean
  }) => ReactNode
  /** Replace one option's row; the context mirrors Vue's `#option` slot scope. */
  option?: (context: {
    option: HilosDropdownOption<V>
    selected: boolean
    select: () => void
  }) => ReactNode
}

/**
 * The single-select dropdown: a toggle button over a listbox of options.
 *
 * @param props The controlled selection, the options, and the label / empty /
 *   substitution config.
 */
export function HilosDropdown<V extends string | number>({
  value,
  options,
  onChange,
  placeholder = 'Select…',
  disabled = false,
  menuAriaLabel = 'Options',
  emptyText = 'No options',
  toggle,
  option,
}: HilosDropdownProps<V>) {
  const [open, setOpen] = useState(false)
  const menuId = useId()
  const root = useRef<HTMLDivElement>(null)
  const menu = useRef<HTMLUListElement>(null)
  const toggleButton = useRef<HTMLButtonElement>(null)

  const selected = options.find((each) => each.value === value) ?? null
  const label = selected?.label ?? placeholder

  // Close on an outside click while open (the SDK ships Bootstrap CSS, not its
  // JS, so the dropdown owns its own dismissal like HilosModal).
  useEffect(() => {
    if (!open) {
      return
    }
    const onDocumentClick = (event: MouseEvent): void => {
      if (root.current && !root.current.contains(event.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener('click', onDocumentClick)

    return () => document.removeEventListener('click', onDocumentClick)
  }, [open])

  // Only the options on display take focus: an option a width hides with a class
  // of its own would stop the walk on something nobody sees.
  function optionButtons(): HTMLButtonElement[] {
    return menu.current
      ? Array.from(
          menu.current.querySelectorAll<HTMLButtonElement>(
            '.dropdown-item:not(:disabled)',
          ),
        ).filter(isDisplayed)
      : []
  }

  function focusOption(which: 'first' | 'last'): void {
    const buttons = optionButtons()
    const target = which === 'first' ? buttons[0] : buttons[buttons.length - 1]
    target?.focus()
  }

  function openMenu(focus: 'first' | 'last' | 'none' = 'none'): void {
    if (disabled) {
      return
    }
    setOpen(true)
    if (focus !== 'none') {
      // The menu is already in the DOM; focus after the open paints, the way the
      // bell does — React has no nextTick.
      requestAnimationFrame(() => focusOption(focus))
    }
  }

  function close(returnFocus = false): void {
    if (!open) {
      return
    }
    setOpen(false)
    if (returnFocus) {
      toggleButton.current?.focus()
    }
  }

  function toggleMenu(): void {
    if (disabled) {
      return
    }
    if (open) {
      close()
    } else {
      openMenu()
    }
  }

  function select(chosen: HilosDropdownOption<V>): void {
    if (chosen.disabled) {
      return
    }
    onChange(chosen.value)
    close(true)
  }

  function moveFocus(delta: 1 | -1): void {
    const buttons = optionButtons()
    if (buttons.length === 0) {
      return
    }
    const index = buttons.indexOf(document.activeElement as HTMLButtonElement)
    const next =
      index === -1 ? 0 : (index + delta + buttons.length) % buttons.length
    buttons[next]?.focus()
  }

  function onToggleKeydown(event: React.KeyboardEvent): void {
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      openMenu('first')
    } else if (event.key === 'ArrowUp') {
      event.preventDefault()
      openMenu('last')
    } else if (event.key === 'Escape') {
      event.preventDefault()
      close(true)
    }
  }

  function onMenuKeydown(event: React.KeyboardEvent): void {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault()
        moveFocus(1)
        break
      case 'ArrowUp':
        event.preventDefault()
        moveFocus(-1)
        break
      case 'Home':
        event.preventDefault()
        focusOption('first')
        break
      case 'End':
        event.preventDefault()
        focusOption('last')
        break
      case 'Escape':
        event.preventDefault()
        close(true)
        break
    }
  }

  return (
    <div ref={root} className="dropdown" data-id="hilos-dropdown">
      <button
        ref={toggleButton}
        type="button"
        className="btn btn-outline-secondary dropdown-toggle d-flex align-items-center justify-content-between w-100"
        disabled={disabled}
        aria-expanded={open}
        aria-controls={menuId}
        aria-haspopup="listbox"
        data-id="hilos-dropdown-toggle"
        onClick={toggleMenu}
        onKeyDown={onToggleKeydown}
      >
        {toggle ? (
          toggle({ label, selected, open })
        ) : (
          <span className="text-truncate">{label}</span>
        )}
      </button>
      <ul
        id={menuId}
        ref={menu}
        className={`dropdown-menu w-100${open ? ' show' : ''}`}
        role="listbox"
        aria-label={menuAriaLabel}
        data-id="hilos-dropdown-menu"
        onKeyDown={onMenuKeydown}
      >
        {options.map((item) => (
          <li key={String(item.value)} role="presentation">
            {option ? (
              option({
                option: item,
                selected: item.value === value,
                select: () => select(item),
              })
            ) : (
              <button
                type="button"
                className={`dropdown-item d-flex align-items-center justify-content-between gap-2${
                  item.value === value ? ' active' : ''
                }`}
                disabled={item.disabled}
                role="option"
                aria-selected={item.value === value}
                data-id={`hilos-dropdown-option-${item.value}`}
                onClick={() => select(item)}
              >
                <span className="text-truncate">{item.label}</span>
                {item.value === value && (
                  <i
                    className="bi bi-check2 flex-shrink-0"
                    aria-hidden="true"
                  />
                )}
              </button>
            )}
          </li>
        ))}
        {options.length === 0 && (
          <li role="presentation">
            <span
              className="dropdown-item disabled text-body-secondary"
              data-id="hilos-dropdown-empty"
              role="option"
              aria-disabled="true"
            >
              {emptyText}
            </span>
          </li>
        )}
      </ul>
    </div>
  )
}
