// framework/frontend/angular/src/LoadingButton.ts
// LoadingButton — enhances a native button to disable itself and show a spinner
// while an async action is in flight (the authoritative-backend pattern: act ->
// block -> backend reply clears it). The delayed-spinner timer is the headless
// core state machine (createLoadingButtonState); this view only drives `loading`
// into it and renders `showSpinner`. The selector is an attribute on a native
// button, so the host IS the button: the Bootstrap variant class, the native
// (click), the form `type`, and aria fall through with no wrapper element, and a
// disabled host suppresses the click natively (no swallow handler needed). The
// label stays in the layout under the spinner so the button keeps its width.
// In the page's area of a takeover that only looks the button stands plainly
// disabled, described by the impersonation strip (HIL-1170); it changes neither
// its color, nor its size, nor its words. A button marked opensWindow stays
// live. Its own `aria-describedby` is an input, so the strip's id is joined to
// it rather than written over it.
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  effect,
  inject,
  input,
} from '@angular/core'
import { DEFAULT_SPINNER_DELAY_MS, createLoadingButtonState } from '@hilos/core'

import { injectLookOnly, joinDescribedBy } from './hilosLookOnly.js'
import { hilosSignal } from './hilosSignal.js'

/**
 * A button that blocks and shows a delayed spinner while an action is in flight.
 * Use it as an attribute on a native button:
 * `<button hilosLoadingButton [loading]="busy()" (click)="save()">Save</button>`.
 */
@Component({
  selector: 'button[hilosLoadingButton]',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: 'btn position-relative',
    '[attr.type]': 'type()',
    '[disabled]': 'isDisabled()',
    '[attr.aria-busy]': 'loading() || null',
    '[attr.aria-describedby]': 'describedBy()',
  },
  template: `
    <span [class.invisible]="showSpinner()"><ng-content /></span>
    @if (showSpinner()) {
      <span
        class="position-absolute top-50 start-50 translate-middle"
        data-id="loading-button-spinner"
      >
        <span class="spinner-border spinner-border-sm" role="status">
          <span class="visually-hidden">Loading…</span>
        </span>
      </span>
    }
  `,
})
export class LoadingButton {
  /** Whether the action is in flight: disables the button and arms the spinner. */
  readonly loading = input(false)
  /** Disable independently of loading (e.g. an invalid form). */
  readonly disabled = input(false)
  /** Milliseconds to wait before showing the spinner, so a fast reply never flashes it. */
  readonly loadingDelay = input(DEFAULT_SPINNER_DELAY_MS)
  /** Native button type; `submit` inside a form, `button` otherwise. */
  readonly type = input<'button' | 'submit' | 'reset'>('button')
  /**
   * The press only opens a window, at once or after the server's word; a
   * takeover that only looks leaves it live — what the window would send stands
   * on a control of the mode.
   */
  readonly opensWindow = input(false)
  /** The ids describing the button (a row's reason on the person's card). */
  readonly ariaDescribedby = input<string>(undefined, {
    alias: 'aria-describedby',
  })

  // The delay is read through a getter so the controller is built once at field
  // init (the input is not yet bound) yet always arms with the current value.
  private readonly spinner = createLoadingButtonState(() => this.loadingDelay())
  protected readonly showSpinner = hilosSignal(this.spinner.showSpinner)
  private readonly lookOnly = injectLookOnly()
  private readonly lockedToLook = computed(
    () => this.lookOnly.locked() && !this.opensWindow(),
  )
  protected readonly isDisabled = computed(
    () => this.disabled() || this.loading() || this.lockedToLook(),
  )
  // Locked to look, the button is also described by the strip that says why,
  // beside whatever describes it already.
  protected readonly describedBy = computed(() =>
    joinDescribedBy(
      this.ariaDescribedby(),
      this.lockedToLook() ? this.lookOnly.describedBy() : undefined,
    ),
  )

  constructor() {
    effect(() => {
      this.spinner.setLoading(this.loading())
    })
    inject(DestroyRef).onDestroy(() => {
      this.spinner.dispose()
    })
  }
}

// framework/frontend/react/src/LoadingButton.tsx
// LoadingButton — a button that disables itself and shows a spinner while an
// async action is in flight (the authoritative-backend pattern: act -> block ->
// backend reply clears it). The delayed-spinner timer is the headless core state
// machine (createLoadingButtonState); this view only drives `loading` into it
// and renders `showSpinner`. The spinner appears only after a short delay so a
// fast reply never flashes it, and the label stays in the layout under the
// spinner so the button keeps its width. Pass the Bootstrap variant as a
// className (`className="btn-primary"`); className, aria, and data attributes
// fall through to the button. In the page's area of a takeover that only looks
// the button stands plainly disabled, described by the impersonation strip
// (HIL-1170); it changes neither its color, nor its size, nor its words. A
// button marked opensWindow stays live.
import { useEffect, useMemo } from 'react'
import type { ButtonHTMLAttributes } from 'react'
import { DEFAULT_SPINNER_DELAY_MS, createLoadingButtonState } from '@hilos/core'

import { joinDescribedBy, useLookOnly } from './hilosLookOnly.js'
import { useSignal } from './useSignal.js'

/** Props for {@link LoadingButton}; unknown attributes fall through to the button. */
export interface LoadingButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Whether the action is in flight: disables the button and arms the spinner. */
  loading?: boolean
  /** Milliseconds to wait before showing the spinner, so a fast reply never flashes it. */
  loadingDelay?: number
  /**
   * The press only opens a window, at once or after the server's word; a
   * takeover that only looks leaves it live — what the window would send stands
   * on a control of the mode.
   */
  opensWindow?: boolean
}

/**
 * A button that blocks and shows a delayed spinner while an action is in flight.
 *
 * @param props The button props; `loading`, `loadingDelay`, `opensWindow`, and
 *   the standard button attributes (`disabled`, `type`, `className`, `onClick`, …).
 */
export function LoadingButton({
  loading = false,
  disabled = false,
  loadingDelay = DEFAULT_SPINNER_DELAY_MS,
  opensWindow = false,
  type = 'button',
  className,
  children,
  onClick,
  'aria-describedby': ariaDescribedby,
  ...rest
}: LoadingButtonProps) {
  // The controller is recreated only if the delay changes; the dispose effect
  // releases the previous one. Driving `loading` is a separate effect.
  const spinner = useMemo(
    () => createLoadingButtonState(loadingDelay),
    [loadingDelay],
  )
  const showSpinner = useSignal(spinner.showSpinner)

  useEffect(() => {
    spinner.setLoading(loading)
  }, [spinner, loading])
  useEffect(() => () => spinner.dispose(), [spinner])

  // Locked to look, the button is also described by the strip that says why,
  // beside whatever describes it already (a row's reason on the person's card).
  const lookOnly = useLookOnly()
  const lockedToLook = lookOnly.locked && !opensWindow
  const isDisabled = disabled || loading || lockedToLook

  return (
    <button
      {...rest}
      type={type}
      disabled={isDisabled}
      aria-busy={loading || undefined}
      aria-describedby={joinDescribedBy(
        ariaDescribedby,
        lockedToLook ? lookOnly.describedBy : undefined,
      )}
      className={`btn position-relative${className ? ` ${className}` : ''}`}
      onClick={(event) => {
        if (!isDisabled) {
          onClick?.(event)
        }
      }}
    >
      <span className={showSpinner ? 'invisible' : undefined}>{children}</span>
      {showSpinner ? (
        <span
          className="position-absolute top-50 start-50 translate-middle"
          data-id="loading-button-spinner"
        >
          <span className="spinner-border spinner-border-sm" role="status">
            <span className="visually-hidden">Loading…</span>
          </span>
        </span>
      ) : null}
    </button>
  )
}
