// framework/frontend/react/src/admin/changeLog/HilosChangeLogTablePage.tsx
// HilosChangeLogTablePage — the Change Log Table admin page (HilosPages.CHANGE_LOG_TABLE). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Change Log Table admin page: the framework default shell for its key. */
export function HilosChangeLogTablePage() {
  return <HilosAdminPage page={HilosPages.CHANGE_LOG_TABLE} />
}

// framework/frontend/vue/src/admin/changeLog/HilosChangeLogTablePage.vue
<!-- HilosChangeLogTablePage — the Tracked table admin page (HilosPages.CHANGE_LOG_TABLE). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.CHANGE_LOG_TABLE" />
</template>
