// framework/frontend/angular/src/admin/logs/HilosLogsViewPage.ts
// HilosLogsViewPage — the framework Hilos log viewer (HilosPages.LOGS_VIEW):
// the lines of ONE file on ONE node, for an administrator who came to work out what
// already happened. The node, the source (the live journal or one archived batch)
// and the stream together ARE the address of this screen, so choosing another file
// rewrites the address in place rather than navigating — it is another file of the
// same page, and a navigation would re-subscribe it and drop the catalog. Nothing
// is filtered here: the level and the substring are fields of the read request, and
// the server answers with what matched. The Follow switch runs the live tail, and
// there is no Refresh button on purpose: freshness arrives as a push. Scrolling up
// releases only the STICKING — the tail keeps running, what arrives while the
// reader is up waits beside the pane, and the return control carries its count.
// That control stands in the strip above the pane, in a room taken always (HIL-1024),
// so neither its arrival nor its count moves the pane (styling-rules.md, "The room a
// live message takes"); so nothing ever moves under the reader's eyes, and nothing is
// lost without saying so. The note that a typed search is not applied yet stands in
// the place of the line count, in a cell held at its width always (HIL-1152), so it
// does not move the pane either. The catalog, the address, the read, the buffer and
// the row view-model are the core headless's (hilosLogViewer), including the
// threshold that decides "at the tail" and the wording of the notes — this view
// owns only the markup and the scrolling, so a project mounts it by passing its
// HilosLogViewerContext and the Vue and React ports measure the same edge.
// Bootstrap classes only, save the one pre-wrap declaration the pane calls for
// because Bootstrap has no utility for it (styling-rules.md, same exception as
// HilosActionError).
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  afterRenderEffect,
  computed,
  effect,
  inject,
  input,
  signal,
  viewChild,
} from '@angular/core'
import {
  HILOS_LOG_LEVEL_OPTIONS,
  HilosPages,
  LOG_SOURCE_LIVE,
  LOG_VIEWER_PENDING_WIDEST_LABEL,
  createHilosLogViewer,
  createSignal,
  hasLogViewerNodes,
  isLogViewerPinned,
  logLevelVariant,
  logViewerNodeOf,
  logViewerPaneState,
  logViewerPendingLabel,
  logViewerStreamsOf,
  readLogViewerAddress,
  subscribeSignal,
} from '@hilos/core'
import type {
  HilosLogViewerAddress,
  HilosLogViewerCatalog,
  HilosLogViewerContext,
  HilosLogViewerEntry,
  HilosLogViewerNotice,
  HilosLogViewerRow,
  HilosLogViewerSelection,
  PageRouteMatch,
  ReadonlySignal,
  Unsubscribe,
} from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'
import { HILOS_ROUTER } from '../../hilosRouterToken.js'

/** The icon one note is drawn with; its wording belongs to the headless. */
const NOTICE_ICONS: Record<HilosLogViewerNotice, string> = {
  rotated: 'bi-arrow-repeat',
  skipped: 'bi-fast-forward',
  dropped: 'bi-scissors',
  stopped: 'bi-stop-circle',
  anchorMissing: 'bi-geo-alt',
}

/** The framework log viewer: one file of one node, with its live tail. */
@Component({
  selector: 'hilos-logs-view-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosAdminPage],
  template: `
    <hilos-admin-page [page]="page">
      <div class="border rounded-3 p-3 mb-3">
        <div class="row g-2 align-items-end">
          @if (clustered()) {
            <div class="col-6 col-md-2">
              <label
                class="form-label small fw-semibold mb-1"
                for="hilos-log-node"
              >
                Node
              </label>
              <select
                id="hilos-log-node"
                class="form-select form-select-sm"
                [value]="selection().nodeId ?? ''"
                data-id="hilos-log-node"
                (change)="onNode($event)"
              >
                <option value="" disabled>Choose a node</option>
                @for (entry of catalog()?.nodes ?? []; track entry.nodeId) {
                  <option [value]="entry.nodeId">{{ entry.nodeId }}</option>
                }
              </select>
            </div>
          }
          <div class="col-6 col-md-3">
            <label
              class="form-label small fw-semibold mb-1"
              for="hilos-log-source"
            >
              Source
            </label>
            <select
              id="hilos-log-source"
              class="form-select form-select-sm"
              [value]="sourceValue(selection().source)"
              data-id="hilos-log-source"
              (change)="onSource($event)"
            >
              <option [value]="live">Live journal</option>
              @for (batch of batches(); track batch) {
                <option [value]="batch">Batch — {{ batchLabel(batch) }}</option>
              }
            </select>
          </div>
          <div class="col-12 col-md-3">
            <label
              class="form-label small fw-semibold mb-1"
              for="hilos-log-stream"
            >
              Stream
            </label>
            <select
              id="hilos-log-stream"
              class="form-select form-select-sm"
              [value]="selection().stream ?? ''"
              data-id="hilos-log-stream"
              (change)="onStream($event)"
            >
              <option value="">Choose a stream</option>
              @for (stream of streams(); track stream.key) {
                <option [value]="stream.key">{{ stream.key }}</option>
              }
            </select>
          </div>
          <div class="col-6 col-md-2">
            <label
              class="form-label small fw-semibold mb-1"
              for="hilos-log-level"
            >
              Level
            </label>
            <select
              id="hilos-log-level"
              class="form-select form-select-sm"
              [value]="level()"
              data-id="hilos-log-level"
              (change)="onLevel($event)"
            >
              @for (option of levelOptions; track option.value) {
                <option [value]="option.value">{{ option.label }}</option>
              }
            </select>
          </div>
          <div class="col-6 col-md-2">
            <span class="form-label small fw-semibold mb-1 d-block"
              >Follow</span
            >
            <div class="form-check form-switch mb-1">
              <input
                id="hilos-log-follow"
                class="form-check-input"
                type="checkbox"
                [checked]="followRequested()"
                [disabled]="!canFollow()"
                data-id="hilos-log-follow"
                (change)="onFollow($event)"
              />
              <label class="form-check-label small" for="hilos-log-follow">
                tail
              </label>
            </div>
            @if (!canFollow()) {
              <span
                class="small text-body-secondary"
                data-id="hilos-log-follow-off"
              >
                An archived batch has no tail.
              </span>
            }
          </div>
          <div class="col-12">
            <label class="visually-hidden" for="hilos-log-substring">
              Search inside the lines
            </label>
            <div class="input-group input-group-sm">
              <input
                id="hilos-log-substring"
                type="search"
                class="form-control"
                placeholder="Search inside the lines"
                [value]="substringDraft()"
                data-id="hilos-log-substring"
                (input)="onSubstringInput($event)"
                (keydown.enter)="onSubstringApply()"
              />
              <button
                type="button"
                class="btn"
                [class.btn-primary]="substringDirty()"
                [class.btn-outline-secondary]="!substringDirty()"
                data-id="hilos-log-search"
                (click)="onSubstringApply()"
              >
                <i class="bi bi-search me-1" aria-hidden="true"></i>Search
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex flex-wrap align-items-center gap-2 mb-2">
        <button
          type="button"
          class="btn btn-sm btn-outline-secondary"
          [disabled]="!hasMore() || busy()"
          data-id="hilos-log-earlier"
          (click)="viewer().readOlder()"
        >
          <i class="bi bi-arrow-up me-1" aria-hidden="true"></i>Earlier
        </button>
        <!-- The line count and the note that the typed search is not applied
        yet share one cell (HIL-1152); the note stands in the count's place
        while the two texts differ, and an invisible twin of the note holds the
        cell at its width always, so neither its coming nor its going moves the
        pane (styling-rules.md, "The room a live message takes"); the status
        region stands there always so a screen reader hears the note arrive
        (accessibility.md, "Live regions"), and the count stays outside it
        because it changes with every line of the tail. -->
        <span class="hilos-stack" data-id="hilos-log-count-room">
          <span class="small invisible" aria-hidden="true">
            <i class="bi bi-exclamation-circle me-1"></i>Not applied yet — press
            Search
          </span>
          <span role="status" aria-live="polite">
            @if (substringDirty()) {
              <span
                class="small text-warning-emphasis"
                data-id="hilos-log-search-pending"
              >
                <i class="bi bi-exclamation-circle me-1" aria-hidden="true"></i
                >Not applied yet — press Search
              </span>
            }
          </span>
          @if (!substringDirty()) {
            <span class="small text-body-secondary" data-id="hilos-log-count">
              {{ entryCount() }} entries shown
            </span>
          }
        </span>
        @if (following()) {
          <span
            class="ms-auto badge text-bg-success-subtle text-success-emphasis border border-success-subtle"
            data-id="hilos-log-tail-badge"
          >
            <i class="bi bi-broadcast me-1" aria-hidden="true"></i>Tail is
            running
          </span>
        }
        <span
          class="hilos-stack"
          [class.ms-auto]="!following()"
          data-id="hilos-log-back-to-tail-room"
        >
          <!-- Holds the room at the widest the control ever gets: a span rather
          than a button, since it keeps a place and must never take the focus. -->
          <span class="btn btn-sm invisible" aria-hidden="true">
            <i class="bi bi-arrow-down me-1"></i>Back to the tail
            <span class="badge text-bg-light ms-1">{{
              widestPendingLabel
            }}</span>
          </span>
          @if (!pinned()) {
            <button
              type="button"
              class="btn btn-sm btn-primary"
              data-id="hilos-log-back-to-tail"
              (click)="viewer().returnToTail()"
            >
              <i class="bi bi-arrow-down me-1" aria-hidden="true"></i>Back to
              the tail
              @if (pendingLines() > 0) {
                <span
                  class="badge text-bg-light ms-1"
                  data-id="hilos-log-back-to-tail-count"
                  >{{ pendingLabel() }}</span
                ><span class="visually-hidden"> new lines</span>
              }
            </button>
          }
        </span>
      </div>

      <div
        #pane
        class="border rounded-3 bg-body-tertiary py-2 overflow-auto"
        style="max-height: 26rem; white-space: pre-wrap"
        data-id="hilos-log-pane"
        (scroll)="onScroll()"
      >
        @if (refusal(); as text) {
          <p class="px-3 mb-0 small text-danger" data-id="hilos-log-refusal">
            {{ text }}
          </p>
        } @else if (paneState() === 'unknown') {
          <p
            class="px-3 mb-0 small text-body-secondary"
            data-id="hilos-log-empty-unknown"
          >
            The cluster picture has not arrived yet, so there is nothing to
            choose between — not nothing to read.
          </p>
        } @else if (paneState() === 'unreadable') {
          <p
            class="px-3 mb-0 small text-body-secondary"
            data-id="hilos-log-empty-unreadable"
          >
            @if (clustered()) {
              No node could read its log store.
            } @else {
              The log store could not be read.
            }
          </p>
        } @else if (paneState() === 'empty') {
          <p
            class="px-3 mb-0 small text-body-secondary"
            data-id="hilos-log-empty-catalog"
          >
            No streams have been reported yet.
          </p>
        } @else if (paneState() === 'unchosen') {
          <p
            class="px-3 mb-0 small text-body-secondary"
            data-id="hilos-log-empty-unchosen"
          >
            Choose a stream to read.
          </p>
        } @else if (paneState() === 'missing') {
          <p
            class="px-3 mb-0 small text-body-secondary"
            data-id="hilos-log-empty-missing"
          >
            This file cannot be read. The rotation may have carried it off, or
            nothing has written to it yet.
          </p>
        } @else if (paneState() === 'nomatch') {
          <p
            class="px-3 mb-0 small text-body-secondary"
            data-id="hilos-log-empty-nomatch"
          >
            Nothing in this file matched.
          </p>
        } @else if (paneState() === 'silent') {
          <p
            class="px-3 mb-0 small text-body-secondary"
            data-id="hilos-log-empty-silent"
          >
            This file is empty.
          </p>
        } @else {
          @for (row of rows(); track row.key) {
            @if (row.kind === 'notice') {
              <div
                class="d-flex align-items-center justify-content-center gap-2 px-3 py-1 small text-body-secondary"
                data-id="hilos-log-notice"
              >
                <i
                  [class]="'bi ' + noticeIcons[row.notice]"
                  aria-hidden="true"
                ></i>
                <span>{{ row.text }}</span>
              </div>
            } @else {
              <!-- The entry a link opened the viewer on is framed so the eye lands on it;
              it comes first on its page, so nothing has to scroll to it. -->
              <div
                data-id="hilos-log-entry"
                [class]="
                  row.anchored
                    ? 'border border-primary rounded-1 bg-primary-subtle'
                    : ''
                "
                [attr.aria-current]="row.anchored ? 'location' : null"
              >
                <div
                  class="d-flex gap-2 px-3 py-1 font-monospace small text-break border-start border-4"
                  [class]="
                    'border-' +
                    levelVariant(row.level) +
                    (row.orphan ? ' opacity-75' : '')
                  "
                  [attr.data-id]="
                    row.anchored ? 'hilos-log-entry-anchor' : null
                  "
                >
                  <span
                    class="fw-semibold text-nowrap"
                    [class]="'text-' + levelVariant(row.level)"
                  >
                    {{ row.level }}
                  </span>
                  <span class="text-body-secondary text-nowrap">{{
                    row.time
                  }}</span>
                  <span class="flex-grow-1">{{ row.text }}</span>
                  @if (row.frames.length > 0) {
                    <button
                      type="button"
                      class="btn btn-sm btn-link p-0 text-decoration-none text-nowrap"
                      [attr.aria-expanded]="isOpen(row)"
                      [attr.aria-label]="
                        'Call stack of this entry, ' +
                        row.frames.length +
                        ' frames'
                      "
                      data-id="hilos-log-stack-toggle"
                      (click)="toggle(row)"
                    >
                      <i class="bi bi-info-circle me-1" aria-hidden="true"></i
                      >{{ row.frames.length }}
                    </button>
                  }
                </div>
                @if (row.frames.length > 0 && isOpen(row)) {
                  <div class="bg-body" data-id="hilos-log-stack">
                    @for (frame of row.frames; track $index) {
                      <div
                        class="d-flex gap-2 px-3 py-1 font-monospace small text-break opacity-75 border-start border-4"
                        [class]="'border-' + levelVariant(row.level)"
                      >
                        <span class="flex-grow-1">{{ frame.text }}</span>
                      </div>
                    }
                  </div>
                }
              </div>
            }
          }
        }
      </div>
    </hilos-admin-page>
  `,
})
export class HilosLogsViewPage {
  /** The project context: the connection and the action lifecycle. */
  readonly context = input.required<HilosLogViewerContext>()

  protected readonly page = HilosPages.LOGS_VIEW
  protected readonly live = LOG_SOURCE_LIVE
  protected readonly levelOptions = HILOS_LOG_LEVEL_OPTIONS
  protected readonly noticeIcons = NOTICE_ICONS
  protected readonly levelVariant = logLevelVariant
  protected readonly widestPendingLabel = LOG_VIEWER_PENDING_WIDEST_LABEL

  private readonly router = inject(HILOS_ROUTER, { optional: true })

  // The address IS what this screen is showing, so the navigator is what it reads
  // and writes. A router-less mount (none in practice) still reads files — it just
  // keeps the choice out of the location bar.
  private readonly address: HilosLogViewerAddress = this.router ?? {
    currentRoute: createSignal<PageRouteMatch>({
      page: HilosPages.LOGS_VIEW,
      params: {},
      admin: true,
    }),
    replacePath: () => {},
  }

  protected readonly viewer = computed(() =>
    createHilosLogViewer(this.context(), this.address),
  )

  // The pane is the scrolling element, so it is the one whose position answers
  // "is the reader at the tail" — the threshold itself is the headless's, so that
  // the Vue and React ports do not each invent their own.
  private readonly pane = viewChild<ElementRef<HTMLElement>>('pane')

  // Everything the pane draws, mirrored from the (per-context) core signals into
  // Angular signals so the template re-renders on every read and every pushed line.
  protected readonly catalog = signal<HilosLogViewerCatalog | null>(null)
  protected readonly selection = signal<HilosLogViewerSelection>(
    readLogViewerAddress(this.address.currentRoute.get().params),
  )
  protected readonly rows = signal<readonly HilosLogViewerRow[]>([])
  protected readonly level = signal('')
  protected readonly substring = signal('')
  protected readonly substringDraft = signal('')
  protected readonly substringDirty = signal(false)
  protected readonly busy = signal(false)
  protected readonly readable = signal(true)
  protected readonly hasMore = signal(false)
  protected readonly refusal = signal<string | null>(null)
  protected readonly followRequested = signal(false)
  protected readonly following = signal(false)
  protected readonly canFollow = signal(false)
  protected readonly pinned = signal(true)
  protected readonly pendingLines = signal(0)
  protected readonly pendingLabel = computed(() =>
    logViewerPendingLabel(this.pendingLines()),
  )

  // The node select exists only where nodes have names: a picker with one nameless
  // option is furniture for a choice that does not exist.
  protected readonly clustered = computed(() =>
    hasLogViewerNodes(this.catalog()),
  )
  protected readonly node = computed(() =>
    logViewerNodeOf(this.catalog(), this.selection().nodeId),
  )
  protected readonly streams = computed(() =>
    logViewerStreamsOf(this.node(), this.selection().source),
  )

  // Which state the pane is in — the discrimination is the headless's, because it
  // is the same question in all three view frameworks. The count is of ROWS and
  // not of entries: a file with no lines that has just been rotated has something
  // to say, and "this file is empty" would hide the note saying it.
  protected readonly paneState = computed(() =>
    logViewerPaneState(
      this.catalog(),
      this.selection(),
      this.rows().length,
      this.readable(),
      this.level() !== '' || this.substring() !== '',
    ),
  )

  // The counter beside the Earlier button counts entries, because that is the word
  // it uses; a note is not one.
  protected readonly entryCount = computed(
    () => this.rows().filter((row) => row.kind === 'entry').length,
  )

  // Newest batch first: an operator opening the archive is looking for what just
  // happened far more often than for what happened last month.
  protected readonly batches = computed(() =>
    [...(this.node()?.batches ?? [])].reverse(),
  )

  // Which stacks are open, by entry key. The key survives a page of older lines
  // arriving above, so an opened stack stays open when the pane grows upwards.
  private readonly opened = signal(new Set<string>())

  constructor() {
    // Read the catalog and the first page once the context input is bound, and stop
    // on destroy; the same effect re-binds on a context swap.
    effect((onCleanup) => {
      const viewer = this.viewer()
      viewer.start()
      const unsubscribes = [
        this.mirror(viewer.catalog, this.catalog.set),
        this.mirror(viewer.selection, this.selection.set),
        this.mirror(viewer.rows, this.rows.set),
        this.mirror(viewer.level, this.level.set),
        this.mirror(viewer.substring, this.substring.set),
        this.mirror(viewer.substringDraft, this.substringDraft.set),
        this.mirror(viewer.substringDirty, this.substringDirty.set),
        this.mirror(viewer.busy, this.busy.set),
        this.mirror(viewer.readable, this.readable.set),
        this.mirror(viewer.hasMore, this.hasMore.set),
        this.mirror(viewer.refusal, this.refusal.set),
        this.mirror(viewer.followRequested, this.followRequested.set),
        this.mirror(viewer.following, this.following.set),
        this.mirror(viewer.canFollow, this.canFollow.set),
        this.mirror(viewer.pinned, this.pinned.set),
        this.mirror(viewer.pendingLines, this.pendingLines.set),
      ]
      onCleanup(() => {
        for (const unsubscribe of unsubscribes) {
          unsubscribe()
        }
        viewer.dispose()
      })
    })

    // Sticking to the bottom happens after the rows are drawn, because the height to
    // scroll to does not exist until then; an ordinary effect would let the browser
    // paint one frame with the old scroll position and the pane would jump on every
    // batch of lines. The pin is read inside this effect on purpose: the effect is
    // reactive, and the pane must follow the pin as well as the rows.
    afterRenderEffect(() => {
      this.rows()
      if (!this.pinned()) {
        return
      }
      const element = this.pane()?.nativeElement
      if (element !== undefined) {
        element.scrollTop = element.scrollHeight
      }
    })
  }

  /**
   * Mirror one core signal into its Angular twin: the current value first, because
   * subscribing alone would leave the template on the default until the next frame.
   *
   * @param source The core signal to follow.
   * @param set The Angular signal's setter.
   */
  private mirror<T>(
    source: ReadonlySignal<T>,
    set: (value: T) => void,
  ): Unsubscribe {
    set(source.get())

    return subscribeSignal(source, set)
  }

  /** The value the source select carries for one choice. */
  protected sourceValue(
    source: typeof LOG_SOURCE_LIVE | number | null,
  ): string {
    return source === null ? '' : String(source)
  }

  protected batchLabel(batch: number): string {
    return new Date(batch * 1000).toLocaleString()
  }

  protected onNode(event: Event): void {
    this.viewer().select({ nodeId: (event.target as HTMLSelectElement).value })
  }

  protected onSource(event: Event): void {
    const value = (event.target as HTMLSelectElement).value
    this.viewer().select({
      source: value === LOG_SOURCE_LIVE ? LOG_SOURCE_LIVE : Number(value),
    })
  }

  protected onStream(event: Event): void {
    const value = (event.target as HTMLSelectElement).value
    this.viewer().select({ stream: value === '' ? null : value })
  }

  protected onLevel(event: Event): void {
    this.viewer().setLevel((event.target as HTMLSelectElement).value)
  }

  protected onSubstringInput(event: Event): void {
    this.viewer().editSubstring((event.target as HTMLInputElement).value)
  }

  protected onSubstringApply(): void {
    this.viewer().applySubstring()
  }

  protected onFollow(event: Event): void {
    this.viewer().setFollow((event.target as HTMLInputElement).checked)
  }

  protected onScroll(): void {
    const element = this.pane()?.nativeElement
    if (element === undefined) {
      return
    }

    this.viewer().setPinned(
      isLogViewerPinned(
        element.scrollTop,
        element.scrollHeight,
        element.clientHeight,
      ),
    )
  }

  protected isOpen(entry: HilosLogViewerEntry): boolean {
    return this.opened().has(entry.key)
  }

  protected toggle(entry: HilosLogViewerEntry): void {
    const next = new Set(this.opened())
    if (!next.delete(entry.key)) {
      next.add(entry.key)
    }
    this.opened.set(next)
  }
}

// framework/frontend/vue/src/admin/logs/HilosLogsViewPage.vue
<!-- HilosLogsViewPage — the framework Hilos log viewer (HilosPages.LOGS_VIEW):
the lines of ONE file on ONE node, for an administrator who came to work out what
already happened. The node, the source (the live journal or one archived batch)
and the stream together ARE the address of this screen, so choosing another file
rewrites the address in place rather than navigating — it is another file of the
same page, and a navigation would re-subscribe it and drop the catalog. Nothing
is filtered here: the level and the substring are fields of the read request, and
the server answers with what matched. The Follow switch runs the live tail, and
there is no Refresh button on purpose: freshness arrives as a push. Scrolling up
releases only the STICKING — the tail keeps running, what arrives while the
reader is up waits beside the pane, and the return control carries its count.
That control stands in the strip above the pane, in a room taken always (HIL-1024),
so neither its arrival nor its count moves the pane (styling-rules.md, "The room a
live message takes"); so nothing ever moves under the reader's eyes, and nothing is
lost without saying so. The note that a typed search is not applied yet stands
in the place of the line count, in a cell held at its width always (HIL-1152),
so it does not move the pane either. The catalog, the address, the read, the buffer and the row
view-model are the core headless's (hilosLogViewer), including the threshold that
decides "at the tail" and the wording of the notes — this view owns only the
markup and the scrolling, so a project mounts it by passing its
HilosLogViewerContext and the React and Angular ports measure the same edge.
Bootstrap classes only, save the one pre-wrap declaration the pane calls for
because Bootstrap has no utility for it (styling-rules.md, same exception as
HilosActionError). -->
<script setup lang="ts">
import {
  createHilosLogViewer,
  createSignal,
  hasLogViewerNodes,
  isLogViewerPinned,
  logLevelVariant,
  logViewerNodeOf,
  logViewerPaneState,
  logViewerPendingLabel,
  logViewerStreamsOf,
  HILOS_LOG_LEVEL_OPTIONS,
  HilosPages,
  LOG_SOURCE_LIVE,
  LOG_VIEWER_PENDING_WIDEST_LABEL,
  type HilosLogViewerAddress,
  type HilosLogViewerContext,
  type HilosLogViewerEntry,
  type HilosLogViewerNotice,
  type PageRouteMatch,
} from '@hilos/core'
import {
  computed,
  inject,
  nextTick,
  onMounted,
  onUnmounted,
  ref,
  watch,
} from 'vue'

import HilosAdminPage from '../../HilosAdminPage.vue'
import { hilosRouterKey } from '../../hilosRouterKey.js'
import { useSignal } from '../../useSignal.js'

const props = defineProps<{
  /** The project context: the connection and the action lifecycle. */
  context: HilosLogViewerContext
}>()

const router = inject(hilosRouterKey)
// The address IS what this screen is showing, so the navigator is what it reads
// and writes. A router-less mount (none in practice) still reads files — it just
// keeps the choice out of the location bar.
const address: HilosLogViewerAddress = router ?? {
  currentRoute: createSignal<PageRouteMatch>({
    page: HilosPages.LOGS_VIEW,
    params: {},
    admin: true,
  }),
  replacePath: () => {},
}

const viewer = createHilosLogViewer(props.context, address)
onMounted(() => viewer.start())
onUnmounted(() => viewer.dispose())

const catalog = useSignal(viewer.catalog)
const selection = useSignal(viewer.selection)
const rows = useSignal(viewer.rows)
const level = useSignal(viewer.level)
const substring = useSignal(viewer.substring)
const substringDraft = useSignal(viewer.substringDraft)
const substringDirty = useSignal(viewer.substringDirty)
const busy = useSignal(viewer.busy)
const readable = useSignal(viewer.readable)
const hasMore = useSignal(viewer.hasMore)
const refusal = useSignal(viewer.refusal)
const followRequested = useSignal(viewer.followRequested)
const following = useSignal(viewer.following)
const canFollow = useSignal(viewer.canFollow)
const pinned = useSignal(viewer.pinned)
const pendingLines = useSignal(viewer.pendingLines)

// The node select exists only where nodes have names: a picker with one nameless
// option is furniture for a choice that does not exist.
const clustered = computed(() => hasLogViewerNodes(catalog.value))
const node = computed(() =>
  logViewerNodeOf(catalog.value, selection.value.nodeId),
)
const streams = computed(() =>
  logViewerStreamsOf(node.value, selection.value.source),
)

// Which state the pane is in — the discrimination is the headless's, because it
// is the same question in all three view frameworks. The count is of ROWS and
// not of entries: a file with no lines that has just been rotated has something
// to say, and "this file is empty" would hide the note saying it.
const paneState = computed(() =>
  logViewerPaneState(
    catalog.value,
    selection.value,
    rows.value.length,
    readable.value,
    level.value !== '' || substring.value !== '',
  ),
)

// The counter beside the Earlier button counts entries, because that is the word
// it uses; a note is not one.
const entryCount = computed(
  () => rows.value.filter((row) => row.kind === 'entry').length,
)

// Newest batch first: an operator opening the archive is looking for what just
// happened far more often than for what happened last month.
const batches = computed(() => [...(node.value?.batches ?? [])].reverse())

/** The value the source select carries for one choice. */
function sourceValue(source: typeof LOG_SOURCE_LIVE | number | null): string {
  return source === null ? '' : String(source)
}

function batchLabel(batch: number): string {
  return new Date(batch * 1000).toLocaleString()
}

function onNode(event: Event): void {
  viewer.select({ nodeId: (event.target as HTMLSelectElement).value })
}

function onSource(event: Event): void {
  const value = (event.target as HTMLSelectElement).value
  viewer.select({
    source: value === LOG_SOURCE_LIVE ? LOG_SOURCE_LIVE : Number(value),
  })
}

function onStream(event: Event): void {
  const value = (event.target as HTMLSelectElement).value
  viewer.select({ stream: value === '' ? null : value })
}

function onLevel(event: Event): void {
  viewer.setLevel((event.target as HTMLSelectElement).value)
}

function onSubstringInput(event: Event): void {
  viewer.editSubstring((event.target as HTMLInputElement).value)
}

function applySubstring(): void {
  viewer.applySubstring()
}

function onFollow(event: Event): void {
  viewer.setFollow((event.target as HTMLInputElement).checked)
}

/** The icon one note is drawn with; its wording belongs to the headless. */
const NOTICE_ICONS: Record<HilosLogViewerNotice, string> = {
  rotated: 'bi-arrow-repeat',
  skipped: 'bi-fast-forward',
  dropped: 'bi-scissors',
  stopped: 'bi-stop-circle',
  anchorMissing: 'bi-geo-alt',
}

// The pane is the scrolling element, so it is the one whose position answers
// "is the reader at the tail" — the threshold itself is the headless's, so that
// the React and Angular ports do not each invent their own.
const pane = ref<HTMLElement | null>(null)

function onScroll(): void {
  const element = pane.value
  if (element === null) {
    return
  }

  viewer.setPinned(
    isLogViewerPinned(
      element.scrollTop,
      element.scrollHeight,
      element.clientHeight,
    ),
  )
}

// The pane is at the bottom whenever the viewer is pinned, which is a rule
// about both the rows and the pin. The scroll waits for nextTick because the
// height to scroll to does not exist until the rows are drawn.
watch([rows, pinned], async () => {
  if (!pinned.value) {
    return
  }

  await nextTick()
  const element = pane.value
  if (element !== null) {
    element.scrollTop = element.scrollHeight
  }
})

// Which stacks are open, by entry key. The key survives a page of older lines
// arriving above, so an opened stack stays open when the pane grows upwards.
const opened = ref(new Set<string>())

function isOpen(entry: HilosLogViewerEntry): boolean {
  return opened.value.has(entry.key)
}

function toggle(entry: HilosLogViewerEntry): void {
  const next = new Set(opened.value)
  if (!next.delete(entry.key)) {
    next.add(entry.key)
  }
  opened.value = next
}
</script>

<template>
  <HilosAdminPage :page="HilosPages.LOGS_VIEW">
    <div class="border rounded-3 p-3 mb-3">
      <div class="row g-2 align-items-end">
        <div v-if="clustered" class="col-6 col-md-2">
          <label class="form-label small fw-semibold mb-1" for="hilos-log-node">
            Node
          </label>
          <select
            id="hilos-log-node"
            class="form-select form-select-sm"
            :value="selection.nodeId ?? ''"
            data-id="hilos-log-node"
            @change="onNode"
          >
            <option value="" disabled>Choose a node</option>
            <option
              v-for="entry in catalog?.nodes ?? []"
              :key="entry.nodeId"
              :value="entry.nodeId"
            >
              {{ entry.nodeId }}
            </option>
          </select>
        </div>
        <div class="col-6 col-md-3">
          <label
            class="form-label small fw-semibold mb-1"
            for="hilos-log-source"
          >
            Source
          </label>
          <select
            id="hilos-log-source"
            class="form-select form-select-sm"
            :value="sourceValue(selection.source)"
            data-id="hilos-log-source"
            @change="onSource"
          >
            <option :value="LOG_SOURCE_LIVE">Live journal</option>
            <option v-for="batch in batches" :key="batch" :value="batch">
              Batch — {{ batchLabel(batch) }}
            </option>
          </select>
        </div>
        <div class="col-12 col-md-3">
          <label
            class="form-label small fw-semibold mb-1"
            for="hilos-log-stream"
          >
            Stream
          </label>
          <select
            id="hilos-log-stream"
            class="form-select form-select-sm"
            :value="selection.stream ?? ''"
            data-id="hilos-log-stream"
            @change="onStream"
          >
            <option value="">Choose a stream</option>
            <option
              v-for="stream in streams"
              :key="stream.key"
              :value="stream.key"
            >
              {{ stream.key }}
            </option>
          </select>
        </div>
        <div class="col-6 col-md-2">
          <label
            class="form-label small fw-semibold mb-1"
            for="hilos-log-level"
          >
            Level
          </label>
          <select
            id="hilos-log-level"
            class="form-select form-select-sm"
            :value="level"
            data-id="hilos-log-level"
            @change="onLevel"
          >
            <option
              v-for="option in HILOS_LOG_LEVEL_OPTIONS"
              :key="option.value"
              :value="option.value"
            >
              {{ option.label }}
            </option>
          </select>
        </div>
        <div class="col-6 col-md-2">
          <span class="form-label small fw-semibold mb-1 d-block">Follow</span>
          <div class="form-check form-switch mb-1">
            <input
              id="hilos-log-follow"
              class="form-check-input"
              type="checkbox"
              :checked="followRequested"
              :disabled="!canFollow"
              data-id="hilos-log-follow"
              @change="onFollow"
            />
            <label class="form-check-label small" for="hilos-log-follow">
              tail
            </label>
          </div>
          <span
            v-if="!canFollow"
            class="small text-body-secondary"
            data-id="hilos-log-follow-off"
          >
            An archived batch has no tail.
          </span>
        </div>
        <div class="col-12">
          <label class="visually-hidden" for="hilos-log-substring">
            Search inside the lines
          </label>
          <div class="input-group input-group-sm">
            <input
              id="hilos-log-substring"
              type="search"
              class="form-control"
              placeholder="Search inside the lines"
              :value="substringDraft"
              data-id="hilos-log-substring"
              @input="onSubstringInput"
              @keydown.enter="applySubstring"
            />
            <button
              type="button"
              class="btn"
              :class="substringDirty ? 'btn-primary' : 'btn-outline-secondary'"
              data-id="hilos-log-search"
              @click="applySubstring"
            >
              <i class="bi bi-search me-1" aria-hidden="true"></i>Search
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="d-flex flex-wrap align-items-center gap-2 mb-2">
      <button
        type="button"
        class="btn btn-sm btn-outline-secondary"
        :disabled="!hasMore || busy"
        data-id="hilos-log-earlier"
        @click="viewer.readOlder()"
      >
        <i class="bi bi-arrow-up me-1" aria-hidden="true"></i>Earlier
      </button>
      <!-- The line count and the note that the typed search is not applied
      yet share one cell (HIL-1152); the note stands in the count's place while
      the two texts differ, and an invisible twin of the note holds the cell at
      its width always, so neither its coming nor its going moves the pane
      (styling-rules.md, "The room a live message takes"); the status region
      stands there always so a screen reader hears the note arrive
      (accessibility.md, "Live regions"), and the count stays outside it
      because it changes with every line of the tail. -->
      <span class="hilos-stack" data-id="hilos-log-count-room">
        <span class="small invisible" aria-hidden="true">
          <i class="bi bi-exclamation-circle me-1"></i>Not applied yet — press
          Search
        </span>
        <span role="status" aria-live="polite">
          <span
            v-if="substringDirty"
            class="small text-warning-emphasis"
            data-id="hilos-log-search-pending"
          >
            <i class="bi bi-exclamation-circle me-1" aria-hidden="true"></i>Not
            applied yet — press Search
          </span>
        </span>
        <span
          v-if="!substringDirty"
          class="small text-body-secondary"
          data-id="hilos-log-count"
        >
          {{ entryCount }} entries shown
        </span>
      </span>
      <span
        v-if="following"
        class="ms-auto badge text-bg-success-subtle text-success-emphasis border border-success-subtle"
        data-id="hilos-log-tail-badge"
      >
        <i class="bi bi-broadcast me-1" aria-hidden="true"></i>Tail is running
      </span>
      <span
        class="hilos-stack"
        :class="{ 'ms-auto': !following }"
        data-id="hilos-log-back-to-tail-room"
      >
        <!-- Holds the room at the widest the control ever gets: a span rather
        than a button, since it keeps a place and must never take the focus. -->
        <span class="btn btn-sm invisible" aria-hidden="true">
          <i class="bi bi-arrow-down me-1"></i>Back to the tail
          <span class="badge text-bg-light ms-1">{{
            LOG_VIEWER_PENDING_WIDEST_LABEL
          }}</span>
        </span>
        <button
          v-if="!pinned"
          type="button"
          class="btn btn-sm btn-primary"
          data-id="hilos-log-back-to-tail"
          @click="viewer.returnToTail()"
        >
          <i class="bi bi-arrow-down me-1" aria-hidden="true"></i>Back to the
          tail
          <template v-if="pendingLines > 0">
            <span
              class="badge text-bg-light ms-1"
              data-id="hilos-log-back-to-tail-count"
            >
              {{ logViewerPendingLabel(pendingLines) }}
            </span>
            <span class="visually-hidden"> new lines</span>
          </template>
        </button>
      </span>
    </div>

    <div
      ref="pane"
      class="border rounded-3 bg-body-tertiary py-2 overflow-auto"
      style="max-height: 26rem; white-space: pre-wrap"
      data-id="hilos-log-pane"
      @scroll="onScroll"
    >
      <p
        v-if="refusal"
        class="px-3 mb-0 small text-danger"
        data-id="hilos-log-refusal"
      >
        {{ refusal }}
      </p>
      <p
        v-else-if="paneState === 'unknown'"
        class="px-3 mb-0 small text-body-secondary"
        data-id="hilos-log-empty-unknown"
      >
        The cluster picture has not arrived yet, so there is nothing to choose
        between — not nothing to read.
      </p>
      <p
        v-else-if="paneState === 'unreadable'"
        class="px-3 mb-0 small text-body-secondary"
        data-id="hilos-log-empty-unreadable"
      >
        <template v-if="clustered">
          No node could read its log store.
        </template>
        <template v-else>The log store could not be read.</template>
      </p>
      <p
        v-else-if="paneState === 'empty'"
        class="px-3 mb-0 small text-body-secondary"
        data-id="hilos-log-empty-catalog"
      >
        No streams have been reported yet.
      </p>
      <p
        v-else-if="paneState === 'unchosen'"
        class="px-3 mb-0 small text-body-secondary"
        data-id="hilos-log-empty-unchosen"
      >
        Choose a stream to read.
      </p>
      <p
        v-else-if="paneState === 'missing'"
        class="px-3 mb-0 small text-body-secondary"
        data-id="hilos-log-empty-missing"
      >
        This file cannot be read. The rotation may have carried it off, or
        nothing has written to it yet.
      </p>
      <p
        v-else-if="paneState === 'nomatch'"
        class="px-3 mb-0 small text-body-secondary"
        data-id="hilos-log-empty-nomatch"
      >
        Nothing in this file matched.
      </p>
      <p
        v-else-if="paneState === 'silent'"
        class="px-3 mb-0 small text-body-secondary"
        data-id="hilos-log-empty-silent"
      >
        This file is empty.
      </p>
      <template v-else>
        <template v-for="row in rows" :key="row.key">
          <div
            v-if="row.kind === 'notice'"
            class="d-flex align-items-center justify-content-center gap-2 px-3 py-1 small text-body-secondary"
            data-id="hilos-log-notice"
          >
            <i :class="`bi ${NOTICE_ICONS[row.notice]}`" aria-hidden="true"></i>
            <span>{{ row.text }}</span>
          </div>
          <!-- The entry a link opened the viewer on is framed so the eye lands on it;
          it comes first on its page, so nothing has to scroll to it. -->
          <div
            v-else
            data-id="hilos-log-entry"
            :class="{
              'border border-primary rounded-1 bg-primary-subtle': row.anchored,
            }"
            :aria-current="row.anchored ? 'location' : undefined"
          >
            <div
              class="d-flex gap-2 px-3 py-1 font-monospace small text-break border-start border-4"
              :class="[
                `border-${logLevelVariant(row.level)}`,
                { 'opacity-75': row.orphan },
              ]"
              :data-id="row.anchored ? 'hilos-log-entry-anchor' : undefined"
            >
              <span
                class="fw-semibold text-nowrap"
                :class="`text-${logLevelVariant(row.level)}`"
              >
                {{ row.level }}
              </span>
              <span class="text-body-secondary text-nowrap">{{
                row.time
              }}</span>
              <span class="flex-grow-1">{{ row.text }}</span>
              <button
                v-if="row.frames.length > 0"
                type="button"
                class="btn btn-sm btn-link p-0 text-decoration-none text-nowrap"
                :aria-expanded="isOpen(row)"
                :aria-label="`Call stack of this entry, ${row.frames.length} frames`"
                data-id="hilos-log-stack-toggle"
                @click="toggle(row)"
              >
                <i class="bi bi-info-circle me-1" aria-hidden="true"></i
                >{{ row.frames.length }}
              </button>
            </div>
            <div
              v-if="row.frames.length > 0 && isOpen(row)"
              class="bg-body"
              data-id="hilos-log-stack"
            >
              <div
                v-for="(frame, index) in row.frames"
                :key="index"
                class="d-flex gap-2 px-3 py-1 font-monospace small text-break opacity-75 border-start border-4"
                :class="`border-${logLevelVariant(row.level)}`"
              >
                <span class="flex-grow-1">{{ frame.text }}</span>
              </div>
            </div>
          </div>
        </template>
      </template>
    </div>
  </HilosAdminPage>
</template>
