// framework/frontend/angular/src/admin/i18n/translate/HilosI18nTranslateUiPageItemPage.ts
// HilosI18nTranslateUiPageItemPage — the I18n Translate Ui Page Item admin page (HilosPages.I18N_TRANSLATE_UI_PAGE_ITEM). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by projecting content into the
// shell's slot to replace its default body. Bootstrap classes only
// (styling-rules.md).
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../../HilosAdminPage.js'

/** The I18n Translate Ui Page Item admin page: the framework default shell for its key. */
@Component({
  selector: 'hilos-i18n-translate-ui-page-item-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosAdminPage],
  template: `<hilos-admin-page [page]="page" />`,
})
export class HilosI18nTranslateUiPageItemPage {
  /** The admin page key this default renders the shell for. */
  protected readonly page = HilosPages.I18N_TRANSLATE_UI_PAGE_ITEM
}

// framework/frontend/react/src/admin/i18n/translate/HilosI18nTranslateUiPageItemPage.tsx
// HilosI18nTranslateUiPageItemPage — the I18n Translate Ui Page Item admin page (HilosPages.I18N_TRANSLATE_UI_PAGE_ITEM). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../../HilosAdminPage.js'

/** The I18n Translate Ui Page Item admin page: the framework default shell for its key. */
export function HilosI18nTranslateUiPageItemPage() {
  return <HilosAdminPage page={HilosPages.I18N_TRANSLATE_UI_PAGE_ITEM} />
}
