// framework/frontend/vue/src/admin/daemon/HilosDaemonCronPage.vue
<!-- HilosDaemonCronPage — the Cron admin page (HilosPages.DAEMON_CRON). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.DAEMON_CRON" />
</template>

// framework/frontend/react/src/admin/daemon/HilosDaemonCronPage.tsx
// HilosDaemonCronPage — the Daemon Cron admin page (HilosPages.DAEMON_CRON). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Daemon Cron admin page: the framework default shell for its key. */
export function HilosDaemonCronPage() {
  return <HilosAdminPage page={HilosPages.DAEMON_CRON} />
}
