// framework/frontend/angular/src/admin/daemon/HilosDaemonWebsocketsPage.ts
// HilosDaemonWebsocketsPage — the Daemon Websockets admin page (HilosPages.DAEMON_WEBSOCKETS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by projecting content into the
// shell's slot to replace its default body. Bootstrap classes only
// (styling-rules.md).
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Daemon Websockets admin page: the framework default shell for its key. */
@Component({
  selector: 'hilos-daemon-websockets-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosAdminPage],
  template: `<hilos-admin-page [page]="page" />`,
})
export class HilosDaemonWebsocketsPage {
  /** The admin page key this default renders the shell for. */
  protected readonly page = HilosPages.DAEMON_WEBSOCKETS
}

// framework/frontend/react/src/admin/daemon/HilosDaemonWebsocketsPage.tsx
// HilosDaemonWebsocketsPage — the Daemon Websockets admin page (HilosPages.DAEMON_WEBSOCKETS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Daemon Websockets admin page: the framework default shell for its key. */
export function HilosDaemonWebsocketsPage() {
  return <HilosAdminPage page={HilosPages.DAEMON_WEBSOCKETS} />
}
