// framework/frontend/react/src/admin/i18n/translate/HilosI18nTranslateEmailPage.tsx
// HilosI18nTranslateEmailPage — the I18n Translate Email admin page (HilosPages.I18N_TRANSLATE_EMAIL). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../../HilosAdminPage.js'

/** The I18n Translate Email admin page: the framework default shell for its key. */
export function HilosI18nTranslateEmailPage() {
  return <HilosAdminPage page={HilosPages.I18N_TRANSLATE_EMAIL} />
}

// framework/frontend/vue/src/admin/i18n/translate/HilosI18nTranslateEmailPage.vue
<!-- HilosI18nTranslateEmailPage — the Translate email admin page (HilosPages.I18N_TRANSLATE_EMAIL). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.I18N_TRANSLATE_EMAIL" />
</template>
