// framework/frontend/angular/src/admin/analytics/HilosAnalyticsPage.ts
// HilosAnalyticsPage — the Analytics admin page (HilosPages.ANALYTICS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by projecting content into the
// shell's slot to replace its default body. Bootstrap classes only
// (styling-rules.md).
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Analytics admin page: the framework default shell for its key. */
@Component({
  selector: 'hilos-analytics-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosAdminPage],
  template: `<hilos-admin-page [page]="page" />`,
})
export class HilosAnalyticsPage {
  /** The admin page key this default renders the shell for. */
  protected readonly page = HilosPages.ANALYTICS
}

// framework/frontend/vue/src/admin/analytics/HilosAnalyticsPage.vue
<!-- HilosAnalyticsPage — the Analytics admin page (HilosPages.ANALYTICS). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.ANALYTICS" />
</template>
