// demo/chat/frontend/src/views/Hilos/SecurityOauthProvider/SecurityOauthProvider.vue
<!-- The OAuth provider admin page (HilosPages.SECURITY_OAUTH_PROVIDER). A thin binding of the page key to
the framework admin shell (HilosAdminPage), which resolves the label, lead,
breadcrumb, and sub-section children from the core admin tree. Bootstrap classes
only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'
import { HilosAdminPage } from '@hilos/vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.SECURITY_OAUTH_PROVIDER" />
</template>

// demo/tasks/frontend/src/views/Hilos/Security/SecurityOauthProvider.tsx
// The Hilos OAuth provider page (HilosPages.SECURITY_OAUTH_PROVIDER, HIL-286): a
// thin project binding of the framework HilosSecurityOauthProviderPage to this
// app's context. Bootstrap classes only (styling-rules.md).
import { HilosSecurityOauthProviderPage } from '@hilos/react'

import { hilosSecurityOauthContext } from './hilosSecurityOauthContext'

export default function SecurityOauthProvider() {
  return <HilosSecurityOauthProviderPage context={hilosSecurityOauthContext} />
}
