// framework/frontend/react/src/legal/HilosLegalRevisionText.tsx
import type { HilosLegalClause } from '@hilos/core'

export interface HilosLegalRevisionTextProps {
  clauses: HilosLegalClause[]
}

/** Numbered effective clauses with the project's deviations identified. */
export function HilosLegalRevisionText({
  clauses,
}: HilosLegalRevisionTextProps) {
  return (
    <ol className="ps-4 mb-0 text-break" data-id="legal-revision-text">
      {clauses.map((clause) => (
        <li
          key={clause.clauseKey}
          className="mb-3"
          data-id="legal-revision-clause"
        >
          <strong>{clause.statement}.</strong>
          {clause.text.split('\n\n').map((paragraph, index) => (
            <p key={index} className="mb-2">
              {paragraph}
            </p>
          ))}
          {clause.source === 'deviation' && (
            <div
              className="small text-body-secondary"
              data-id="legal-revision-clause-deviation"
            >
              Project deviation from: {clause.standardStatement} ·{' '}
              {clause.direction}
            </div>
          )}
        </li>
      ))}
    </ol>
  )
}

// framework/frontend/angular/src/legal/HilosLegalRevisionText.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import type { HilosLegalClause } from '@hilos/core'

/** Numbered effective clauses and the origin of each project deviation. */
@Component({
  selector: 'hilos-legal-revision-text',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ol class="ps-4 mb-0 text-break" data-id="legal-revision-text">
      @for (clause of clauses(); track clause.clauseKey) {
        <li class="mb-3" data-id="legal-revision-clause">
          <strong>{{ clause.statement }}.</strong>
          @for (paragraph of clause.text.split('\\n\\n'); track $index) {
            <p class="mb-2">{{ paragraph }}</p>
          }
          @if (clause.source === 'deviation') {
            <div
              class="small text-body-secondary"
              data-id="legal-revision-clause-deviation"
            >
              Project deviation from: {{ clause.standardStatement }} ·
              {{ clause.direction }}
            </div>
          }
        </li>
      }
    </ol>
  `,
})
export class HilosLegalRevisionText {
  readonly clauses = input.required<HilosLegalClause[]>()
}
