// demo/chat/frontend/src/views/MainView.vue
<!-- The chat main page (PAGE_MAIN). For now it shows the session's current user
resolved from the session scope; the real chat views land here later. Rendered
by HilosView when the navigator's route is the main page. -->
<script setup lang="ts">
import { useSignal } from '@hilos/vue'

import { currentUserName } from '../session'

const selfName = useSignal(currentUserName)
</script>

<template>
  <p>Signed in as <span data-id="self-user">{{ selfName }}</span></p>
</template>

// demo/simple-todo/frontend/src/views/MainView.tsx
// The todo main page (PAGE_MAIN). For now it shows the session's current user
// resolved from the session scope; the real todo views land here later.
// Rendered by HilosView when the navigator's route is the main page.
import { useSignal } from '@hilos/react'

import { currentUserName } from '../session'

export default function MainView() {
  const selfName = useSignal(currentUserName)
  return (
    <p>
      Signed in as <span data-id="self-user">{selfName}</span>
    </p>
  )
}
