// framework/frontend/react/src/admin/sil/HilosSilRequestsPage.tsx
// HilosSilRequestsPage — the Sil Requests admin page (HilosPages.SIL_REQUESTS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Sil Requests admin page: the framework default shell for its key. */
export function HilosSilRequestsPage() {
  return <HilosAdminPage page={HilosPages.SIL_REQUESTS} />
}

// framework/frontend/vue/src/admin/sil/HilosSilRequestsPage.vue
<!-- HilosSilRequestsPage — the Requests admin page (HilosPages.SIL_REQUESTS). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.SIL_REQUESTS" />
</template>
