// demo/simple-todo/frontend/src/views/Licence/Licence.tsx
// The public Licence page (HilosPages.LICENCE). A framework-declared static
// page; this project supplies the content. See views/About/About.tsx.
import { HilosStaticPage } from '@hilos/react'

export default function Licence() {
  return (
    <HilosStaticPage title="Licence">
      <p>The Hilos framework is released under the MIT licence.</p>
      <p>
        Permission is hereby granted, free of charge, to any person obtaining a
        copy of this software and associated documentation files, to deal in the
        software without restriction — including the rights to use, copy, modify,
        merge, publish, distribute, sublicense, and/or sell copies of it.
      </p>
      <p className="mb-0">
        The software is provided “as is”, without warranty of any kind.
      </p>
    </HilosStaticPage>
  )
}

// demo/chat/frontend/src/views/Licence.vue
<template>
  <div class="row">
    <div class="col-12 col-lg-8 mx-auto">
      <div class="card">
        <div class="card-header">
          <h2 class="h4 mb-0 fw-bold">Licence</h2>
        </div>
        <div class="card-body">
          <h3 class="h5 mb-2 fw-bold">MIT License</h3>
          <p class="mb-2">
            Copyright (c) 2018 anlide
          </p>
          <p class="mb-2">
            Permission is hereby granted, free of charge, to any person obtaining a copy
            of this software and associated documentation files (the "Software"), to deal
            in the Software without restriction, including without limitation the rights
            to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
            copies of the Software, and to permit persons to whom the Software is
            furnished to do so, subject to the following conditions:
          </p>
          <p class="mb-2">
            The above copyright notice and this permission notice shall be included in all
            copies or substantial portions of the Software.
          </p>
          <p class="mb-0">
            THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
            AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
            LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
            OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
            SOFTWARE.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Licence page placeholder
</script>
