// framework/frontend/vue/src/admin/legal/HilosLegalDocumentPage.vue
<script setup lang="ts">
import {
  computedSignal,
  createHilosLegalRevisionsTable,
  createHilosLegalConsentPreview,
  createHilosLegalReconsentPreview,
  hilosLegalDocumentLabel,
  LEGAL_TERMS_UNPUBLISHED_MESSAGE,
  HilosPages,
  LEGAL_CATALOG_REFUSAL_SECTION,
  LEGAL_DOCUMENT_SECTION,
  LEGAL_RECONSENT_COPY,
  legalAdminDocumentSchema,
  resolveHilosPath,
  type HilosLegalContext,
  type HilosLegalDocumentKey,
} from '@hilos/core'
import { computed, inject, onMounted, onUnmounted, ref } from 'vue'
import HilosAdminPage from '../../HilosAdminPage.vue'
import HilosModal from '../../HilosModal.vue'
import HilosFormError from '../../HilosFormError.vue'
import HilosLegalConsent from '../../legal/HilosLegalConsent.vue'
import HilosLegalReconsent from '../../legal/HilosLegalReconsent.vue'
import HilosLink from '../../HilosLink.vue'
import HilosViewportTable from '../../HilosViewportTable.vue'
import { hilosRouterKey } from '../../hilosRouterKey.js'
import { useSignal } from '../../useSignal.js'

const props = defineProps<{ context: HilosLegalContext }>()
const router = inject(hilosRouterKey)
if (!router)
  throw new Error('HilosLegalDocumentPage requires a provided Hilos router.')
const documentKey = computedSignal(() =>
  String(router.currentRoute.get().params.documentKey ?? ''),
)
const document = useSignal(
  props.context.scopes.pageDataSignal(LEGAL_DOCUMENT_SECTION),
)
const refusal = useSignal(
  props.context.scopes.pageDataSignal(LEGAL_CATALOG_REFUSAL_SECTION),
)
const details = computed(() => {
  const parsed = legalAdminDocumentSchema.safeParse(document.value)
  return parsed.success ? parsed.data : null
})
const revisions = createHilosLegalRevisionsTable(props.context, documentKey)
const preview = createHilosLegalConsentPreview(props.context)
const previewOpen = useSignal(preview.opened)
const previewTerms = useSignal(preview.terms)
const previewLoading = useSignal(preview.loading)
const previewError = useSignal(preview.error)
const accepted = ref(false)
const reading = ref<HilosLegalDocumentKey | null>(null)
function openPreview(): void {
  accepted.value = false
  reading.value = null
  void preview.open()
}
// The "the terms have changed" screen as whoever held the previous revision
// sees it today (HIL-500): the same component in a read-only modal.
const reconsent = createHilosLegalReconsentPreview(props.context)
const reconsentOpen = useSignal(reconsent.opened)
const reconsentPreview = useSignal(reconsent.preview)
const reconsentLoading = useSignal(reconsent.loading)
const reconsentError = useSignal(reconsent.error)
const reconsentView = useSignal(reconsent.view)
function openReconsent(): void {
  if (details.value) void reconsent.open(details.value.document)
}
onMounted(() => revisions.start())
onUnmounted(() => {
  revisions.dispose()
  preview.close()
  reconsent.close()
})
</script>

<template>
  <HilosAdminPage :page="HilosPages.LEGAL_DOCUMENT">
    <div
      v-if="typeof refusal === 'string'"
      class="alert alert-danger text-break"
      role="alert"
      data-id="legal-catalog-refusal"
    >
      <h2 class="h6">The legal document catalog could not be loaded</h2>
      <p class="mb-0">{{ refusal }}</p>
    </div>
    <template v-else-if="details">
      <div class="alert alert-secondary small">
        Document texts live in code. A new revision is published by a
        deployment.
      </div>
      <section v-if="details.set" data-id="legal-set" class="mb-4">
        <h2 class="h5">Hilos standard set {{ details.set.version }}</h2>
        <p class="small text-body-secondary">
          {{ details.set.publishedOn }} · {{ details.set.significance }} ·
          {{ details.set.clauses.length }} clauses
        </p>
        <ol class="list-group list-group-numbered">
          <li
            v-for="clause in details.set.clauses"
            :key="clause.clauseKey"
            class="list-group-item text-break"
          >
            <code class="small me-2">{{ clause.clauseKey }}</code
            >{{ clause.statement }}
          </li>
        </ol>
      </section>
      <section
        v-if="details.newerSet"
        class="alert alert-warning"
        data-id="legal-set-newer"
      >
        <h2 class="h6">
          Hilos has released set {{ details.newerSet.version }} for this
          document
        </h2>
        <p class="small">
          {{ details.newerSet.publishedOn }} ·
          {{ details.newerSet.significance }}. The project keeps its declared
          set until it publishes a new revision.
        </p>
        <ul class="mb-0 small">
          <li
            v-for="change in details.newerSet.changes"
            :key="change.clauseKey"
          >
            {{ change.kind }}: {{ change.title }}
            <code>{{ change.clauseKey }}</code>
          </li>
        </ul>
      </section>
      <section class="mb-4">
        <h2 class="h5">Different in this project</h2>
        <p v-if="!details.deviations.length" class="text-body-secondary">
          No project deviations are declared.
        </p>
        <div
          v-for="deviation in details.deviations"
          :key="deviation.clauseKey"
          class="border rounded p-3 mb-2 text-break"
          data-id="legal-deviation-row"
        >
          <h3 class="h6">
            {{ deviation.statement }}
            <span class="badge text-bg-secondary">{{
              deviation.direction
            }}</span>
          </h3>
          <p class="small text-body-secondary">
            Standard: {{ deviation.standardStatement }} ·
            <code>{{ deviation.clauseKey }}</code>
          </p>
          <p
            v-for="(paragraph, index) in deviation.text.split('\n\n')"
            :key="index"
            class="small mb-2"
          >
            {{ paragraph }}
          </p>
        </div>
      </section>
      <section class="mb-4">
        <h2 class="h5">How a person sees it</h2>
        <button
          type="button"
          class="btn btn-outline-secondary"
          data-id="legal-preview-consent"
          @click="openPreview"
        >
          <i class="bi bi-eye me-1" aria-hidden="true" />Consent screen at
          registration
        </button>
        <button
          type="button"
          class="btn btn-outline-secondary ms-2"
          data-id="legal-preview-reconsent"
          @click="openReconsent"
        >
          <i class="bi bi-arrow-repeat me-1" aria-hidden="true" />Re-consent
          screen
        </button>
      </section>
      <HilosViewportTable :controller="revisions.controller">
        <template #cell-rowKey="{ row }">
          <div data-id="legal-revision-row" :data-revision="row.rowKey">
            <strong>{{ row.rowKey }}</strong>
            <span v-if="row.current" class="badge text-bg-primary ms-2"
              >Current</span
            >
            <span v-if="!row.declared" class="badge text-bg-warning ms-2"
              >Not in code</span
            >
            <div v-if="row.revision" class="small text-body-secondary">
              {{ row.revision.publishedOn }} · {{ row.revision.significance }} ·
              Effective {{ row.revision.effectiveOn }} · Set
              {{ row.revision.setVersion }}
            </div>
          </div>
        </template>
        <template #cell-actions="{ row }"
          ><HilosLink
            :to="
              resolveHilosPath(HilosPages.LEGAL_REVISION, {
                documentKey: details.document,
                revisionId: row.rowKey,
              })
            "
            class="btn btn-sm btn-outline-secondary"
            data-id="legal-revision-open"
            :data-revision="row.rowKey"
            >Open</HilosLink
          ></template
        >
      </HilosViewportTable>
    </template>
    <HilosModal
      :model-value="previewOpen"
      title="Consent screen at registration"
      initial-focus="dialog"
      @update:model-value="
        (value) => {
          if (!value) preview.close()
        }
      "
    >
      <div data-id="legal-consent-preview">
        <div class="visually-hidden" role="status" aria-live="polite">
          {{ previewError ?? (previewLoading ? 'Loading terms…' : '') }}
        </div>
        <div
          v-if="previewLoading"
          class="placeholder-glow"
          data-id="legal-consent-loading"
          aria-busy="true"
        >
          <span class="placeholder col-12" aria-hidden="true" />
          <span class="placeholder col-9" aria-hidden="true" />
        </div>
        <p
          v-if="previewTerms?.documents.length === 0"
          data-id="legal-consent-unpublished"
        >
          {{ LEGAL_TERMS_UNPUBLISHED_MESSAGE }}
        </p>
        <HilosLegalConsent
          v-else-if="previewTerms"
          v-model:accepted="accepted"
          v-model:reading="reading"
          :terms="previewTerms"
        />
        <p
          v-if="previewTerms?.form === 'line' && previewTerms.documents.length"
          class="small text-body-secondary mb-0"
          data-id="auth-consent-line"
        >
          By creating an account you accept the
          <template
            v-for="(item, index) in previewTerms.documents"
            :key="item.document"
          >
            <template v-if="index"> and the </template>
            <button
              type="button"
              class="btn btn-link btn-sm p-0"
              data-id="legal-consent-read"
              :data-document="item.document"
              @click="reading = item.document"
            >
              {{ hilosLegalDocumentLabel(item.document) }}
            </button> </template
          >.
        </p>
        <HilosFormError
          :message="previewError"
          data-id="legal-consent-preview-error"
        />
      </div>
      <template #actions>
        <button
          v-if="previewError"
          type="button"
          class="btn btn-primary"
          data-id="legal-consent-preview-retry"
          @click="openPreview"
        >
          Try again
        </button>
        <button
          type="button"
          class="btn btn-secondary"
          data-id="legal-consent-preview-close"
          @click="preview.close"
        >
          Close
        </button>
      </template>
    </HilosModal>
    <HilosModal
      :model-value="reconsentOpen"
      title="Re-consent screen"
      initial-focus="dialog"
      @update:model-value="
        (value) => {
          if (!value) reconsent.close()
        }
      "
    >
      <div data-id="legal-reconsent-preview">
        <HilosLegalReconsent
          variant="preview"
          :content="reconsentPreview"
          :view="reconsentView"
          :loading="reconsentLoading"
          :error="reconsentError"
          @retry="openReconsent"
          @show="reconsent.show"
        />
      </div>
      <template #actions>
        <button
          type="button"
          class="btn btn-secondary"
          data-id="legal-reconsent-preview-close"
          @click="reconsent.close"
        >
          {{ LEGAL_RECONSENT_COPY.close }}
        </button>
      </template>
    </HilosModal>
  </HilosAdminPage>
</template>

// framework/frontend/react/src/admin/legal/HilosLegalDocumentPage.tsx
import { useContext, useEffect, useMemo, useState } from 'react'
import {
  computedSignal,
  createHilosLegalRevisionsTable,
  createHilosLegalConsentPreview,
  createHilosLegalReconsentPreview,
  hilosLegalDocumentLabel,
  LEGAL_TERMS_UNPUBLISHED_MESSAGE,
  HilosPages,
  HilosLegalRowKey,
  HILOS_TABLE_ACTIONS_KEY,
  LEGAL_CATALOG_REFUSAL_SECTION,
  LEGAL_DOCUMENT_SECTION,
  LEGAL_RECONSENT_COPY,
  legalAdminDocumentSchema,
  resolveHilosPath,
  type HilosLegalContext,
  type HilosLegalDocumentKey,
} from '@hilos/core'
import { HilosAdminPage } from '../../HilosAdminPage.js'
import { HilosModal } from '../../HilosModal.js'
import { HilosFormError } from '../../HilosFormError.js'
import { HilosLegalConsent } from '../../legal/HilosLegalConsent.js'
import { HilosLegalReconsent } from '../../legal/HilosLegalReconsent.js'
import { HilosLink } from '../../HilosLink.js'
import { HilosViewportTable } from '../../HilosViewportTable.js'
import { HilosRouterContext } from '../../hilosRouterContext.js'
import { useSignal } from '../../useSignal.js'

/** A document's adopted standard, deviations and revision history. */
export function HilosLegalDocumentPage({
  context,
}: {
  context: HilosLegalContext
}) {
  const router = useContext(HilosRouterContext)
  if (!router)
    throw new Error('HilosLegalDocumentPage requires a provided Hilos router.')
  const document = useMemo(
    () =>
      computedSignal(() =>
        String(router.currentRoute.get().params.documentKey ?? ''),
      ),
    [router],
  )
  const revisions = useMemo(
    () => createHilosLegalRevisionsTable(context, document),
    [context, document],
  )
  const preview = useMemo(
    () => createHilosLegalConsentPreview(context),
    [context],
  )
  const previewOpen = useSignal(preview.opened)
  const previewTerms = useSignal(preview.terms)
  const previewLoading = useSignal(preview.loading)
  const previewError = useSignal(preview.error)
  const [accepted, setAccepted] = useState(false)
  const [reading, setReading] = useState<HilosLegalDocumentKey | null>(null)
  useEffect(() => () => preview.close(), [preview])
  function openPreview(): void {
    setAccepted(false)
    setReading(null)
    void preview.open()
  }
  const raw = useSignal(context.scopes.pageDataSignal(LEGAL_DOCUMENT_SECTION))
  const refusal = useSignal(
    context.scopes.pageDataSignal(LEGAL_CATALOG_REFUSAL_SECTION),
  )
  const parsed = legalAdminDocumentSchema.safeParse(raw)
  const details = parsed.success ? parsed.data : null
  // The "the terms have changed" screen as whoever held the previous revision
  // sees it today (HIL-500): the same component in a read-only modal.
  const reconsent = useMemo(
    () => createHilosLegalReconsentPreview(context),
    [context],
  )
  const reconsentOpen = useSignal(reconsent.opened)
  const reconsentPreview = useSignal(reconsent.preview)
  const reconsentLoading = useSignal(reconsent.loading)
  const reconsentError = useSignal(reconsent.error)
  const reconsentView = useSignal(reconsent.view)
  useEffect(() => () => reconsent.close(), [reconsent])
  function openReconsent(): void {
    if (details) void reconsent.open(details.document)
  }
  useEffect(() => {
    revisions.start()
    return () => revisions.dispose()
  }, [revisions])
  return (
    <HilosAdminPage page={HilosPages.LEGAL_DOCUMENT}>
      {typeof refusal === 'string' ? (
        <div
          className="alert alert-danger text-break"
          role="alert"
          data-id="legal-catalog-refusal"
        >
          <h2 className="h6">The legal document catalog could not be loaded</h2>
          <p className="mb-0">{refusal}</p>
        </div>
      ) : (
        details && (
          <>
            <div className="alert alert-secondary small">
              Document texts live in code. A new revision is published by a
              deployment.
            </div>
            {details.set && (
              <section data-id="legal-set" className="mb-4">
                <h2 className="h5">Hilos standard set {details.set.version}</h2>
                <p className="small text-body-secondary">
                  {details.set.publishedOn} · {details.set.significance} ·{' '}
                  {details.set.clauses.length} clauses
                </p>
                <ol className="list-group list-group-numbered">
                  {details.set.clauses.map((clause) => (
                    <li
                      key={clause.clauseKey}
                      className="list-group-item text-break"
                    >
                      <code className="small me-2">{clause.clauseKey}</code>
                      {clause.statement}
                    </li>
                  ))}
                </ol>
              </section>
            )}
            {details.newerSet && (
              <section
                className="alert alert-warning"
                data-id="legal-set-newer"
              >
                <h2 className="h6">
                  Hilos has released set {details.newerSet.version} for this
                  document
                </h2>
                <p className="small">
                  {details.newerSet.publishedOn} ·{' '}
                  {details.newerSet.significance}. The project keeps its
                  declared set until it publishes a new revision.
                </p>
                <ul className="mb-0 small">
                  {details.newerSet.changes.map((change) => (
                    <li key={change.clauseKey}>
                      {change.kind}: {change.title}{' '}
                      <code>{change.clauseKey}</code>
                    </li>
                  ))}
                </ul>
              </section>
            )}
            <section className="mb-4">
              <h2 className="h5">Different in this project</h2>
              {details.deviations.length === 0 && (
                <p className="text-body-secondary">
                  No project deviations are declared.
                </p>
              )}
              {details.deviations.map((deviation) => (
                <div
                  key={deviation.clauseKey}
                  className="border rounded p-3 mb-2 text-break"
                  data-id="legal-deviation-row"
                >
                  <h3 className="h6">
                    {deviation.statement}{' '}
                    <span className="badge text-bg-secondary">
                      {deviation.direction}
                    </span>
                  </h3>
                  <p className="small text-body-secondary">
                    Standard: {deviation.standardStatement} ·{' '}
                    <code>{deviation.clauseKey}</code>
                  </p>
                  {deviation.text.split('\n\n').map((paragraph, index) => (
                    <p key={index} className="small mb-2">
                      {paragraph}
                    </p>
                  ))}
                </div>
              ))}
            </section>
            <section className="mb-4">
              <h2 className="h5">How a person sees it</h2>
              <button
                type="button"
                className="btn btn-outline-secondary"
                data-id="legal-preview-consent"
                onClick={openPreview}
              >
                <i className="bi bi-eye me-1" aria-hidden="true" />
                Consent screen at registration
              </button>
              <button
                type="button"
                className="btn btn-outline-secondary ms-2"
                data-id="legal-preview-reconsent"
                onClick={openReconsent}
              >
                <i className="bi bi-arrow-repeat me-1" aria-hidden="true" />
                Re-consent screen
              </button>
            </section>
            <HilosViewportTable
              controller={revisions.controller}
              cells={{
                [HilosLegalRowKey.rowKey]: (row) => (
                  <div data-id="legal-revision-row" data-revision={row.rowKey}>
                    <strong>{row.rowKey}</strong>
                    {row.current && (
                      <span className="badge text-bg-primary ms-2">
                        Current
                      </span>
                    )}
                    {!row.declared && (
                      <span className="badge text-bg-warning ms-2">
                        Not in code
                      </span>
                    )}
                    {row.revision && (
                      <div className="small text-body-secondary">
                        {row.revision.publishedOn} · {row.revision.significance}{' '}
                        · Effective {row.revision.effectiveOn} · Set{' '}
                        {row.revision.setVersion}
                      </div>
                    )}
                  </div>
                ),
                [HILOS_TABLE_ACTIONS_KEY]: (row) => (
                  <HilosLink
                    to={resolveHilosPath(HilosPages.LEGAL_REVISION, {
                      documentKey: details.document,
                      revisionId: row.rowKey,
                    })}
                    className="btn btn-sm btn-outline-secondary"
                    data-id="legal-revision-open"
                    data-revision={row.rowKey}
                  >
                    Open
                  </HilosLink>
                ),
              }}
            />
          </>
        )
      )}
      <HilosModal
        open={previewOpen}
        title="Consent screen at registration"
        initialFocus="dialog"
        onClose={() => preview.close()}
        actions={() => (
          <>
            {previewError && (
              <button
                type="button"
                className="btn btn-primary"
                data-id="legal-consent-preview-retry"
                onClick={openPreview}
              >
                Try again
              </button>
            )}
            <button
              type="button"
              className="btn btn-secondary"
              data-id="legal-consent-preview-close"
              onClick={() => preview.close()}
            >
              Close
            </button>
          </>
        )}
      >
        <div data-id="legal-consent-preview">
          <div className="visually-hidden" role="status" aria-live="polite">
            {previewError ?? (previewLoading ? 'Loading terms…' : '')}
          </div>
          {previewLoading && (
            <div
              className="placeholder-glow"
              data-id="legal-consent-loading"
              aria-busy="true"
            >
              <span className="placeholder col-12" aria-hidden="true" />
              <span className="placeholder col-9" aria-hidden="true" />
            </div>
          )}
          {previewTerms &&
            (previewTerms.documents.length > 0 ? (
              <HilosLegalConsent
                terms={previewTerms}
                accepted={accepted}
                reading={reading}
                onAcceptedChange={setAccepted}
                onReadingChange={setReading}
              />
            ) : (
              <p data-id="legal-consent-unpublished">
                {LEGAL_TERMS_UNPUBLISHED_MESSAGE}
              </p>
            ))}
          {previewTerms?.form === 'line' &&
            previewTerms.documents.length > 0 && (
              <p
                className="small text-body-secondary mb-0"
                data-id="auth-consent-line"
              >
                By creating an account you accept the{' '}
                {previewTerms.documents.map((item, index) => (
                  <span key={item.document}>
                    {index > 0 && ' and the '}
                    <button
                      type="button"
                      className="btn btn-link btn-sm p-0"
                      data-id="legal-consent-read"
                      data-document={item.document}
                      onClick={() => setReading(item.document)}
                    >
                      {hilosLegalDocumentLabel(item.document)}
                    </button>
                  </span>
                ))}
                .
              </p>
            )}
          <HilosFormError
            message={previewError}
            dataId="legal-consent-preview-error"
          />
        </div>
      </HilosModal>
      <HilosModal
        open={reconsentOpen}
        title="Re-consent screen"
        initialFocus="dialog"
        onClose={() => reconsent.close()}
        actions={() => (
          <button
            type="button"
            className="btn btn-secondary"
            data-id="legal-reconsent-preview-close"
            onClick={() => reconsent.close()}
          >
            {LEGAL_RECONSENT_COPY.close}
          </button>
        )}
      >
        <div data-id="legal-reconsent-preview">
          <HilosLegalReconsent
            variant="preview"
            content={reconsentPreview}
            view={reconsentView}
            loading={reconsentLoading}
            error={reconsentError}
            onRetry={openReconsent}
            onShow={reconsent.show}
          />
        </div>
      </HilosModal>
    </HilosAdminPage>
  )
}
