// framework/frontend/react/src/profile/HilosProfileSessions.tsx
import {
  endableProfileSessionCount,
  formatProfileDateTime,
  type HilosProfileSession,
  type HilosProfileSessionActions,
} from '@hilos/core'
import { useState } from 'react'

import { HilosFormError } from '../HilosFormError.js'
import { HilosModal } from '../HilosModal.js'
import { LoadingButton } from '../LoadingButton.js'
import { useTrackedAction } from '../useTrackedAction.js'

/** Props for {@link HilosProfileSessions}. */
export interface HilosProfileSessionsProps {
  readonly sessions: readonly HilosProfileSession[]
  readonly actions: HilosProfileSessionActions
}

/** The shared session list, tab disclosure, and end-session controls. */
export function HilosProfileSessions({
  sessions,
  actions,
}: HilosProfileSessionsProps) {
  const [expanded, setExpanded] = useState<ReadonlySet<number>>(new Set())
  const [endingSessionId, setEndingSessionId] = useState<number | null>(null)
  const [endOthersOpen, setEndOthersOpen] = useState(false)
  const endAction = useTrackedAction()
  const endOthersAction = useTrackedAction()
  const selectedSession = sessions.find(
    (session) => session.id === endingSessionId,
  )
  const endError =
    selectedSession === undefined
      ? 'This session has already ended'
      : endAction.error
  const endableCount = endableProfileSessionCount(sessions)
  const endOthersError =
    endableCount === 0
      ? 'Your other sessions have already ended'
      : endOthersAction.error

  function toggleTabs(sessionId: number): void {
    const next = new Set(expanded)
    if (next.has(sessionId)) {
      next.delete(sessionId)
    } else {
      next.add(sessionId)
    }
    setExpanded(next)
  }

  function openEndOthers(): void {
    endOthersAction.clearError()
    setEndOthersOpen(true)
  }

  async function confirmEnd(): Promise<void> {
    if (selectedSession === undefined) {
      return
    }
    if (await endAction.run(actions.endSession(selectedSession.id))) {
      setEndingSessionId(null)
    }
  }

  async function confirmEndOthers(): Promise<void> {
    if (endableCount === 0) {
      return
    }
    if (await endOthersAction.run(actions.endOtherSessions())) {
      setEndOthersOpen(false)
    }
  }

  return (
    <section aria-label="Sessions" data-id="profile-sessions">
      <p>
        A session is a browser that signed in. Its open tabs are listed inside
        it. Ending a session takes effect at once.
      </p>
      <div className="alert alert-info small" role="note">
        The list of tabs is what is happening right now and can lag behind in a
        cluster. The list of sessions cannot: it comes from the database.
      </div>
      {sessions.length === 0 ? (
        <div className="text-body-secondary">No sessions.</div>
      ) : (
        <div className="d-flex flex-column gap-3">
          {sessions.map((session) => (
            <article
              key={session.id}
              className="card"
              data-id="profile-session-row"
            >
              <div className="card-body">
                <div className="d-flex flex-wrap align-items-start justify-content-between gap-2">
                  <div>
                    <h3 className="h6 mb-1">Session #{session.id}</h3>
                    <div data-id="profile-session-device">
                      {session.deviceName ?? 'Unknown device'}
                    </div>
                    {session.current ? (
                      <span
                        className="badge text-bg-primary me-1"
                        data-id="profile-session-this"
                      >
                        this one
                      </span>
                    ) : null}
                    {session.impersonated ? (
                      <span
                        className="badge text-bg-warning"
                        data-id="profile-session-impersonated"
                      >
                        an administrator is working as you
                      </span>
                    ) : null}
                  </div>
                  {!session.current && !session.impersonated ? (
                    <button
                      type="button"
                      className="btn btn-outline-danger btn-sm"
                      data-id="profile-session-revoke"
                      onClick={() => {
                        endAction.clearError()
                        setEndingSessionId(session.id)
                      }}
                    >
                      Revoke
                    </button>
                  ) : null}
                </div>
                <div className="small text-body-secondary mt-2">
                  created {formatProfileDateTime(session.createdAt)} · last seen{' '}
                  {session.tabs.length > 0
                    ? 'now'
                    : formatProfileDateTime(session.lastSeenAt)}{' '}
                  · expires {formatProfileDateTime(session.expiresAt)}
                </div>
                <button
                  type="button"
                  className="btn btn-link btn-sm px-0 mt-2"
                  aria-expanded={expanded.has(session.id)}
                  data-id="profile-session-tabs"
                  onClick={() => toggleTabs(session.id)}
                >
                  tabs: {session.tabs.length}
                </button>
                {expanded.has(session.id) ? (
                  <div className="mt-2">
                    {session.tabs.length === 0 ? (
                      <p className="text-body-secondary small mb-0">
                        No open tabs: the sign-in stays valid, but the browser
                        is closed right now.
                      </p>
                    ) : (
                      <ul className="list-group list-group-flush">
                        {session.tabs.map((tab) => (
                          <li
                            key={tab.acceptKey}
                            className="list-group-item px-0 d-flex flex-wrap justify-content-between gap-2"
                            data-id="profile-session-tab"
                          >
                            <code>{tab.acceptKey.slice(0, 8)}</code>
                            <span className="small text-body-secondary">
                              opened{' '}
                              {formatProfileDateTime(tab.connectedAt * 1000)}
                              {tab.current ? (
                                <span
                                  className="badge text-bg-primary ms-1"
                                  data-id="profile-session-tab-this"
                                >
                                  this tab
                                </span>
                              ) : null}
                            </span>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                ) : null}
              </div>
            </article>
          ))}
        </div>
      )}
      <button
        type="button"
        className="btn btn-outline-danger mt-3"
        disabled={endableCount === 0}
        data-id="profile-sessions-end-others"
        onClick={openEndOthers}
      >
        Sign out everywhere else
      </button>

      <HilosModal
        open={endingSessionId !== null}
        title={`End session #${endingSessionId ?? ''}`}
        initialFocus="dialog"
        onClose={() => setEndingSessionId(null)}
        actions={(args) => (
          <>
            <button
              type="button"
              className="btn btn-secondary"
              disabled={endAction.busy}
              onClick={args.requestClose}
            >
              Cancel
            </button>
            <LoadingButton
              className="btn-danger"
              loading={endAction.loading}
              disabled={selectedSession === undefined || endAction.busy}
              data-id="profile-session-end-confirm"
              onClick={() => void confirmEnd()}
            >
              End
            </LoadingButton>
          </>
        )}
      >
        <p>
          Tabs of this session lose the account at once: where an account is
          needed, the sign-in form takes the place of the content.
        </p>
        <p>Your other sessions are not touched.</p>
        <HilosFormError message={endError} dataId="profile-session-end-error" />
      </HilosModal>

      <HilosModal
        open={endOthersOpen}
        title="Sign out everywhere else"
        initialFocus="dialog"
        onClose={() => setEndOthersOpen(false)}
        actions={(args) => (
          <>
            <button
              type="button"
              className="btn btn-secondary"
              disabled={endOthersAction.busy}
              onClick={args.requestClose}
            >
              Cancel
            </button>
            <LoadingButton
              className="btn-danger"
              loading={endOthersAction.loading}
              disabled={endableCount === 0 || endOthersAction.busy}
              data-id="profile-sessions-end-others-confirm"
              onClick={() => void confirmEndOthers()}
            >
              Sign out
            </LoadingButton>
          </>
        )}
      >
        <p>
          Other sessions that will end:{' '}
          <strong data-id="profile-sessions-end-others-count">
            {endableCount}
          </strong>
          .
        </p>
        <p>
          Their tabs lose the account at once: where an account is needed, the
          sign-in form takes the place of the content.
        </p>
        <p>This session stays signed in.</p>
        <HilosFormError
          message={endOthersError}
          dataId="profile-sessions-end-others-error"
        />
      </HilosModal>
    </section>
  )
}

// framework/frontend/angular/src/profile/HilosProfileSessions.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  signal,
} from '@angular/core'
import {
  endableProfileSessionCount,
  formatProfileDateTime,
  type HilosProfileSession as ProfileSession,
  type HilosProfileSessionActions,
} from '@hilos/core'

import { HilosFormError } from '../HilosFormError.js'
import { HilosModal } from '../HilosModal.js'
import { LoadingButton } from '../LoadingButton.js'
import { createHilosTrackedAction } from '../hilosTrackedAction.js'

/** The shared session list, tab disclosure, and end-session controls. */
@Component({
  selector: 'hilos-profile-sessions',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosFormError, HilosModal, LoadingButton],
  template: `
    <section aria-label="Sessions" data-id="profile-sessions">
      <p>
        A session is a browser that signed in. Its open tabs are listed inside
        it. Ending a session takes effect at once.
      </p>
      <div class="alert alert-info small" role="note">
        The list of tabs is what is happening right now and can lag behind in a
        cluster. The list of sessions cannot: it comes from the database.
      </div>
      @if (sessions().length === 0) {
        <div class="text-body-secondary">No sessions.</div>
      } @else {
        <div class="d-flex flex-column gap-3">
          @for (session of sessions(); track session.id) {
            <article class="card" data-id="profile-session-row">
              <div class="card-body">
                <div
                  class="d-flex flex-wrap align-items-start justify-content-between gap-2"
                >
                  <div>
                    <h3 class="h6 mb-1">Session #{{ session.id }}</h3>
                    <div data-id="profile-session-device">
                      {{ session.deviceName ?? 'Unknown device' }}
                    </div>
                    @if (session.current) {
                      <span
                        class="badge text-bg-primary me-1"
                        data-id="profile-session-this"
                        >this one</span
                      >
                    }
                    @if (session.impersonated) {
                      <span
                        class="badge text-bg-warning"
                        data-id="profile-session-impersonated"
                        >an administrator is working as you</span
                      >
                    }
                  </div>
                  @if (!session.current && !session.impersonated) {
                    <button
                      type="button"
                      class="btn btn-outline-danger btn-sm"
                      data-id="profile-session-revoke"
                      (click)="openEnd(session.id)"
                    >
                      Revoke
                    </button>
                  }
                </div>
                <div class="small text-body-secondary mt-2">
                  created {{ date(session.createdAt) }} · last seen
                  {{
                    session.tabs.length > 0 ? 'now' : date(session.lastSeenAt)
                  }}
                  · expires {{ date(session.expiresAt) }}
                </div>
                <button
                  type="button"
                  class="btn btn-link btn-sm px-0 mt-2"
                  [attr.aria-expanded]="expanded().has(session.id)"
                  data-id="profile-session-tabs"
                  (click)="toggleTabs(session.id)"
                >
                  tabs: {{ session.tabs.length }}
                </button>
                @if (expanded().has(session.id)) {
                  <div class="mt-2">
                    @if (session.tabs.length === 0) {
                      <p class="text-body-secondary small mb-0">
                        No open tabs: the sign-in stays valid, but the browser
                        is closed right now.
                      </p>
                    } @else {
                      <ul class="list-group list-group-flush">
                        @for (tab of session.tabs; track tab.acceptKey) {
                          <li
                            class="list-group-item px-0 d-flex flex-wrap justify-content-between gap-2"
                            data-id="profile-session-tab"
                          >
                            <code>{{ shortKey(tab.acceptKey) }}</code>
                            <span class="small text-body-secondary">
                              opened {{ tabDate(tab.connectedAt) }}
                              @if (tab.current) {
                                <span
                                  class="badge text-bg-primary ms-1"
                                  data-id="profile-session-tab-this"
                                  >this tab</span
                                >
                              }
                            </span>
                          </li>
                        }
                      </ul>
                    }
                  </div>
                }
              </div>
            </article>
          }
        </div>
      }
      <button
        type="button"
        class="btn btn-outline-danger mt-3"
        [disabled]="endableCount() === 0"
        data-id="profile-sessions-end-others"
        (click)="openEndOthers()"
      >
        Sign out everywhere else
      </button>

      <hilos-modal
        [open]="endingSessionId() !== null"
        (openChange)="$event ? null : endingSessionId.set(null)"
        [title]="endTitle()"
        initialFocus="dialog"
      >
        <p>
          Tabs of this session lose the account at once: where an account is
          needed, the sign-in form takes the place of the content.
        </p>
        <p>Your other sessions are not touched.</p>
        <hilos-form-error
          [message]="endError()"
          dataId="profile-session-end-error"
        />
        <ng-template #modalActions let-requestClose="requestClose">
          <button
            type="button"
            class="btn btn-secondary"
            [disabled]="endAction.busy()"
            (click)="requestClose()"
          >
            Cancel
          </button>
          <button
            hilosLoadingButton
            class="btn-danger"
            [loading]="endAction.loading()"
            [disabled]="selectedSession() === undefined || endAction.busy()"
            data-id="profile-session-end-confirm"
            (click)="confirmEnd()"
          >
            End
          </button>
        </ng-template>
      </hilos-modal>

      <hilos-modal
        [open]="endOthersOpen()"
        (openChange)="$event ? null : endOthersOpen.set(false)"
        title="Sign out everywhere else"
        initialFocus="dialog"
      >
        <p>
          Other sessions that will end:
          <strong data-id="profile-sessions-end-others-count">{{
            endableCount()
          }}</strong
          >.
        </p>
        <p>
          Their tabs lose the account at once: where an account is needed, the
          sign-in form takes the place of the content.
        </p>
        <p>This session stays signed in.</p>
        <hilos-form-error
          [message]="endOthersError()"
          dataId="profile-sessions-end-others-error"
        />
        <ng-template #modalActions let-requestClose="requestClose">
          <button
            type="button"
            class="btn btn-secondary"
            [disabled]="endOthersAction.busy()"
            (click)="requestClose()"
          >
            Cancel
          </button>
          <button
            hilosLoadingButton
            class="btn-danger"
            [loading]="endOthersAction.loading()"
            [disabled]="endableCount() === 0 || endOthersAction.busy()"
            data-id="profile-sessions-end-others-confirm"
            (click)="confirmEndOthers()"
          >
            Sign out
          </button>
        </ng-template>
      </hilos-modal>
    </section>
  `,
})
export class HilosProfileSessions {
  readonly sessions = input.required<readonly ProfileSession[]>()
  readonly actions = input.required<HilosProfileSessionActions>()

  protected readonly expanded = signal<ReadonlySet<number>>(new Set())
  protected readonly endingSessionId = signal<number | null>(null)
  protected readonly endOthersOpen = signal(false)
  protected readonly endAction = createHilosTrackedAction()
  protected readonly endOthersAction = createHilosTrackedAction()
  protected readonly selectedSession = computed(() =>
    this.sessions().find((session) => session.id === this.endingSessionId()),
  )
  protected readonly endableCount = computed(() =>
    endableProfileSessionCount(this.sessions()),
  )
  protected readonly endError = computed(() =>
    this.selectedSession() === undefined
      ? 'This session has already ended'
      : this.endAction.error(),
  )
  protected readonly endOthersError = computed(() =>
    this.endableCount() === 0
      ? 'Your other sessions have already ended'
      : this.endOthersAction.error(),
  )
  protected readonly endTitle = computed(
    () => `End session #${this.endingSessionId() ?? ''}`,
  )

  protected date(value: string | null): string {
    return formatProfileDateTime(value)
  }

  protected tabDate(connectedAt: number): string {
    return formatProfileDateTime(connectedAt * 1000)
  }

  protected shortKey(acceptKey: string): string {
    return acceptKey.slice(0, 8)
  }

  protected toggleTabs(sessionId: number): void {
    const next = new Set(this.expanded())
    if (next.has(sessionId)) {
      next.delete(sessionId)
    } else {
      next.add(sessionId)
    }
    this.expanded.set(next)
  }

  protected openEnd(sessionId: number): void {
    this.endAction.clearError()
    this.endingSessionId.set(sessionId)
  }

  protected async confirmEnd(): Promise<void> {
    const session = this.selectedSession()
    if (session !== undefined) {
      if (await this.endAction.run(this.actions().endSession(session.id))) {
        this.endingSessionId.set(null)
      }
    }
  }

  protected openEndOthers(): void {
    this.endOthersAction.clearError()
    this.endOthersOpen.set(true)
  }

  protected async confirmEndOthers(): Promise<void> {
    if (this.endableCount() === 0) {
      return
    }
    if (await this.endOthersAction.run(this.actions().endOtherSessions())) {
      this.endOthersOpen.set(false)
    }
  }
}
