// framework/frontend/react/src/admin/security/HilosSecurityPage.tsx
// HilosSecurityPage — the Security admin page (HilosPages.SECURITY). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Security admin page: the framework default shell for its key. */
export function HilosSecurityPage() {
  return <HilosAdminPage page={HilosPages.SECURITY} />
}

// framework/frontend/vue/src/admin/security/HilosSecurityPage.vue
<!-- HilosSecurityPage — the Security Center admin page (HilosPages.SECURITY). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.SECURITY" />
</template>
