// framework/frontend/react/src/admin/security/HilosSecurityOauthPage.tsx
// HilosSecurityOauthPage — the Security Oauth admin page (HilosPages.SECURITY_OAUTH). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Security Oauth admin page: the framework default shell for its key. */
export function HilosSecurityOauthPage() {
  return <HilosAdminPage page={HilosPages.SECURITY_OAUTH} />
}

// framework/frontend/vue/src/admin/security/HilosSecurityOauthPage.vue
<!-- HilosSecurityOauthPage — the OAuth providers admin page (HilosPages.SECURITY_OAUTH). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.SECURITY_OAUTH" />
</template>
