// framework/frontend/react/src/admin/mcpSkills/HilosMcpSkillsMcpPage.tsx
// HilosMcpSkillsMcpPage — the Mcp Skills Mcp admin page (HilosPages.MCP_SKILLS_MCP). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Mcp Skills Mcp admin page: the framework default shell for its key. */
export function HilosMcpSkillsMcpPage() {
  return <HilosAdminPage page={HilosPages.MCP_SKILLS_MCP} />
}

// framework/frontend/angular/src/admin/mcpSkills/HilosMcpSkillsMcpPage.ts
// HilosMcpSkillsMcpPage — the Mcp Skills Mcp admin page (HilosPages.MCP_SKILLS_MCP). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by projecting content into the
// shell's slot to replace its default body. Bootstrap classes only
// (styling-rules.md).
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Mcp Skills Mcp admin page: the framework default shell for its key. */
@Component({
  selector: 'hilos-mcp-skills-mcp-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosAdminPage],
  template: `<hilos-admin-page [page]="page" />`,
})
export class HilosMcpSkillsMcpPage {
  /** The admin page key this default renders the shell for. */
  protected readonly page = HilosPages.MCP_SKILLS_MCP
}
