// framework/frontend/react/src/admin/mcpSkills/HilosMcpSkillsMcpLogsViewPage.tsx
// HilosMcpSkillsMcpLogsViewPage — the Mcp Skills Mcp Logs View admin page (HilosPages.MCP_SKILLS_MCP_LOGS_VIEW). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Mcp Skills Mcp Logs View admin page: the framework default shell for its key. */
export function HilosMcpSkillsMcpLogsViewPage() {
  return <HilosAdminPage page={HilosPages.MCP_SKILLS_MCP_LOGS_VIEW} />
}

// framework/frontend/angular/src/admin/mcpSkills/HilosMcpSkillsMcpLogsViewPage.ts
// HilosMcpSkillsMcpLogsViewPage — the Mcp Skills Mcp Logs View admin page (HilosPages.MCP_SKILLS_MCP_LOGS_VIEW). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by projecting content into the
// shell's slot to replace its default body. Bootstrap classes only
// (styling-rules.md).
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Mcp Skills Mcp Logs View admin page: the framework default shell for its key. */
@Component({
  selector: 'hilos-mcp-skills-mcp-logs-view-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosAdminPage],
  template: `<hilos-admin-page [page]="page" />`,
})
export class HilosMcpSkillsMcpLogsViewPage {
  /** The admin page key this default renders the shell for. */
  protected readonly page = HilosPages.MCP_SKILLS_MCP_LOGS_VIEW
}
