// demo/simple-todo/frontend/src/views/Licence/Licence.tsx
// The public Licence page (HilosPages.LICENCE). A framework-declared static
// page; this project supplies the content. See views/About/About.tsx.
import { HilosStaticPage } from '@hilos/react'

export default function Licence() {
  return (
    <HilosStaticPage title="Licence">
      <p>The Hilos framework is released under the MIT licence.</p>
      <p>
        Permission is hereby granted, free of charge, to any person obtaining a
        copy of this software and associated documentation files, to deal in the
        software without restriction — including the rights to use, copy, modify,
        merge, publish, distribute, sublicense, and/or sell copies of it.
      </p>
      <p className="mb-0">
        The software is provided “as is”, without warranty of any kind.
      </p>
    </HilosStaticPage>
  )
}

// demo/chat/frontend/src/views/Licence/Licence.vue
<!-- The public Licence page (HilosPages.LICENCE). A framework-declared static
page; this project supplies the content. See views/About/About.vue. -->
<script setup lang="ts">
import { HilosStaticPage } from '@hilos/vue'
</script>

<template>
  <HilosStaticPage title="Licence">
    <p>The Hilos framework is released under the MIT licence.</p>
    <p>
      Permission is hereby granted, free of charge, to any person obtaining a
      copy of this software and associated documentation files, to deal in the
      software without restriction — including the rights to use, copy, modify,
      merge, publish, distribute, sublicense, and/or sell copies of it.
    </p>
    <p class="mb-0">
      The software is provided “as is”, without warranty of any kind.
    </p>
  </HilosStaticPage>
</template>
