// framework/frontend/codestyle/fixtures/shellParity/parity/framework/frontend/react/src/Widget.tsx
export function Widget() {
  return (
    <>
      <div data-id="shared-static" />
      <div data-id={`shared-dynamic-${row.id}`} />
      <div data-id={`shared-long-${row.id}`} />
      <div data-id={dataId} />
      <div data-id={`${dataId}-slot`} />
      <HilosChild dataId="shared-prop" />
      <HilosChild dataId={`shared-prop-dynamic-${row.id}`} />
    </>
  )
}

// framework/frontend/codestyle/fixtures/shellParity/parity/framework/frontend/angular/src/Widget.ts
import { Component } from '@angular/core'

@Component({
  template: `
    <div data-id="shared-static"></div>
    <div [attr.data-id]="'shared-dynamic-' + row.id"></div>
    <div [attr.data-id]="'shared-long-' + row.id"></div>
    <div [attr.data-id]="dataId"></div>
    <div [attr.data-id]="dataId + '-slot'"></div>
  `,
})
export class Widget {}
