// framework/frontend/react/src/admin/billing/HilosBillingPaymentsPage.tsx
// HilosBillingPaymentsPage — the Billing Payments admin page (HilosPages.BILLING_PAYMENTS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Billing Payments admin page: the framework default shell for its key. */
export function HilosBillingPaymentsPage() {
  return <HilosAdminPage page={HilosPages.BILLING_PAYMENTS} />
}

// framework/frontend/angular/src/admin/billing/HilosBillingPaymentsPage.ts
// HilosBillingPaymentsPage — the Billing Payments admin page (HilosPages.BILLING_PAYMENTS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by projecting content into the
// shell's slot to replace its default body. Bootstrap classes only
// (styling-rules.md).
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Billing Payments admin page: the framework default shell for its key. */
@Component({
  selector: 'hilos-billing-payments-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HilosAdminPage],
  template: `<hilos-admin-page [page]="page" />`,
})
export class HilosBillingPaymentsPage {
  /** The admin page key this default renders the shell for. */
  protected readonly page = HilosPages.BILLING_PAYMENTS
}
