// framework/frontend/react/src/admin/i18n/details/HilosI18nActionPage.tsx
// HilosI18nActionPage — the I18n Action admin page (HilosPages.I18N_ACTION). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../../HilosAdminPage.js'

/** The I18n Action admin page: the framework default shell for its key. */
export function HilosI18nActionPage() {
  return <HilosAdminPage page={HilosPages.I18N_ACTION} />
}

// framework/frontend/vue/src/admin/i18n/details/HilosI18nActionPage.vue
<!-- HilosI18nActionPage — the Action admin page (HilosPages.I18N_ACTION). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.I18N_ACTION" />
</template>
