// framework/frontend/vue/src/admin/changeLog/HilosChangeLogTablesPage.vue
<!-- HilosChangeLogTablesPage — the Tracked tables admin page (HilosPages.CHANGE_LOG_TABLES). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.CHANGE_LOG_TABLES" />
</template>

// framework/frontend/react/src/admin/changeLog/HilosChangeLogTablesPage.tsx
// HilosChangeLogTablesPage — the Change Log Tables admin page (HilosPages.CHANGE_LOG_TABLES). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Change Log Tables admin page: the framework default shell for its key. */
export function HilosChangeLogTablesPage() {
  return <HilosAdminPage page={HilosPages.CHANGE_LOG_TABLES} />
}
