// framework/frontend/vue/src/admin/mcpSkills/HilosMcpSkillsMcpLogsPage.vue
<!-- HilosMcpSkillsMcpLogsPage — the Usage logs admin page (HilosPages.MCP_SKILLS_MCP_LOGS). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.MCP_SKILLS_MCP_LOGS" />
</template>

// framework/frontend/react/src/admin/mcpSkills/HilosMcpSkillsMcpLogsPage.tsx
// HilosMcpSkillsMcpLogsPage — the Mcp Skills Mcp Logs admin page (HilosPages.MCP_SKILLS_MCP_LOGS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Mcp Skills Mcp Logs admin page: the framework default shell for its key. */
export function HilosMcpSkillsMcpLogsPage() {
  return <HilosAdminPage page={HilosPages.MCP_SKILLS_MCP_LOGS} />
}
