// framework/frontend/react/src/HilosLayout.tsx
// HilosLayout — the tier-1 application shell (sdk-packaging.md): a slot-first
// app frame a project fills rather than re-implements. React has no named
// slots, so the brand and nav regions are node props and the routed page
// content is children. It renders the top navigation bar carrying the brand and
// nav, the framework admin entry (the gear linking to the Hilos dashboard), the
// live connection indicator the SDK owns (core-and-connection.md), and, last,
// its tracked sign-out control while a person stands behind the session;
// a full-width banner region below the nav carrying the framework's own
// protected-mode strip, its impersonation strip (drawn from the session, with a
// Stop that waits for the server's answer), and the app-wide status strip a
// project fills (e.g. a trial notice) through the banner prop — one live region
// for all, empty and zero-height while none is up — the content, and a footer
// of the public framework pages (HILOS_FOOTER_LINKS). The shell is a
// fixed-height viewport column (vh-100): the nav, banner, and footer never
// scroll (flex-shrink-0) and the main region grows and scrolls its own overflow
// (min-h-0 + overflow-auto), so a page either scrolls inside main or — like the
// chat page — fills it and scrolls an inner region rather than the whole
// document. The brand, the gear, and the footer links are HilosLinks —
// no-refresh navigation that leaves the socket alive — so the shell alone moves
// between the project home, the admin section, and the public pages. While the
// connection reports protected mode the shell becomes the maintenance surface
// (HilosMaintenance) and keeps only the connection indicator — every other
// region of the shell links to a page the freeze has shut. On the very first
// frame there is nothing to report yet, and on a browser that has met
// maintenance here the core holds that frame back (HIL-613): the shell then
// renders only the hidden hilos-boot-state marker, so a reload into a frozen
// node never flashes the ordinary layout. While the session holds a blocked
// account the routed content gives way to the "Access closed" card
// (HilosAccountBlocked, HIL-289) — the header and footer stay, maintenance
// still comes first. Styling is Bootstrap classes only and
// the shell carries no CSS of its own (styling-rules.md); the status and admin
// icons are Bootstrap Icons (`bi-*`), shipped with the view layer
// (src/index.ts) like Bootstrap.
import type {
  ConnectionState,
  HilosConnection,
  PageRouteMatch,
} from '@hilos/core'
import {
  HILOS_FOOTER_LINKS,
  HILOS_PAGE_ROUTES,
  HilosPages,
  createSignal,
  hilosAccountBlocked,
  hilosImpersonation,
  hilosSignedIn,
  IMPERSONATION_STRIP_COPY,
  protectedModeBannerCopy,
  RECONNECT_DRAGGING_COPY,
  rtStalenessLabel,
  signOut,
  SIGN_OUT_COPY,
  stopImpersonation,
} from '@hilos/core'
import { useContext, useEffect } from 'react'
import type { ReactNode } from 'react'

import { HilosAccountBlocked } from './HilosAccountBlocked.js'
import { HilosLink } from './HilosLink.js'
import { HilosMaintenance } from './HilosMaintenance.js'
import { LoadingButton } from './LoadingButton.js'
import { HilosToastHost } from './HilosToastHost.js'
import type { HilosToastCorner } from './hilosToastCorner.js'
import { HilosOAuthWaitModal } from './auth/HilosOAuthWaitModal.js'
import { HilosRouterContext } from './hilosRouterContext.js'
import { useConnectionState } from './useConnectionState.js'
import { useFirstFrameHold } from './useFirstFrameHold.js'
import { useProtectedMode } from './useProtectedMode.js'
import { useReconnectDragging } from './useReconnectDragging.js'
import { useRtStaleness } from './useRtStaleness.js'
import { useSignal } from './useSignal.js'
import { useTrackedAction } from './useTrackedAction.js'

/** Props for {@link HilosLayout}. */
export interface HilosLayoutProps {
  /** The connection whose live state the shell indicator mirrors. */
  connection: HilosConnection
  /**
   * Whether the signed-in user holds the admin privilege. The admin entry is
   * drawn for an admin and for nobody else, so a project that answers no admin
   * identity (the default) shows no way into a surface the gate would refuse.
   */
  isAdmin?: boolean
  /**
   * Which corner the toast stack sits in; the bottom end by default. A project
   * chooses it once here and never per notice: different corners in different
   * sections of one product is a reliable way to make the notices stop being
   * noticed (toasts.md).
   */
  toastCorner?: HilosToastCorner
  /** The home-linked brand region content. Defaults to `Hilos`. */
  brand?: ReactNode
  /** The navigation region placed next to the brand. */
  nav?: ReactNode
  /**
   * The right-aligned user region placed before the admin gear (the Vue shell's
   * `#user` slot): the profile link, the notification bell, a guest's Sign in.
   * Additive — omit it and the shell still draws its own sign-out control last.
   */
  user?: ReactNode
  /**
   * The app-wide status strip a project draws in the banner region below the
   * nav (the Vue shell's `#banner` slot), under the framework's own strips: a
   * trial notice. Optional — omit it and the region carries only those.
   */
  banner?: ReactNode
  /** The routed page content rendered in the shell body. */
  children?: ReactNode
}

// Each transport state maps to a Bootstrap Icon and a Bootstrap text color:
// green while the socket is live and green on a first connect too — the person
// has only just opened the page and nothing has broken yet, so a warning color
// there would invent a problem (HIL-831) — amber once a live link has dropped
// and is being repaired, red when it is down. `connecting` and `reconnecting`
// share the in-progress icon, and what distinguishes them is the color and the
// visually-hidden label.
type ConnVisual = { icon: string; color: string }
const CONN_VISUAL: Record<ConnectionState, ConnVisual> = {
  connected: { icon: 'bi-check-circle-fill', color: 'text-success' },
  connecting: { icon: 'bi-arrow-repeat', color: 'text-success' },
  reconnecting: { icon: 'bi-arrow-repeat', color: 'text-warning' },
  disconnected: { icon: 'bi-exclamation-triangle-fill', color: 'text-danger' },
}

// The gear targets the framework's own dashboard page; its URL is owned by the
// framework page catalog, not restated here as a literal (routing/hilosPages).
const ADMIN_HREF = HILOS_PAGE_ROUTES[HilosPages.DASHBOARD]

// A stable empty fallback so useSignal always has a real signal without a router
// (tests, the hard-link fallback); the page title then stays empty.
const NO_TITLE = createSignal('')

// The same for the route: without a router there is no route and therefore no
// administrative surface, so the maintenance surface hides the verifier's code
// field. That is the safe way round — a missing field is fixed by typing the
// admin url, a field shown where it should not be is the defect this closes.
const NO_ROUTE = createSignal<PageRouteMatch>({
  page: '',
  params: {},
  admin: false,
})

/**
 * The application shell: top navigation with the brand, the admin gear, the
 * live connection indicator, and the routed page content.
 *
 * @param props The connection plus the brand, nav, and content regions.
 */
export function HilosLayout({
  connection,
  isAdmin = false,
  toastCorner,
  brand = 'Hilos',
  nav,
  user,
  banner,
  children,
}: HilosLayoutProps) {
  const connectionState = useConnectionState(connection)
  const visual = CONN_VISUAL[connectionState]

  // While the backend holds the node in protected mode the shell shows the
  // maintenance surface instead of the routed page, and drops everything that
  // leads anywhere: the brand, the nav, the user region, the admin gear, and
  // the footer all point at pages the freeze has shut. The connection indicator
  // is the one thing that stays — during planned work it is the only status
  // worth telling the visitor. The state is read from the connection, not from
  // a page store, so it outlives routing and subscription lifecycles.
  const protectedMode = useProtectedMode(connection)
  const underMaintenance = protectedMode.active

  // The opposite side of the same state: whoever the mode does NOT hold, while
  // it still holds the node, is inside a system that is closed to everybody else
  // and looks exactly like an open one. The banner is what says so, and it comes
  // from the connection for the same reason the surface does - navigation, a
  // reconnect, an F5 and a second tab all learn it from the frame rather than
  // from a store that would have to be rebuilt on each of them.
  const verificationBanner = protectedModeBannerCopy(protectedMode)

  // The second framework strip (HIL-1064): the session says an administrator
  // stands behind it, so the person is told whom they are acting as and given
  // the way back. It is the shell's and reads the core store bootHilos binds -
  // no project input. Stop is a tracked action with the driver's defaults: busy
  // disables it at once, a refusal is the error toast and leaves the strip
  // standing, and success needs no toast - the strip leaves by itself with the
  // identity the answer rides behind. Below the protected-mode strip because
  // what is about the node comes before what is about the session.
  const impersonation = useSignal(hilosImpersonation)
  const impersonationStop = useTrackedAction()
  // The "Access closed" card (HIL-289): the session lost its account to a
  // block, so the content gives way to the card on every url - the header and
  // the footer stay, and whatever the content held, modals included, goes with
  // it. Under the maintenance surface rather than over it: what is about the
  // node comes first.
  const accountBlocked = useSignal(hilosAccountBlocked)
  const onImpersonationStop = (): void => {
    if (impersonationStop.busy) {
      return
    }
    void impersonationStop.run(stopImpersonation())
  }

  const signedIn = useSignal(hilosSignedIn)
  const signOutAction = useTrackedAction()
  const onSignOut = (): void => {
    if (signOutAction.busy) {
      return
    }
    void signOutAction.run(signOut())
  }

  // A live socket that is nonetheless showing part of a frozen replica
  // (HIL-711): the same green, with a snowflake instead of the tick. It replaces
  // the icon rather than standing beside it because the question is one — how
  // much of what you see can be trusted — and two marks would read as two
  // problems. Only while the socket is up: while it is down the transport itself
  // is the news, and a stale copy is the least of what is out of date.
  const staleness = useRtStaleness(connection)
  const stalenessLabel = rtStalenessLabel(staleness)
  const showsFrozenData = connectionState === 'connected' && staleness.stale
  const connIcon = showsFrozenData ? 'bi-snow' : visual.icon

  // A repair that has been running long enough for the backoff pauses to have
  // reached their ceiling (HIL-831): the same amber arrows, with a small red
  // triangle over their corner. An overlay rather than a replacement, because it
  // is the same process — merely longer than expected. Only while reconnecting:
  // on a first connect nothing has been repairing.
  const reconnectDragging = useReconnectDragging(connection)
  const showsDraggingRepair =
    connectionState === 'reconnecting' && reconnectDragging
  const connLabel =
    showsFrozenData && stalenessLabel !== undefined
      ? `${connectionState} - ${stalenessLabel}`
      : showsDraggingRepair
        ? `${connectionState} - ${RECONNECT_DRAGGING_COPY.dragging}`
        : connectionState

  // Before any of that can be read there is a frame where nothing has been
  // announced yet, and drawing the ordinary shell in it is what makes a reload
  // into a frozen node flash (HIL-613). On a browser that has met maintenance
  // here the core holds that frame back until the welcome lands, and the shell
  // draws nothing at all in the meantime — not a spinner, not a placeholder: the
  // wait is measured in the time one frame takes, and anything drawn in it is a
  // second flash replacing the first.
  const firstFrameHeld = useFirstFrameHold(connection)

  // Mirror the navigator's current page title: set it as the document title so
  // the browser tab tracks the no-refresh navigation, and render it in the live
  // region below so a screen reader announces the page change (WCAG 2.4.2).
  // Without a router (tests, the hard-link fallback) the title stays empty.
  const router = useContext(HilosRouterContext)
  const pageTitle = useSignal(router?.currentTitle ?? NO_TITLE)
  const currentRoute = useSignal(router?.currentRoute ?? NO_ROUTE)
  useEffect(() => {
    if (pageTitle) {
      document.title = pageTitle
    }
  }, [pageTitle])

  return (
    <>
      {/* The one place the two boot outcomes are named, on the marker a test
      waits for rather than polling for chrome that is absent by design while
      held. */}
      <div
        data-id="hilos-boot-state"
        data-state={firstFrameHeld ? 'held' : 'ready'}
        hidden
      />
      {!firstFrameHeld && (
        <div
          className="d-flex flex-column vh-100 overflow-hidden"
          data-id="app-root"
        >
          <a
            href="#hilos-main-content"
            className="visually-hidden-focusable position-absolute top-0 start-0 m-2 btn btn-primary btn-sm z-3"
            data-id="skip-to-content"
          >
            Skip to main content
          </a>
          <div
            className="visually-hidden"
            role="status"
            aria-live="polite"
            data-id="page-title"
          >
            {pageTitle}
          </div>
          <nav
            className="navbar navbar-expand bg-body-tertiary border-bottom flex-shrink-0"
            aria-label="Main"
          >
            <div className="container">
              {!underMaintenance && (
                <HilosLink
                  to="/"
                  className="navbar-brand mb-0 h1"
                  data-id="nav-brand"
                >
                  {brand}
                </HilosLink>
              )}
              {/* The auto margin lives on this region whether or not it holds
              links, so the connection indicator keeps its place on the right
              while the maintenance surface is up. */}
              <div className="navbar-nav me-auto">
                {underMaintenance ? null : nav}
              </div>
              <div className="d-flex align-items-center gap-3">
                {!underMaintenance && (
                  <>
                    {user}
                    {isAdmin ? (
                      <HilosLink
                        className="nav-link d-inline-flex align-items-center p-0 fs-5"
                        to={ADMIN_HREF}
                        data-id="nav-admin"
                        aria-label="Hilos dashboard"
                      >
                        <i className="bi bi-gear-fill" aria-hidden="true" />
                        <span className="visually-hidden">Hilos dashboard</span>
                      </HilosLink>
                    ) : null}
                  </>
                )}
                <span
                  className={`navbar-text d-inline-flex align-items-center fs-5 ${visual.color}`}
                  data-id="conn-state"
                  role="status"
                  aria-live="polite"
                  title={connLabel}
                >
                  <span className="position-relative d-inline-flex">
                    <i className={`bi ${connIcon}`} aria-hidden="true" />
                    {showsDraggingRepair && (
                      <i
                        className="bi bi-exclamation-triangle-fill text-danger position-absolute hilos-conn-dragging-mark"
                        aria-hidden="true"
                      />
                    )}
                  </span>
                  <span className="visually-hidden">{connLabel}</span>
                </span>
                {!underMaintenance && signedIn && (
                  <LoadingButton
                    className="btn-link nav-link d-inline-flex align-items-center p-0 fs-5"
                    data-id="nav-logout"
                    aria-label={SIGN_OUT_COPY.label}
                    title={SIGN_OUT_COPY.label}
                    loading={signOutAction.busy}
                    onClick={onSignOut}
                  >
                    <i className="bi bi-box-arrow-right" aria-hidden="true" />
                  </LoadingButton>
                )}
              </div>
            </div>
          </nav>
          <div
            className="flex-shrink-0"
            role="status"
            aria-live="polite"
            data-id="app-banner"
          >
            {verificationBanner !== undefined && (
              <div
                className="alert alert-warning border-0 rounded-0 mb-0 py-2"
                data-id="protected-mode-banner"
              >
                <div className="container d-flex flex-wrap align-items-center justify-content-center gap-3">
                  <span>
                    <i
                      className="bi bi-shield-exclamation me-1"
                      aria-hidden="true"
                    ></i>{' '}
                    {verificationBanner}
                  </span>
                </div>
              </div>
            )}
            {impersonation !== null && !underMaintenance && (
              <div
                className="alert alert-warning border-0 rounded-0 mb-0 py-2"
                data-id="impersonation-banner"
              >
                <div className="container d-flex flex-wrap align-items-center justify-content-center gap-3">
                  <span>
                    <i
                      className="bi bi-people-fill me-1"
                      aria-hidden="true"
                    ></i>{' '}
                    {IMPERSONATION_STRIP_COPY.lead}{' '}
                    <strong>{impersonation.userName}</strong>
                  </span>
                  <LoadingButton
                    className="btn-sm btn-outline-dark"
                    data-id="impersonation-stop"
                    loading={impersonationStop.busy}
                    onClick={onImpersonationStop}
                  >
                    {IMPERSONATION_STRIP_COPY.stop}
                  </LoadingButton>
                </div>
              </div>
            )}
            {banner}
          </div>
          <main
            id="hilos-main-content"
            tabIndex={-1}
            className={`container flex-grow-1 min-h-0 overflow-auto py-4${
              underMaintenance ? ' d-flex flex-column' : ''
            }`}
          >
            {underMaintenance ? (
              <HilosMaintenance
                status={protectedMode}
                connection={connection}
                adminSurface={currentRoute.admin}
              />
            ) : accountBlocked !== null ? (
              <HilosAccountBlocked notice={accountBlocked} />
            ) : (
              children
            )}
          </main>
          {!underMaintenance && (
            <footer
              className="footer flex-shrink-0 border-top bg-body-tertiary py-2"
              data-id="app-footer"
            >
              <div className="container d-flex flex-wrap justify-content-center gap-3 small">
                {HILOS_FOOTER_LINKS.map((link) => (
                  <HilosLink
                    key={link.page}
                    className="link-secondary text-decoration-none"
                    to={HILOS_PAGE_ROUTES[link.page] ?? '/'}
                    data-id={`footer-link-${link.page}`}
                  >
                    {link.label}
                  </HilosLink>
                ))}
              </div>
            </footer>
          )}
          {/* Transient notices float over the shell, so every page inside it
          can report an outcome without owning a notification surface of its
          own. */}
          <HilosToastHost corner={toastCorner} />
          {/* An OAuth trip runs in another window over whatever page started
          it, so the wait belongs to the shell too: the page underneath stays
          subscribed and alive, and no project mounts anything (HIL-633). */}
          <HilosOAuthWaitModal />
        </div>
      )}
    </>
  )
}

// framework/frontend/vue/src/HilosLayout.vue
<!-- HilosLayout — the tier-1 application shell (sdk-packaging.md): a slot-first
app frame a project fills rather than re-implements. It renders the top
navigation bar carrying the project's brand, nav, and user slots, the framework admin
entry (the gear linking to the Hilos dashboard), the live connection indicator
the SDK owns (core-and-connection.md), and, last, its tracked sign-out control
while a person stands behind the session; a full-width banner region below the nav
carrying the framework's own protected-mode strip, its
impersonation strip (drawn from the session, with a Stop that waits for the
server's answer), and the app-wide status strip a project fills (e.g. a trial
notice) through the #banner slot — one live region for all, empty and
zero-height while none is up — the
routed page content in the default slot, and a footer of the public framework pages
(HILOS_FOOTER_LINKS). The shell is a fixed-height viewport column (vh-100): the
nav, banner, and footer never scroll (flex-shrink-0) and the main region grows
and scrolls its own overflow (min-h-0 + overflow-auto), so a page either scrolls
inside main or — like the chat page — fills it and scrolls an inner region rather
than the whole document.
The brand, the gear, and the footer links are HilosLinks — no-refresh navigation
that leaves the socket alive — so the shell alone moves between the project home,
the admin section, and the public pages. While the connection reports protected
mode the shell becomes the maintenance surface (HilosMaintenance) and keeps only
the connection indicator — every other region of the shell links to a page the
freeze has shut. On the very first frame there is nothing to report yet, and on a
browser that has met maintenance here the core holds that frame back (HIL-613):
the shell then renders only the hidden hilos-boot-state marker, so a reload into a
frozen node never flashes the ordinary layout. While the session holds a blocked
account the routed content gives way to the "Access closed" card
(HilosAccountBlocked, HIL-289) — the header and footer stay, maintenance still
comes first. Styling is Bootstrap classes only
and the shell carries no CSS of its own (styling-rules.md); the status and admin
icons are Bootstrap Icons (`bi-*`), shipped with the view layer (src/index.ts)
like Bootstrap. -->
<script setup lang="ts">
import type { ConnectionState, HilosConnection } from '@hilos/core'
import {
  HILOS_FOOTER_LINKS,
  HILOS_PAGE_ROUTES,
  HilosPages,
  hilosAccountBlocked,
  hilosImpersonation,
  hilosSignedIn,
  IMPERSONATION_STRIP_COPY,
  protectedModeBannerCopy,
  RECONNECT_DRAGGING_COPY,
  rtStalenessLabel,
  signOut,
  SIGN_OUT_COPY,
  stopImpersonation,
} from '@hilos/core'
import { computed, inject, watch } from 'vue'

import HilosAccountBlocked from './HilosAccountBlocked.vue'
import HilosLink from './HilosLink.vue'
import LoadingButton from './LoadingButton.vue'
import HilosMaintenance from './HilosMaintenance.vue'
import HilosToastHost from './HilosToastHost.vue'
import type { HilosToastCorner } from './hilosToastCorner.js'
import HilosOAuthWaitModal from './auth/HilosOAuthWaitModal.vue'
import { hilosRouterKey } from './hilosRouterKey.js'
import { useConnectionState } from './useConnectionState.js'
import { useFirstFrameHold } from './useFirstFrameHold.js'
import { useProtectedMode } from './useProtectedMode.js'
import { useReconnectDragging } from './useReconnectDragging.js'
import { useRtStaleness } from './useRtStaleness.js'
import { useSignal } from './useSignal.js'
import { useTrackedAction } from './useTrackedAction.js'

const props = defineProps<{
  connection: HilosConnection
  /**
   * Whether the signed-in user holds the admin privilege. The admin entry is
   * drawn for an admin and for nobody else, so a project that answers no admin
   * identity (the default) shows no way into a surface the gate would refuse.
   */
  isAdmin?: boolean
  /**
   * Which corner the toast stack sits in; the bottom end by default. A project
   * chooses it once here and never per notice: different corners in different
   * sections of one product is a reliable way to make the notices stop being
   * noticed (toasts.md).
   */
  toastCorner?: HilosToastCorner
}>()

const connectionState = useConnectionState(props.connection)

// While the backend holds the node in protected mode the shell shows the
// maintenance surface instead of the routed page, and drops everything that
// leads anywhere: the brand, the nav, the user region, the admin gear, and the
// footer all point at pages the freeze has shut. The connection indicator is
// the one thing that stays — during planned work it is the only status worth
// telling the visitor. The state is read from the connection, not from a page
// store, so it outlives routing and subscription lifecycles.
const protectedMode = useProtectedMode(props.connection)
const underMaintenance = computed(() => protectedMode.value.active)

// The opposite side of the same state: whoever the mode does NOT hold, while it
// still holds the node, is inside a system that is closed to everybody else and
// looks exactly like an open one. The banner is what says so, and it comes from
// the connection for the same reason the surface does - navigation, a reconnect,
// an F5 and a second tab all learn it from the frame rather than from a store
// that would have to be rebuilt on each of them. It is drawn above the project's
// own banner slot: the SDK speaks first.
const verificationBanner = computed(() =>
  protectedModeBannerCopy(protectedMode.value),
)

// The second framework strip (HIL-1064): the session says an administrator
// stands behind it, so the person is told whom they are acting as and given the
// way back. It is the shell's and reads the core store bootHilos binds - no
// project input. Stop is a tracked action with the driver's defaults: busy
// disables it at once, a refusal is the error toast and leaves the strip
// standing, and success needs no toast - the strip leaves by itself with the
// identity the answer rides behind. Below the protected-mode strip because what
// is about the node comes before what is about the session.
const impersonation = useSignal(hilosImpersonation)

// The "Access closed" card (HIL-289): the session lost its account to a block,
// so the content gives way to the card on every url - the header and the footer
// stay, and whatever the content held, modals included, goes with it. Under the
// maintenance surface rather than over it: what is about the node comes first.
const accountBlocked = useSignal(hilosAccountBlocked)
const { busy: impersonationStopBusy, run: runImpersonationStop } =
  useTrackedAction()
const onImpersonationStop = (): void => {
  if (impersonationStopBusy.value) {
    return
  }
  void runImpersonationStop(stopImpersonation())
}

const signedIn = useSignal(hilosSignedIn)
const { busy: signOutBusy, run: runSignOut } = useTrackedAction()
const onSignOut = (): void => {
  if (signOutBusy.value) {
    return
  }
  void runSignOut(signOut())
}

// Before any of that can be read there is a frame where nothing has been
// announced yet, and drawing the ordinary shell in it is what makes a reload
// into a frozen node flash (HIL-613). On a browser that has met maintenance
// here the core holds that frame back until the welcome lands, and the shell
// draws nothing at all in the meantime — not a spinner, not a placeholder: the
// wait is measured in the time one frame takes, and anything drawn in it is a
// second flash replacing the first.
const firstFrameHeld = useFirstFrameHold(props.connection)
// The one place the two boot outcomes are named, on the marker a test waits for
// rather than polling for chrome that is absent by design while held.
const bootState = computed(() => (firstFrameHeld.value ? 'held' : 'ready'))

// Mirror the navigator's current page title: set it as the document title so the
// browser tab tracks the no-refresh navigation, and render it in the live region
// below so a screen reader announces the page change (WCAG 2.4.2). Without a
// router (tests, the hard-link fallback) there is no title to track.
const router = inject(hilosRouterKey, undefined)
const pageTitle = router ? useSignal(router.currentTitle) : undefined

// The maintenance surface shows the verifier's code field only on an
// administrative url, so the shell hands the route's surface type down to it.
// Without a router there is no route and therefore no administrative surface
// (tests, the hard-link fallback): the field then hides, which is the safe way
// round — a missing field is fixed by typing the admin url, a field shown where
// it should not be is the defect this closes.
const currentRoute = router ? useSignal(router.currentRoute) : undefined
watch(
  () => pageTitle?.value,
  (title) => {
    if (title) {
      document.title = title
    }
  },
  { immediate: true },
)

// Each transport state maps to a Bootstrap Icon and a Bootstrap text color:
// green while the socket is live and green on a first connect too — the person
// has only just opened the page and nothing has broken yet, so a warning color
// there would invent a problem (HIL-831) — amber once a live link has dropped
// and is being repaired, red when it is down. `connecting` and `reconnecting`
// share the in-progress icon, and what distinguishes them is the color and the
// visually-hidden label.
type ConnVisual = { icon: string; color: string }
const CONN_VISUAL: Record<ConnectionState, ConnVisual> = {
  connected: { icon: 'bi-check-circle-fill', color: 'text-success' },
  connecting: { icon: 'bi-arrow-repeat', color: 'text-success' },
  reconnecting: { icon: 'bi-arrow-repeat', color: 'text-warning' },
  disconnected: { icon: 'bi-exclamation-triangle-fill', color: 'text-danger' },
}
const connVisual = computed(() => CONN_VISUAL[connectionState.value])

// A live socket that is nonetheless showing part of a frozen replica (HIL-711):
// the same green, with a snowflake instead of the tick. It replaces the icon
// rather than standing beside it because the question is one — how much of what
// you see can be trusted — and two marks would read as two problems. Only while
// the socket is up: while it is down the transport itself is the news, and a
// stale copy is the least of what is out of date.
const staleness = useRtStaleness(props.connection)
const stalenessLabel = computed(() => rtStalenessLabel(staleness.value))
const showsFrozenData = computed(
  () => connectionState.value === 'connected' && staleness.value.stale,
)
const connIcon = computed(() =>
  showsFrozenData.value ? 'bi-snow' : connVisual.value.icon,
)
// A repair that has been running long enough for the backoff pauses to have
// reached their ceiling (HIL-831): the same amber arrows, with a small red
// triangle over their corner. An overlay rather than a replacement, because it
// is the same process — merely longer than expected. Only while reconnecting:
// on a first connect nothing has been repairing.
const reconnectDragging = useReconnectDragging(props.connection)
const showsDraggingRepair = computed(
  () => connectionState.value === 'reconnecting' && reconnectDragging.value,
)
const connLabel = computed(() => {
  if (showsFrozenData.value && stalenessLabel.value !== undefined) {
    return `${connectionState.value} - ${stalenessLabel.value}`
  }
  if (showsDraggingRepair.value) {
    return `${connectionState.value} - ${RECONNECT_DRAGGING_COPY.dragging}`
  }
  return connectionState.value
})

// The gear targets the framework's own dashboard page; its URL is owned by the
// framework page catalog, not restated here as a literal (routing/hilosPages).
const adminHref = HILOS_PAGE_ROUTES[HilosPages.DASHBOARD]

// The footer's public framework pages and their hrefs are owned by the
// framework (routing/hilosPages), so every project's footer offers the same
// links and a project supplies only each page's content component.
const footerLinks = HILOS_FOOTER_LINKS
const footerHref = (page: string): string => HILOS_PAGE_ROUTES[page] ?? '/'
</script>

<template>
  <div data-id="hilos-boot-state" :data-state="bootState" hidden />
  <div
    v-if="!firstFrameHeld"
    class="d-flex flex-column vh-100 overflow-hidden"
    data-id="app-root"
  >
    <a
      href="#hilos-main-content"
      class="visually-hidden-focusable position-absolute top-0 start-0 m-2 btn btn-primary btn-sm z-3"
      data-id="skip-to-content"
    >
      Skip to main content
    </a>
    <div
      class="visually-hidden"
      role="status"
      aria-live="polite"
      data-id="page-title"
    >
      {{ pageTitle }}
    </div>
    <nav
      class="navbar navbar-expand bg-body-tertiary border-bottom flex-shrink-0"
      aria-label="Main"
    >
      <div class="container">
        <HilosLink
          v-if="!underMaintenance"
          to="/"
          class="navbar-brand mb-0 h1"
          data-id="nav-brand"
        >
          <slot name="brand">Hilos</slot>
        </HilosLink>
        <!-- The auto margin lives on this region whether or not it holds links,
        so the connection indicator keeps its place on the right while the
        maintenance surface is up. -->
        <div class="navbar-nav me-auto">
          <template v-if="!underMaintenance">
            <slot name="nav" />
          </template>
        </div>
        <div class="d-flex align-items-center gap-3">
          <template v-if="!underMaintenance">
            <slot name="user" />
            <HilosLink
              v-if="props.isAdmin"
              class="nav-link d-inline-flex align-items-center p-0 fs-5"
              :to="adminHref"
              data-id="nav-admin"
              aria-label="Hilos dashboard"
            >
              <i class="bi bi-gear-fill" aria-hidden="true"></i>
              <span class="visually-hidden">Hilos dashboard</span>
            </HilosLink>
          </template>
          <span
            class="navbar-text d-inline-flex align-items-center fs-5"
            :class="connVisual.color"
            data-id="conn-state"
            role="status"
            aria-live="polite"
            :title="connLabel"
          >
            <span class="position-relative d-inline-flex">
              <i class="bi" :class="connIcon" aria-hidden="true"></i>
              <i
                v-if="showsDraggingRepair"
                class="bi bi-exclamation-triangle-fill text-danger position-absolute hilos-conn-dragging-mark"
                aria-hidden="true"
              ></i>
            </span>
            <span class="visually-hidden">{{ connLabel }}</span>
          </span>
          <LoadingButton
            v-if="!underMaintenance && signedIn"
            class="btn-link nav-link d-inline-flex align-items-center p-0 fs-5"
            data-id="nav-logout"
            :aria-label="SIGN_OUT_COPY.label"
            :title="SIGN_OUT_COPY.label"
            :loading="signOutBusy"
            @click="onSignOut"
          >
            <i class="bi bi-box-arrow-right" aria-hidden="true"></i>
          </LoadingButton>
        </div>
      </div>
    </nav>
    <div
      class="flex-shrink-0"
      role="status"
      aria-live="polite"
      data-id="app-banner"
    >
      <div
        v-if="verificationBanner !== undefined"
        class="alert alert-warning border-0 rounded-0 mb-0 py-2"
        data-id="protected-mode-banner"
      >
        <div
          class="container d-flex flex-wrap align-items-center justify-content-center gap-3"
        >
          <span>
            <i class="bi bi-shield-exclamation me-1" aria-hidden="true"></i>
            {{ verificationBanner }}
          </span>
        </div>
      </div>
      <div
        v-if="impersonation !== null && !underMaintenance"
        class="alert alert-warning border-0 rounded-0 mb-0 py-2"
        data-id="impersonation-banner"
      >
        <div
          class="container d-flex flex-wrap align-items-center justify-content-center gap-3"
        >
          <span>
            <i class="bi bi-people-fill me-1" aria-hidden="true"></i>
            {{ IMPERSONATION_STRIP_COPY.lead }}
            <strong>{{ impersonation.userName }}</strong>
          </span>
          <LoadingButton
            class="btn-sm btn-outline-dark"
            data-id="impersonation-stop"
            :loading="impersonationStopBusy"
            @click="onImpersonationStop"
          >
            {{ IMPERSONATION_STRIP_COPY.stop }}
          </LoadingButton>
        </div>
      </div>
      <slot name="banner" />
    </div>
    <main
      id="hilos-main-content"
      tabindex="-1"
      class="container flex-grow-1 min-h-0 overflow-auto py-4"
      :class="{ 'd-flex flex-column': underMaintenance }"
    >
      <HilosMaintenance
        v-if="underMaintenance"
        :status="protectedMode"
        :connection="props.connection"
        :admin-surface="currentRoute?.admin ?? false"
      />
      <HilosAccountBlocked
        v-else-if="accountBlocked !== null"
        :notice="accountBlocked"
      />
      <slot v-else />
    </main>
    <footer
      v-if="!underMaintenance"
      class="footer flex-shrink-0 border-top bg-body-tertiary py-2"
      data-id="app-footer"
    >
      <div
        class="container d-flex flex-wrap justify-content-center gap-3 small"
      >
        <HilosLink
          v-for="link in footerLinks"
          :key="link.page"
          class="link-secondary text-decoration-none"
          :to="footerHref(link.page)"
          :data-id="`footer-link-${link.page}`"
        >
          {{ link.label }}
        </HilosLink>
      </div>
    </footer>
    <!-- Transient notices float over the shell, so every page inside it can report
    an outcome without owning a notification surface of its own. -->
    <HilosToastHost :corner="props.toastCorner" />
    <!-- An OAuth trip runs in another window over whatever page started it, so the
    wait belongs to the shell too: the page underneath stays subscribed and alive,
    and no project mounts anything (HIL-633). -->
    <HilosOAuthWaitModal />
  </div>
</template>
