// framework/frontend/react/src/HilosViewportTable.tsx
// HilosViewportTable — the thin React view over the SERVER-WINDOWED
// TableViewportController. Search, sort, and paging change the viewport
// descriptor and are sent to the backend (NO local filtering); live changes
// arrive as pending and are resolved with the Apply button. A removed row
// renders as a placeholder in its slot — the layout never collapses. It holds
// NO table logic (multiframework-core.md): the controller owns the descriptor,
// pending, and Apply. Body cells come from the `row` render prop; the
// placeholder, header, paging, and the pending bar stay framework-owned.
// (Distinct from HilosTable, the client-side view.) A table whose page DECLARED a
// frame draws the bar and the footer from that declaration instead
// (HilosTableBar, HilosTableFooter). Bootstrap classes only.
import { useId } from 'react'
import type { ReactNode } from 'react'
import type {
  HilosTableColumn,
  TableSort,
  TableViewportController,
} from '@hilos/core'

import { HilosTableBar } from './HilosTableBar.js'
import { HilosTableFooter } from './HilosTableFooter.js'
import { useSignal } from './useSignal.js'

/** Props for {@link HilosViewportTable}. */
export interface HilosViewportTableProps<R> {
  /** The headless server-windowed controller driving rows, descriptor, and pending. */
  controller: TableViewportController<R>
  /** Column declarations for the header (labels and sort controls). */
  columns: HilosTableColumn[]
  /** Render the cells of one row; the returned `<td>`s fill the row. */
  row: (row: R, rowKey: string) => ReactNode
  /** Accessible name for the table, rendered as a visually-hidden caption. */
  label?: string
  /** Show the search box above the table. */
  searchable?: boolean
  /** Placeholder for the search box. */
  searchPlaceholder?: string
  /** Message shown when there are no rows. */
  emptyText?: string
  /** Message shown while the first window is still loading. */
  loadingText?: string
  /** Replace the empty-state cell content. */
  empty?: ReactNode
  /** Label shown in a removed row's placeholder slot. */
  placeholderText?: string
  /**
   * The `data-id` the table's root carries, for a page that draws more than one of them:
   * the default is the shared handle, and a second table on the same page names itself so
   * the two can be told apart from outside.
   */
  dataId?: string
}

// A row with an unapplied pending change gets a subtle, theme-aware tint that
// stands out from the zebra striping: amber for a waiting move, red for a
// waiting removal. Bootstrap's contextual row classes carry their own dark-mode
// variants, so they adapt to the active theme with no custom style layer.
const PENDING_ROW_CLASS: Record<'move' | 'remove', string> = {
  move: 'table-warning',
  remove: 'table-danger',
}

/**
 * The framework-owned table chrome over a headless {@link TableViewportController}.
 *
 * @param props The controller, columns, row renderer, and label / search / empty / placeholder config.
 */
export function HilosViewportTable<R>({
  controller,
  columns,
  row,
  label,
  searchable = false,
  searchPlaceholder = 'Search…',
  emptyText = 'No rows.',
  loadingText = 'Loading…',
  empty,
  placeholderText = 'Removed',
  dataId = 'hilos-viewport-table',
}: HilosViewportTableProps<R>) {
  const rows = useSignal(controller.rows)
  const search = useSignal(controller.search)
  const order = useSignal(controller.order)
  const page = useSignal(controller.page)
  const pageCount = useSignal(controller.pageCount)
  const totalCount = useSignal(controller.totalCount)
  const totalExact = useSignal(controller.totalExact)
  const hasNextPage = useSignal(controller.hasNextPage)
  const pendingCount = useSignal(controller.pendingCount)
  const loaded = useSignal(controller.loaded)
  // The declaration does not change over the life of a table, so it is read once
  // rather than wrapped in a signal (tableFrame.ts, HilosTableFrameState).
  const declaration = controller.frame.declaration
  const titleId = useId()
  // A table whose count stopped at its ceiling has no page count to compare against, and
  // the footer is what such a table still needs: it is the only place saying there is more.
  const paginated = pageCount === null || pageCount > 1
  // The total reads as "at least this many" when the count stopped at its ceiling, which is
  // what the trailing plus says.
  const countLabel = totalExact ? `${totalCount} total` : `${totalCount}+ total`

  // The arrow a header carries: every column the order runs by gets one, because
  // an order of two columns is sorted by both of them and a single arrow would
  // name one of the two as the whole answer.
  function sortComponent(key: string): TableSort | undefined {
    return order?.find((component) => component.field === key)
  }

  function sortIcon(key: string): string {
    const component = sortComponent(key)
    if (component === undefined) {
      return 'bi-arrow-down-up text-muted'
    }

    return component.direction === 'asc' ? 'bi-arrow-up' : 'bi-arrow-down'
  }

  // A sortable header reports its current sort state to assistive tech through
  // aria-sort: a sortable-but-unsorted column reports 'none', the active column
  // its direction, and a non-sortable column nothing at all.
  function ariaSort(
    column: HilosTableColumn,
  ): 'ascending' | 'descending' | 'none' | undefined {
    if (!column.sortable) {
      return undefined
    }
    const component = sortComponent(column.key)
    if (component === undefined) {
      return 'none'
    }

    return component.direction === 'asc' ? 'ascending' : 'descending'
  }

  return (
    <div data-id={dataId}>
      {declaration ? (
        <HilosTableBar controller={controller} titleId={titleId} />
      ) : null}

      {/* SCAFFOLD: the bar a table draws from props, kept while the five
          framework pages still pass them. It goes with the props themselves when
          those pages move onto the declaration (HIL-819). */}
      {!declaration && (searchable || pendingCount > 0) ? (
        <div className="d-flex justify-content-between align-items-center gap-2 mb-3">
          {searchable ? (
            <input
              type="search"
              className="form-control"
              placeholder={searchPlaceholder}
              aria-label={searchPlaceholder}
              value={search}
              data-id="hilos-table-search"
              onChange={(event) => controller.setSearch(event.target.value)}
            />
          ) : null}
          {pendingCount > 0 ? (
            <button
              type="button"
              className="btn btn-primary btn-sm text-nowrap d-inline-flex align-items-center gap-2 ms-auto"
              aria-label={`Apply ${pendingCount} pending changes`}
              data-id="hilos-table-apply"
              onClick={() => controller.apply()}
            >
              Apply changes
              <span
                className="badge text-bg-light"
                data-id="hilos-table-pending"
                aria-hidden="true"
              >
                {pendingCount}
              </span>
            </button>
          ) : null}
        </div>
      ) : null}

      <div className="table-responsive">
        <table
          className="table table-striped table-hover align-middle mb-0"
          aria-labelledby={declaration ? titleId : undefined}
        >
          {/* A declared table already shows its name as a heading, and a hidden
              caption repeating it would name the table twice. */}
          {!declaration && label ? (
            <caption className="visually-hidden">{label}</caption>
          ) : null}
          <thead>
            <tr>
              {columns.map((column) => (
                <th
                  key={column.key}
                  scope="col"
                  className={column.headerClass}
                  aria-sort={ariaSort(column)}
                >
                  {column.sortable ? (
                    <button
                      type="button"
                      className="btn btn-link p-0 text-reset text-decoration-none d-inline-flex align-items-center gap-1"
                      data-id={`hilos-table-sort-${column.key}`}
                      onClick={() => controller.setSort(column.key)}
                    >
                      {column.label}
                      <i
                        className={`bi ${sortIcon(column.key)}`}
                        aria-hidden="true"
                      />
                    </button>
                  ) : (
                    column.label
                  )}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((view) => (
              <tr
                key={view.rowKey}
                data-id={`hilos-table-row-${view.rowKey}`}
                className={
                  view.pending ? PENDING_ROW_CLASS[view.pending] : undefined
                }
              >
                {/* A placeholder row carries a null row; the null check also
                    narrows the type for the render prop. */}
                {view.placeholder || view.row === null ? (
                  <td
                    colSpan={columns.length}
                    className="text-center text-muted fst-italic"
                    data-id="hilos-table-placeholder"
                  >
                    {placeholderText}
                  </td>
                ) : (
                  row(view.row, view.rowKey)
                )}
              </tr>
            ))}
            {rows.length === 0 ? (
              <tr>
                <td
                  colSpan={columns.length}
                  className="text-center text-muted py-4"
                >
                  {!loaded ? (
                    <span
                      className="d-inline-flex align-items-center gap-2"
                      role="status"
                      data-id="hilos-table-loading"
                    >
                      <span
                        className="spinner-border spinner-border-sm"
                        aria-hidden="true"
                      />
                      {loadingText}
                    </span>
                  ) : (
                    (empty ?? emptyText)
                  )}
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      {declaration ? <HilosTableFooter controller={controller} /> : null}

      {/* SCAFFOLD: the footer a table draws from its own comparisons, kept for
          the same reason and going the same way as the bar above (HIL-819). */}
      {!declaration && paginated ? (
        <div className="d-flex justify-content-between align-items-center mt-3">
          <span className="text-muted small" data-id="hilos-table-count">
            {countLabel}
          </span>
          <div className="btn-group" role="group" aria-label="Pagination">
            <button
              type="button"
              className="btn btn-outline-secondary btn-sm"
              disabled={page === 0}
              data-id="hilos-table-prev"
              onClick={() => controller.prevPage()}
            >
              Previous
            </button>
            {pageCount === null ? null : (
              <span
                className="btn btn-sm disabled"
                aria-label={`Page ${page + 1} of ${pageCount}`}
                data-id="hilos-table-page"
              >
                {page + 1} / {pageCount}
              </span>
            )}
            <button
              type="button"
              className="btn btn-outline-secondary btn-sm"
              disabled={!hasNextPage}
              data-id="hilos-table-next"
              onClick={() => controller.nextPage()}
            >
              Next
            </button>
          </div>
        </div>
      ) : null}
    </div>
  )
}

// framework/frontend/vue/src/HilosViewportTable.vue
<!-- HilosViewportTable — the thin Vue view over the SERVER-WINDOWED
TableViewportController. Search, sort, and paging change the viewport descriptor
and are sent to the backend (NO local filtering); live changes arrive as pending
and are resolved with the Apply button. A removed row renders as a placeholder in
its slot — the layout never collapses. It holds NO table logic
(multiframework-core.md): the controller owns the descriptor, pending, and Apply.
Body cells come from the `#row` slot; the placeholder, header, paging, and the
pending bar stay framework-owned. (Distinct from HilosTable, the client-side
view.)
It draws its frame from what the page DECLARED (HilosTableBar, HilosTableFooter)
when the controller carries a declaration, and from its own props when it does
not — two epochs of the same table living side by side while the five framework
pages have not moved onto the declaration yet (HIL-819). -->

<script setup lang="ts" generic="R">
import { computed, useId } from 'vue'
import type {
  HilosTableColumn,
  TableSort,
  TableViewportController,
} from '@hilos/core'

import HilosTableBar from './HilosTableBar.vue'
import HilosTableFooter from './HilosTableFooter.vue'
import { useSignal } from './useSignal.js'

const props = withDefaults(
  defineProps<{
    /** The headless server-windowed controller driving rows, descriptor, and pending. */
    controller: TableViewportController<R>
    /** Column declarations for the header (labels and sort controls). */
    columns: HilosTableColumn[]
    /** Accessible name for the table, rendered as a visually-hidden caption. */
    label?: string
    /** Show the search box above the table. */
    searchable?: boolean
    /** Placeholder for the search box. */
    searchPlaceholder?: string
    /** Message shown when there are no rows. */
    emptyText?: string
    /** Message shown while the first window is still loading. */
    loadingText?: string
    /** Label shown in a removed row's placeholder slot. */
    placeholderText?: string
    /**
     * The `data-id` the table's root carries, for a page that draws more than one of
     * them: the default is the shared handle, and a second table on the same page names
     * itself so the two can be told apart from outside.
     */
    dataId?: string
  }>(),
  {
    label: undefined,
    searchable: false,
    searchPlaceholder: 'Search…',
    emptyText: 'No rows.',
    loadingText: 'Loading…',
    placeholderText: 'Removed',
    dataId: 'hilos-viewport-table',
  },
)

// What the page declared about the frame, or null when it declared nothing —
// the one switch between the two epochs of markup. It does not change over the
// life of a table, so it is read once rather than wrapped in a signal.
const declaration = props.controller.frame.declaration

// The declared title names the table through aria-labelledby, so the id is
// minted here — where both the bar that renders the heading and the table that
// points at it can see it (Flow F9).
const titleId = useId()

const rows = useSignal(props.controller.rows)
const search = useSignal(props.controller.search)
const order = useSignal(props.controller.order)
const page = useSignal(props.controller.page)
const pageCount = useSignal(props.controller.pageCount)
const totalCount = useSignal(props.controller.totalCount)
const totalExact = useSignal(props.controller.totalExact)
const hasNextPage = useSignal(props.controller.hasNextPage)
const pendingCount = useSignal(props.controller.pendingCount)
const loaded = useSignal(props.controller.loaded)

// A table whose count stopped at its ceiling has no page count to compare against, and the
// footer is exactly what such a table still needs: it is the only place saying there is more.
const paginated = computed(
  () => pageCount.value === null || pageCount.value > 1,
)

// The total reads as "at least this many" when the count stopped at its ceiling, which is
// what the trailing plus says. Spelling it out in words would say the same thing longer.
const countLabel = computed(() =>
  totalExact.value ? `${totalCount.value} total` : `${totalCount.value}+ total`,
)

// A row with an unapplied pending change gets a subtle, theme-aware tint that
// stands out from the zebra striping: amber for a waiting update, red for a
// waiting removal. Bootstrap's contextual row classes carry their own dark-mode
// variants, so they adapt to the active theme with no custom style layer.
const PENDING_ROW_CLASS: Record<'update' | 'remove', string> = {
  update: 'table-warning',
  remove: 'table-danger',
}

// A row's pending tint, resolved in script: the template `:class` binding does
// not narrow `view.pending` out of its `| null` union, so the record is indexed
// here — where the narrowing holds — rather than inline in the template.
function pendingClass(pending: 'update' | 'remove' | null): string | undefined {
  return pending ? PENDING_ROW_CLASS[pending] : undefined
}

// The arrow a header carries: every column the order runs by gets one, because
// an order of two columns is sorted by both of them and a single arrow would
// name one of the two as the whole answer.
function sortComponent(key: string): TableSort | undefined {
  return order.value?.find((component) => component.field === key)
}

function sortIcon(key: string): string {
  const component = sortComponent(key)
  if (component === undefined) {
    return 'bi-arrow-down-up text-muted'
  }

  return component.direction === 'asc' ? 'bi-arrow-up' : 'bi-arrow-down'
}

// A sortable header reports its current sort state to assistive tech through
// aria-sort: a sortable-but-unsorted column reports 'none', the active column
// its direction, and a non-sortable column nothing at all.
function ariaSort(
  column: HilosTableColumn,
): 'ascending' | 'descending' | 'none' | undefined {
  if (!column.sortable) {
    return undefined
  }
  const component = sortComponent(column.key)
  if (component === undefined) {
    return 'none'
  }

  return component.direction === 'asc' ? 'ascending' : 'descending'
}

function onSearchInput(event: Event): void {
  props.controller.setSearch((event.target as HTMLInputElement).value)
}
</script>

<template>
  <div :data-id="dataId">
    <HilosTableBar
      v-if="declaration"
      :controller="controller"
      :title-id="titleId"
    />

    <!-- SCAFFOLD: the bar a table draws from props, kept while the five
    framework pages still pass them. It goes with the props themselves when
    those pages move onto the declaration (HIL-819); the Apply button of a
    declared table belongs to the pending strip (HIL-793). -->
    <div
      v-if="!declaration && (searchable || pendingCount > 0)"
      class="d-flex justify-content-between align-items-center gap-2 mb-3"
    >
      <input
        v-if="searchable"
        type="search"
        class="form-control"
        :placeholder="searchPlaceholder"
        :aria-label="searchPlaceholder"
        :value="search"
        data-id="hilos-table-search"
        @input="onSearchInput"
      />
      <button
        v-if="pendingCount > 0"
        type="button"
        class="btn btn-primary btn-sm text-nowrap d-inline-flex align-items-center gap-2 ms-auto"
        :aria-label="`Apply ${pendingCount} pending changes`"
        data-id="hilos-table-apply"
        @click="controller.apply()"
      >
        Apply changes
        <span
          class="badge text-bg-light"
          data-id="hilos-table-pending"
          aria-hidden="true"
        >
          {{ pendingCount }}
        </span>
      </button>
    </div>

    <div class="table-responsive">
      <table
        class="table table-striped table-hover align-middle mb-0"
        :aria-labelledby="declaration ? titleId : undefined"
      >
        <!-- A declared table already shows its name as a heading, and a hidden
        caption repeating it would name the table twice (Flow F9). -->
        <caption v-if="!declaration && label" class="visually-hidden">
          {{
            label
          }}
        </caption>
        <thead>
          <tr>
            <th
              v-for="column in columns"
              :key="column.key"
              scope="col"
              :class="column.headerClass"
              :aria-sort="ariaSort(column)"
            >
              <button
                v-if="column.sortable"
                type="button"
                class="btn btn-link p-0 text-reset text-decoration-none d-inline-flex align-items-center gap-1"
                :data-id="`hilos-table-sort-${column.key}`"
                @click="controller.setSort(column.key)"
              >
                {{ column.label }}
                <i :class="['bi', sortIcon(column.key)]" aria-hidden="true"></i>
              </button>
              <template v-else>{{ column.label }}</template>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="view in rows"
            :key="view.rowKey"
            :data-id="`hilos-table-row-${view.rowKey}`"
            :class="pendingClass(view.pending)"
          >
            <td
              v-if="view.placeholder || view.row === null"
              :colspan="columns.length"
              class="text-center text-muted fst-italic"
              data-id="hilos-table-placeholder"
            >
              {{ placeholderText }}
            </td>
            <slot v-else name="row" :row="view.row" :row-key="view.rowKey" />
          </tr>
          <tr v-if="rows.length === 0">
            <td :colspan="columns.length" class="text-center text-muted py-4">
              <span
                v-if="!loaded"
                class="d-inline-flex align-items-center gap-2"
                role="status"
                data-id="hilos-table-loading"
              >
                <span
                  class="spinner-border spinner-border-sm"
                  aria-hidden="true"
                ></span>
                {{ loadingText }}
              </span>
              <slot v-else name="empty">{{ emptyText }}</slot>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <HilosTableFooter v-if="declaration" :controller="controller" />

    <!-- SCAFFOLD: the footer a table draws from its own comparisons, kept for
    the same reason and going the same way as the bar above (HIL-819). -->
    <div
      v-if="!declaration && paginated"
      class="d-flex justify-content-between align-items-center mt-3"
    >
      <span class="text-muted small" data-id="hilos-table-count">
        {{ countLabel }}
      </span>
      <div class="btn-group" role="group" aria-label="Pagination">
        <button
          type="button"
          class="btn btn-outline-secondary btn-sm"
          :disabled="page === 0"
          data-id="hilos-table-prev"
          @click="controller.prevPage()"
        >
          Previous
        </button>
        <span
          v-if="pageCount !== null"
          class="btn btn-sm disabled"
          :aria-label="`Page ${page + 1} of ${pageCount}`"
          data-id="hilos-table-page"
        >
          {{ page + 1 }} / {{ pageCount }}
        </span>
        <button
          type="button"
          class="btn btn-outline-secondary btn-sm"
          :disabled="!hasNextPage"
          data-id="hilos-table-next"
          @click="controller.nextPage()"
        >
          Next
        </button>
      </div>
    </div>
  </div>
</template>
