// framework/frontend/react/src/admin/operations/HilosOperationsPage.tsx
// HilosOperationsPage — the Operations admin page (HilosPages.OPERATIONS). A framework default: a
// thin binding of the page key to the shared admin shell HilosAdminPage, which
// resolves the heading, lead, breadcrumb, and any sub-section cards from the
// @hilos/core admin tree. Implement the page by replacing the shell's default
// body through its children. Bootstrap classes only (styling-rules.md).
import { HilosPages } from '@hilos/core'

import { HilosAdminPage } from '../../HilosAdminPage.js'

/** The Operations admin page: the framework default shell for its key. */
export function HilosOperationsPage() {
  return <HilosAdminPage page={HilosPages.OPERATIONS} />
}

// framework/frontend/vue/src/admin/operations/HilosOperationsPage.vue
<!-- HilosOperationsPage — the Operations admin page (HilosPages.OPERATIONS). A framework default: a
thin binding of the page key to the shared admin shell HilosAdminPage, which
resolves the heading, lead, breadcrumb, and any sub-section cards from the
@hilos/core admin tree. Implement the page by replacing the shell's default body
through its default slot. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosPages } from '@hilos/core'

import HilosAdminPage from '../../HilosAdminPage.vue'
</script>

<template>
  <HilosAdminPage :page="HilosPages.OPERATIONS" />
</template>
