// demo/tasks/frontend/src/views/Hilos/Logs/Rotations.tsx
// The Hilos rotation-history page (HilosPages.LOGS_ROTATIONS): a thin project
// binding of the framework HilosLogsRotationsPage to this app's context. The history
// table, the row view-model, the filters, the header and the four empty states are
// the framework's; the project supplies only the context (the same connection and
// scope stores the other Hilos pages use) and registers the rotations table on its
// backend.
import { HilosLogsRotationsPage } from '@hilos/react'

import { hilosLogsContext } from './hilosLogsContext'

export default function LogsRotations() {
  return <HilosLogsRotationsPage context={hilosLogsContext} />
}

// demo/chat/frontend/src/views/Hilos/Logs/Rotations.vue
<!-- The Hilos rotation-history page (HilosPages.LOGS_ROTATIONS): a thin project
binding of the framework HilosLogsRotationsPage to this app's context. The history
table, the row view-model, the filters, the header and the four empty states are
the framework's; the project supplies only the context (the same connection and
scope stores the other Hilos pages use) and registers the rotations table on its
backend. Bootstrap classes only (styling-rules.md). -->
<script setup lang="ts">
import { HilosLogsRotationsPage } from '@hilos/vue'

import { hilosLogsContext } from './hilosLogsContext'

defineOptions({ name: 'LogsRotationsPage' })
</script>

<template>
  <HilosLogsRotationsPage :context="hilosLogsContext" />
</template>
